
import type { StudyPlan, StudentIntake } from '../types/models';
import { CycleType } from '../types/Types';
import { ResourceService } from './ResourceService';
import { SubjectLoader } from './SubjectLoader';
import dayjs from 'dayjs';
import isBetween from 'dayjs/plugin/isBetween';
import isSameOrBefore from 'dayjs/plugin/isSameOrBefore';
dayjs.extend(isBetween);
dayjs.extend(isSameOrBefore);
import puppeteer, { type PDFOptions, type Browser } from 'puppeteer';
import { type Writable } from 'stream';

// Browser instance management
let sharedBrowser: Browser | null = null;
let browserLaunchPromise: Promise<Browser> | null = null;

/**
 * Get or create a shared browser instance
 */
async function getSharedBrowser(): Promise<Browser> {
  if (sharedBrowser && sharedBrowser.connected) {
    return sharedBrowser;
  }

  if (browserLaunchPromise) {
    return browserLaunchPromise;
  }

  browserLaunchPromise = launchBrowser();
  sharedBrowser = await browserLaunchPromise;
  browserLaunchPromise = null;

  return sharedBrowser;
}

/**
 * Launch a new browser instance with optimized settings
 */
async function launchBrowser(): Promise<Browser> {
  console.log('🌐 Launching shared browser instance...');
  return await puppeteer.launch({
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-gpu',
      '--disable-web-security',
      '--disable-features=VizDisplayCompositor',
      '--run-all-compositor-stages-before-draw',
      '--disable-extensions-http-throttling',
      '--memory-pressure-off',
      '--max_old_space_size=4096'
    ],
    // Use system Chrome if available for better font rendering
    executablePath: process.env.CHROME_PATH || undefined
  });
}

/**
 * Close the shared browser instance
 */
export async function closeSharedBrowser(): Promise<void> {
  if (sharedBrowser) {
    console.log('🔒 Closing shared browser instance...');
    await sharedBrowser.close();
    sharedBrowser = null;
  }
  browserLaunchPromise = null;
}

// Color mapping for different cycle types (matching the original PDFService)
const CYCLE_TYPE_COLORS = {
  [CycleType.C1]: { bg: 'rgb(227, 242, 253)', border: 'rgb(59, 130, 246)' }, // Very light blue
  [CycleType.C2]: { bg: 'rgb(232, 245, 232)', border: 'rgb(34, 197, 94)' }, // Very light green  
  [CycleType.C3]: { bg: 'rgb(252, 228, 236)', border: 'rgb(236, 72, 153)' }, // Very light pink
  [CycleType.C4]: { bg: 'rgb(255, 235, 238)', border: 'rgb(239, 68, 68)' }, // Very light red
  [CycleType.C5]: { bg: 'rgb(243, 229, 245)', border: 'rgb(168, 85, 247)' }, // Very light purple
  [CycleType.C5B]: { bg: 'rgb(243, 229, 245)', border: 'rgb(168, 85, 247)' }, // Very light purple
  [CycleType.C6]: { bg: 'rgb(225, 245, 254)', border: 'rgb(6, 182, 212)' }, // Very light cyan
  [CycleType.C7]: { bg: 'rgb(255, 243, 224)', border: 'rgb(245, 158, 11)' }, // Very light orange
  [CycleType.C8]: { bg: 'rgb(241, 248, 233)', border: 'rgb(132, 204, 22)' }, // Very light lime
} as const;

/**
 * Generate structured PDF that matches Word document format with high-fidelity rendering
 * This is the RECOMMENDED method for professional study plan PDFs
 */
async function generateStructuredPDF(
  studyPlan: StudyPlan,
  studentIntake: StudentIntake,
  filename?: string
): Promise<void> {
  try {
    // Create high-quality HTML template
    const htmlContent = await createStructuredHTML(studyPlan, studentIntake);

    // Generate PDF using Puppeteer
    const pdfBuffer = await generatePDFFromHTML(htmlContent, {
      format: 'A4',
      landscape: true,
      printBackground: true,
      margin: { top: '20px', right: '30px', bottom: '20px', left: '30px' },
      preferCSSPageSize: false,
      displayHeaderFooter: true,
      headerTemplate: '<div></div>',
      footerTemplate: `
        <div style="font-size: 10px; text-align: center; width: 100%; color: #666; margin: 0 15px;">
          <span class="title"></span> - Generated by Helios Study Planner on ${new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      })} - Page <span class="pageNumber"></span> of <span class="totalPages"></span>
        </div>
      `
    });

    // Save the PDF
    await savePDF(pdfBuffer, filename || `study-plan-${studyPlan.study_plan_id || 'plan'}.pdf`);

  } catch (error) {
    console.error('Failed to generate structured PDF:', error);
    throw new Error('Structured PDF generation failed');
  }
}

/**
 * Generate structured PDF and stream directly to output stream (memory efficient)
 * This version avoids loading the entire PDF into memory
 */
async function generateStructuredPDFToStream(
  studyPlan: StudyPlan,
  studentIntake: StudentIntake,
  outputStream: Writable,
  filename?: string
): Promise<void> {
  try {
    // Create high-quality HTML template
    const htmlContent = await createStructuredHTML(studyPlan, studentIntake);

    // Generate PDF using Puppeteer and stream directly to output
    await generatePDFFromHTMLToStream(htmlContent, outputStream, {
      format: 'A4',
      printBackground: true,
      margin: { top: '20px', right: '30px', bottom: '20px', left: '30px' },
      preferCSSPageSize: false,
      displayHeaderFooter: true,
      headerTemplate: '<div></div>',
      footerTemplate: `
        <div style="font-size: 10px; text-align: center; width: 100%; color: #666; margin: 0 15px;">
          <span class="title"></span> - Generated by Helios Study Planner on ${new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      })} - Page <span class="pageNumber"></span> of <span class="totalPages"></span>
        </div>
      `
    });

    console.log(`✅ PDF streamed to output: ${filename || `study-plan-${studyPlan.study_plan_id || 'plan'}.pdf`}`);

  } catch (error) {
    console.error('Failed to generate structured PDF to stream:', error);
    throw new Error('Structured PDF streaming failed');
  }
}

/**
 * Main entry point - defaults to structured PDF (recommended)
 * Matches the exact interface of the original PDFService
 */
export class CalendarPDFService {
  static async generateStudyPlanPDF(
    studyPlan: StudyPlan,
    studentIntake: StudentIntake,
    options: {
      filename: string;
    }
  ): Promise<void> {
    return generateStructuredPDF(studyPlan, studentIntake, options?.filename);
  }

  /**
   * Generate PDF and stream directly to output stream (memory efficient)
   */
  static async generateStudyPlanPDFToStream(
    studyPlan: StudyPlan,
    studentIntake: StudentIntake,
    outputStream: Writable,
    options?: {
      filename?: string;
    }
  ): Promise<void> {
    return generateStructuredPDFToStream(studyPlan, studentIntake, outputStream, options?.filename);
  }

  public static async generateHTML(studyPlan: StudyPlan, studentIntake: StudentIntake,
    options: {
      filename: string;
    }
  ): Promise<string> {
    const htmlContent = await createStructuredHTML(studyPlan, studentIntake);
    // write to file
    const fs = await import('fs');
    const path = await import('path');
    const outputDir = path.join(process.cwd(), 'generated-docs');
    const outputPath = path.join(outputDir, options.filename);
    fs.writeFileSync(outputPath, htmlContent);
    return htmlContent;
  }

  /**
   * Generate HTML and stream directly to output stream (for debugging and faster iteration)
   */
  static async generateHTMLToStream(
    studyPlan: StudyPlan,
    studentIntake: StudentIntake,
    outputStream: Writable,
    options?: {
      filename?: string;
    }
  ): Promise<void> {
    try {
      console.log('🔄 Generating HTML content...');
      const htmlContent = await createStructuredHTML(studyPlan, studentIntake);

      console.log(`📄 HTML content generated: ${htmlContent.length} characters`);
      console.log(`📤 Streaming HTML to output...`);

      // Write HTML content to stream
      outputStream.write(htmlContent);
      outputStream.end();

      console.log(`✅ HTML streamed successfully: ${options?.filename || 'study-plan.html'}`);

    } catch (error) {
      console.error('Failed to generate HTML to stream:', error);
      throw new Error('HTML streaming failed');
    }
  }

  /**
   * Close the shared browser instance (useful for cleanup)
   */
  static async closeBrowser(): Promise<void> {
    return closeSharedBrowser();
  }
}

// ===== CORE PDF GENERATION METHODS =====

/**
 * Generate PDF from HTML using Puppeteer with high-quality settings
 */
async function generatePDFFromHTML(htmlContent: string, options: PDFOptions): Promise<Buffer> {
  try {
    console.log('🚀 Starting PDF generation...');
    console.log(`📄 HTML content size: ${(htmlContent.length / 1024 / 1024).toFixed(2)} MB`);

    // Get shared browser instance
    const browser = await getSharedBrowser();
    const page = await browser.newPage();
    console.log('📄 New page created');

    // Set viewport for consistent rendering
    await page.setViewport({ width: 1200, height: 1600, deviceScaleFactor: 2 });

    // Enable better font rendering
    await page.evaluateOnNewDocument(() => {
      // Improve text rendering
      const style = document.createElement('style');
      style.innerHTML = `
          * {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            text-rendering: optimizeLegibility;
          }
        `;
      document.head.appendChild(style);
    });

    // Set content with proper encoding
    console.log('📝 Setting HTML content...');
    await page.setContent(htmlContent, {
      waitUntil: ['networkidle0', 'domcontentloaded'],
      timeout: 120000 // 2 minutes for limited daily pages
    });
    console.log('✅ HTML content loaded successfully');

    // Wait for any charts or dynamic content to load
    console.log('⏳ Waiting for content to stabilize...');
    await new Promise(resolve => setTimeout(resolve, 3000));

    // Generate PDF with high-quality settings
    console.log('🖨️ Generating PDF...');
    const pdfBuffer = await page.pdf({
      ...options,
      preferCSSPageSize: false,
      printBackground: true
    });

    console.log(`✅ PDF generated successfully: ${(pdfBuffer.length / 1024 / 1024).toFixed(2)} MB`);
    return Buffer.from(pdfBuffer);
  } catch (error) {
    console.error('❌ PDF generation failed:', error);
    throw error;
  } finally {
    // Don't close the shared browser - it will be reused
    console.log('📄 Page processing completed, browser kept alive for reuse');
  }
}

/**
 * Generate PDF from HTML using Puppeteer and stream directly to output stream (memory efficient)
 * This version uses a temporary file approach to avoid memory issues with large PDFs
 */
async function generatePDFFromHTMLToStream(htmlContent: string, outputStream: Writable, options: PDFOptions): Promise<void> {
  const fs = await import('fs');
  const path = await import('path');
  const os = await import('os');

  try {
    console.log('🚀 Starting PDF streaming generation...');
    console.log(`📄 HTML content size: ${(htmlContent.length / 1024 / 1024).toFixed(2)} MB`);

    // Get shared browser instance
    const browser = await getSharedBrowser();
    const page = await browser.newPage();
    console.log('📄 New page created');

    // Set viewport for consistent rendering
    await page.setViewport({ width: 1200, height: 1600, deviceScaleFactor: 2 });

    // Enable better font rendering
    await page.evaluateOnNewDocument(() => {
      // Improve text rendering
      const style = document.createElement('style');
      style.innerHTML = `
          * {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            text-rendering: optimizeLegibility;
          }
        `;
      document.head.appendChild(style);
    });

    // Set content with proper encoding
    console.log('📝 Setting HTML content...');
    await page.setContent(htmlContent, {
      waitUntil: ['networkidle0', 'domcontentloaded'],
      timeout: 120000 // 2 minutes for limited daily pages
    });
    console.log('✅ HTML content loaded successfully');

    // Wait for any charts or dynamic content to load
    // console.log('⏳ Waiting for content to stabilize...');
    // await new Promise(resolve => setTimeout(resolve, 3000));

    // Create a temporary file for the PDF
    const tempDir = os.tmpdir();
    const tempFilePath = path.join(tempDir, `pdf-${Date.now()}-${Math.random().toString(36).substr(2, 9)}.pdf`);

    try {
      // Generate PDF directly to temporary file
      await page.pdf({
        ...options,
        preferCSSPageSize: false,
        printBackground: true,
        path: tempFilePath // This writes directly to file, avoiding memory
      });

      // Stream the temporary file to the output stream
      const readStream = fs.createReadStream(tempFilePath);

      return new Promise<void>((resolve, reject) => {
        readStream.on('error', (error) => {
          // Clean up on read stream error
          try {
            if (fs.existsSync(tempFilePath)) {
              fs.unlinkSync(tempFilePath);
            }
          } catch (cleanupError) {
            console.warn('Failed to clean up temporary PDF file on read error:', cleanupError);
          }
          reject(error);
        });

        outputStream.on('error', (error) => {
          // Clean up on output stream error
          try {
            if (fs.existsSync(tempFilePath)) {
              fs.unlinkSync(tempFilePath);
            }
          } catch (cleanupError) {
            console.warn('Failed to clean up temporary PDF file on output error:', cleanupError);
          }
          reject(error);
        });

        outputStream.on('finish', () => {
          // Clean up after successful completion
          try {
            if (fs.existsSync(tempFilePath)) {
              fs.unlinkSync(tempFilePath);
            }
          } catch (cleanupError) {
            console.warn('Failed to clean up temporary PDF file on finish:', cleanupError);
          }
          resolve();
        });

        readStream.pipe(outputStream);
      });

    } catch (error) {
      // Don't close shared browser on error - let it be reused
      throw error;
    }

  } finally {
    // Don't close the shared browser - it will be reused
    console.log('📄 Streaming page processing completed, browser kept alive for reuse');
  }
}

/**
 * Save PDF to appropriate location (filesystem or browser download)
 */
async function savePDF(pdfBuffer: Buffer, filename: string): Promise<void> {
  if (typeof window !== 'undefined') {
    // Browser environment - trigger download
    const blob = new Blob([new Uint8Array(pdfBuffer)], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    console.log(`📁 PDF download triggered: ${filename}`);
  } else {
    // Node.js environment - save to filesystem
    const fs = await import('fs');
    const path = await import('path');

    const outputDir = path.join(process.cwd(), 'generated-docs');

    // Ensure output directory exists
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    const outputPath = path.join(outputDir, filename);
    fs.writeFileSync(outputPath, pdfBuffer);

    console.log(`✅ PDF saved: ${filename}`);
    console.log(`   📁 Location: ${outputPath}`);
  }
}

// ===== HTML TEMPLATE GENERATION METHODS =====

/**
 * Create structured HTML template for yearly planner book format
 */
async function createStructuredHTML(studyPlan: StudyPlan, studentIntake: StudentIntake): Promise<string> {
  const year = studyPlan.targeted_year || new Date().getFullYear();

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>UPSC Study Planner ${year} - ${studentIntake.personal_details?.full_name || 'Student'}</title>
        ${getStructuredCSS()}
    </head>
    <body>
        <div class="container">
            ${generateCoverPage(studentIntake, year)}
            ${generateBirdsEyeView(studyPlan)}
            ${await generateMonthViewWithDailyPages(studyPlan)}
            ${await generateResourcesTable(studyPlan)}
            ${generateLegend(studyPlan)}
        </div>
    </body>
    </html>`;
}



function generateCoverPage(studentIntake: StudentIntake, year: number): string {
  const pd = studentIntake.personal_details;
  const ss = studentIntake.study_strategy;
  const ps = studentIntake.preparation_background;

  return `
    <div class="cover-page">
        <div class="cover-background">
            <div class="cover-content">
                <div class="cover-header">
                    <div class="cover-logo">
                        <i class="fas fa-graduation-cap"></i>
                    </div>
                    <h1 class="cover-title">UPSC Study Planner</h1>
                    <h2 class="cover-year">${year}</h2>
                </div>
                
                <div class="cover-student-info">
                    <div class="student-name">${pd?.full_name || 'Student Name'}</div>
                    <div class="student-details">
                        <div class="detail-item">
                            <span class="detail-label">Email:</span>
                            <span class="detail-value">${pd?.email || 'N/A'}</span>
                        </div>
                        <div class="detail-item">
                            <span class="detail-label">Phone:</span>
                            <span class="detail-value">${pd?.phone_number || 'N/A'}</span>
                        </div>
                        <div class="detail-item">
                            <span class="detail-label">Location:</span>
                            <span class="detail-value">${pd?.present_location || 'N/A'}</span>
                        </div>
                        <div class="detail-item">
                            <span class="detail-label">Target Year:</span>
                            <span class="detail-value">${studentIntake.target_year || 'N/A'}</span>
                        </div>
                    </div>
                </div>
                
                <div class="cover-study-info">
                    <div class="study-details-grid">
                        <div class="study-detail-card">
                            <div class="study-detail-icon">📚</div>
                            <div class="study-detail-title">Weekly Hours</div>
                            <div class="study-detail-value">${ss?.weekly_study_hours || 'N/A'} hrs</div>
                        </div>
                        <div class="study-detail-card">
                            <div class="study-detail-icon">🎯</div>
                            <div class="study-detail-title">Study Approach</div>
                            <div class="study-detail-value">${ss?.study_approach || 'N/A'}</div>
                        </div>
                        <div class="study-detail-card">
                            <div class="study-detail-icon">📖</div>
                            <div class="study-detail-title">Optional Subject</div>
                            <div class="study-detail-value">${studentIntake.optional_subject?.optional_subject_name || 'N/A'}</div>
                        </div>
                        <div class="study-detail-card">
                            <div class="study-detail-icon">🏆</div>
                            <div class="study-detail-title">Previous Attempts</div>
                            <div class="study-detail-value">${ps?.number_of_attempts || 'N/A'}</div>
                        </div>
                    </div>
                </div>
                
                <div class="cover-footer">
                    <div class="cover-quote">"Success is the sum of small efforts repeated day in and day out."</div>
                    <div class="cover-generated">Generated by Helios Study Planner</div>
                </div>
            </div>
        </div>
    </div>`;
}


async function generateResourcesTable(studyPlan: StudyPlan): Promise<string> {
  const uniqueSubjects = getUniqueSubjects(studyPlan);
  let html = `
    <div class="resources-table-section">
        <div class="resources-table-title">
            <i class="fas fa-table"></i>
            Comprehensive Resources by Subject
        </div>
        
        <table class="subject-resources-table">
            <thead>
                <tr>
                    <th>Subject</th>
                    <th>Primary Books</th>
                    <th>Video Content</th>
                    <th>Practice Materials</th>
                    <th>Current Affairs</th>
                </tr>
            </thead>
            <tbody>
    `;

  for (const subjectCode of uniqueSubjects) {
    const subjectName = getSubjectName(subjectCode);
    const resources = await ResourceService.getResourcesForSubject(subjectCode);

    html += `
      <tr>
          <td class="subject-name">${subjectName}</td>
          <td>
              ${resources.primary_books.map(r => `<div class="resource-list-item">${r.resource_title}</div>`).join('')}
          </td>
          <td>
              ${resources.video_content.map(r => `<div class="resource-list-item">${r.resource_title}</div>`).join('')}
          </td>
          <td>
              ${resources.practice_resources.map(r => `<div class="resource-list-item">${r.resource_title}</div>`).join('')}
          </td>
          <td>
              ${resources.current_affairs_sources.map(r => `<div class="resource-list-item">${r.resource_title}</div>`).join('')}
          </td>
      </tr>
      `;
  }

  html += `
            </tbody>
        </table>
    </div>
    `;

  return html;
}

function generateLegend(studyPlan: StudyPlan): string {
  const cycles = studyPlan.cycles || [];
  const uniqueSubjects = getUniqueSubjects(studyPlan);

  let html = `
    <div class="legend">
        <div class="legend-title">
            <i class="fas fa-info-circle"></i>
            Legend & Study Phases
        </div>
        <div class="legend-grid">
    `;

  cycles.forEach((cycle) => {
    html += `
      <div class="legend-item">
          <div class="legend-color" style="background: ${CYCLE_TYPE_COLORS[cycle.cycleType as keyof typeof CYCLE_TYPE_COLORS]?.bg}; border: 1px solid ${CYCLE_TYPE_COLORS[cycle.cycleType as keyof typeof CYCLE_TYPE_COLORS]?.border};"></div>
          <div class="legend-text">${cycle.cycleName}</div>
      </div>
      `;
  });

  uniqueSubjects.forEach(subject => {
    const subjectName = getSubjectName(subject).toLowerCase();
    html += `
        <div class="legend-item">
            <div class="legend-color subject-block ${subjectName}"></div>
            <div class="legend-text">${getSubjectName(subject)}</div>
        </div>
        `;
  });

  html += `
        </div>
    </div>
    `;

  return html;
}

function getStructuredCSS(): string {
  return `
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Lora:wght@400;700&family=Roboto:wght@400;500;700&display=swap');

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Roboto', sans-serif;
            background: white;
            font-size: 10pt;
            color: #333;
        }

        .container {
            width: 100%;
            margin: 0 auto;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #ccc;
        }

        .header h1 {
            font-size: 24pt;
            font-weight: 700;
            margin-bottom: 5px;
        }

        .header p {
            font-size: 12pt;
            color: #666;
        }

        .student-profile {
            margin-bottom: 20px;
            page-break-inside: avoid;
            page-break-after: always;
        }

        .profile-header {
            text-align: center;
            margin-bottom: 20px;
        }

        .profile-title {
            font-size: 18pt;
            font-weight: 700;
            margin-bottom: 5px;
        }

        .profile-subtitle {
            font-size: 11pt;
            color: #666;
        }

        .profile-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
        }

        .profile-card {
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 15px;
        }

        .profile-card-title {
            font-size: 12pt;
            font-weight: 700;
            margin-bottom: 10px;
            border-bottom: 1px solid #eee;
            padding-bottom: 5px;
        }

        .profile-item {
            display: flex;
            justify-content: space-between;
            padding: 5px 0;
        }

        .profile-label {
            font-weight: 700;
        }

        .calendar-section {
            width: 100%;
        }

        .section-title {
            font-size: 16pt;
            font-weight: 700;
            margin-top: 30px;
            margin-bottom: 15px;
            border-bottom: 1px solid #ccc;
            padding-bottom: 5px;
            page-break-before: always;
        }

        .section-title.no-page-break {
            page-break-before: auto;
        }

        .year-calendar {
            display: grid;
            grid-template-columns: repeat(6, 1fr);
            gap: 0;
            page-break-inside: avoid;
            margin-bottom: 20px;
        }


        .month-card {
            border: none;
            border-radius: 0;
            padding: 0;
            margin: 0;
        }

        .cycle-label {
            font-size: 6pt;
            font-weight: 700;
            color: #333;
            text-align: center;
            margin-bottom: 3px;
            background: #e0e0e0;
            padding: 1px 2px;
            border-radius: 2px;
        }

        .month-header {
            text-align: center;
            margin-bottom: 4px;
            padding: 0 2px;
        }

        .month-name {
            font-size: 8pt;
            font-weight: 700;
            color: #333;
        }

        .month-year {
            font-size: 6pt;
            color: #666;
        }

        .month-grid {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            gap: 1px;
            padding: 0 2px;
        }

        .day-header {
            text-align: center;
            font-weight: 700;
            font-size: 5pt;
            padding: 1px;
        }

        .day-cell {
            aspect-ratio: 1;
            display: flex;
            align-items: center;
            justify-content: center;
            border-radius: 2px;
            font-size: 5pt;
            min-height: 8px;
        }

        .day-cell.cycle-phase-1 { background-color: #e3f2fd; }
        .day-cell.cycle-phase-2 { background-color: #e8f5e9; }
        .day-cell.cycle-phase-3 { background-color: #fff3e0; }
        .day-cell.cycle-phase-4 { background-color: #f3e5f5; }
        .day-cell.revision { background-color: #fffde7; }
        .day-cell.exam { background-color: #ffebee; }

        .month-card.cycle-c1 { background-color: rgb(227, 242, 253); border-color: rgb(59, 130, 246); }
        .month-card.cycle-c2 { background-color: rgb(232, 245, 232); border-color: rgb(34, 197, 94); }
        .month-card.cycle-c3 { background-color: rgb(252, 228, 236); border-color: rgb(236, 72, 153); }
        .month-card.cycle-c4 { background-color: rgb(255, 235, 238); border-color: rgb(239, 68, 68); }
        .month-card.cycle-c5 { background-color: rgb(243, 229, 245); border-color: rgb(168, 85, 247); }
        .month-card.cycle-c5b { background-color: rgb(243, 229, 245); border-color: rgb(168, 85, 247); }
        .month-card.cycle-c6 { background-color: rgb(225, 245, 254); border-color: rgb(6, 182, 212); }
        .month-card.cycle-c7 { background-color: rgb(255, 243, 224); border-color: rgb(245, 158, 11); }
        .month-card.cycle-c8 { background-color: rgb(241, 248, 233); border-color: rgb(132, 204, 22); }

        .month-day-cell.cycle-c1 { background-color: rgb(227, 242, 253); }
        .month-day-cell.cycle-c2 { background-color: rgb(232, 245, 232); }
        .month-day-cell.cycle-c3 { background-color: rgb(252, 228, 236); }
        .month-day-cell.cycle-c4 { background-color: rgb(255, 235, 238); }
        .month-day-cell.cycle-c5 { background-color: rgb(243, 229, 245); }
        .month-day-cell.cycle-c5b { background-color: rgb(243, 229, 245); }
        .month-day-cell.cycle-c6 { background-color: rgb(225, 245, 254); }
        .month-day-cell.cycle-c7 { background-color: rgb(255, 243, 224); }
        .month-day-cell.cycle-c8 { background-color: rgb(241, 248, 233); }

        .month-detail {
            page-break-before: always;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }

        .month-detail-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }

        .month-detail-title {
            font-size: 18pt;
            font-weight: 700;
        }

        .month-detail-year {
            font-size: 14pt;
            color: #666;
        }

        .month-detail-grid {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            gap: 1px;
            border: 1px solid #ddd;
            flex: 1;
        }

        .monthly-resources {
            margin-top: 20px;
            padding: 20px;
            background: #f9f9f9;
            border-radius: 8px;
        }

        .monthly-resources-title {
            font-size: 14pt;
            font-weight: 700;
            margin-bottom: 15px;
            color: #333;
            border-bottom: 2px solid #ddd;
            padding-bottom: 8px;
        }

        .monthly-resources-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 8px;
        }

        .monthly-resource-card {
            background: white;
            border: 1px solid #ddd;
            border-radius: 6px;
            padding: 10px;
        }

        .monthly-resource-subject {
            font-size: 12pt;
            font-weight: 700;
            margin-bottom: 10px;
            color: #333;
            border-bottom: 1px solid #eee;
            padding-bottom: 5px;
        }

        .monthly-resource-lists {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 6px;
        }

        .monthly-resource-category {
            margin-bottom: 6px;
        }

        .monthly-resource-category-title {
            font-size: 9pt;
            font-weight: 700;
            margin-bottom: 5px;
            color: #555;
        }

        .monthly-resource-list {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .monthly-resource-list li {
            font-size: 8pt;
            padding: 2px 0;
            color: #666;
            border-left: 2px solid #ddd;
            padding-left: 8px;
            margin-bottom: 2px;
        }

        .month-day-header {
            background: #f9f9f9;
            padding: 8px 4px;
            text-align: center;
            font-weight: 700;
            font-size: 9pt;
            border: 1px solid #ddd;
        }

        .month-day-cell {
            border: 1px solid #ddd;
            min-height: 70px;
            padding: 4px;
        }

        .month-day-number {
            font-weight: 700;
            font-size: 9pt;
            margin-bottom: 4px;
        }

        .subject-block {
            border-radius: 4px;
            padding: 2px 4px;
            margin: 2px 0;
            font-size: 7pt;
            font-weight: 700;
            text-align: center;
        }

        .subject-block.history { background-color: #ffcdd2; }
        .subject-block.geography { background-color: #c8e6c9; }
        .subject-block.polity { background-color: #bbdefb; }
        .subject-block.economics { background-color: #fff9c4; }
        .subject-block.science { background-color: #d1c4e9; }
        .subject-block.current-affairs { background-color: #f8bbd0; }
        .subject-block.optional { background-color: #dcedc8; }

        .week-calendar {
            page-break-before: always;
        }

        .week-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }

        .week-title {
            font-size: 16pt;
            font-weight: 700;
        }

        .week-grid {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            gap: 10px;
        }

        .week-day {
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 10px;
        }

        .week-day-header {
            text-align: center;
            margin-bottom: 10px;
        }

        .week-day-name {
            font-weight: 700;
            font-size: 10pt;
        }

        .week-day-number {
            font-size: 14pt;
            font-weight: 700;
            margin-top: 2px;
        }

        .daily-tasks {
            margin-top: 10px;
        }

        .task-item {
            border-left: 3px solid;
            padding: 5px 8px;
            margin-bottom: 5px;
            font-size: 8pt;
        }

        .task-item.history { border-left-color: #e57373; }
        .task-item.geography { border-left-color: #81c784; }
        .task-item.polity { border-left-color: #64b5f6; }
        .task-item.economics { border-left-color: #fff176; }
        .task-item.science { border-left-color: #9575cd; }
        .task-item.current-affairs { border-left-color: #f06292; }
        .task-item.optional { border-left-color: #aed581; }

        .resources-table-section {
            page-break-before: always;
        }

        .subject-resources-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 9pt;
        }

        .subject-resources-table th, .subject-resources-table td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
        }

        .subject-resources-table th {
            font-weight: 700;
            background-color: #f9f9f9;
        }

        .subject-name {
            font-weight: 700;
        }

        .legend {
            page-break-before: always;
        }

        .legend-title {
            font-size: 14pt;
            font-weight: 700;
            margin-bottom: 10px;
        }

        .legend-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 10px;
        }

        .legend-item {
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .legend-color {
            width: 16px;
            height: 16px;
            border-radius: 4px;
        }

        /* Cover Page Styles */
        .cover-page {
            page-break-after: always;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }

        .cover-background {
            width: 100%;
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            position: relative;
        }

        .cover-content {
            text-align: center;
            max-width: 800px;
            padding: 40px;
        }

        .cover-header {
            margin-bottom: 60px;
        }

        .cover-logo {
            font-size: 60pt;
            margin-bottom: 20px;
            opacity: 0.9;
        }

        .cover-title {
            font-size: 36pt;
            font-weight: 700;
            margin-bottom: 10px;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
        }

        .cover-year {
            font-size: 24pt;
            font-weight: 400;
            opacity: 0.9;
        }

        .cover-student-info {
            margin-bottom: 50px;
            background: rgba(255,255,255,0.1);
            padding: 30px;
            border-radius: 15px;
            backdrop-filter: blur(10px);
        }

        .student-name {
            font-size: 28pt;
            font-weight: 700;
            margin-bottom: 20px;
            text-shadow: 1px 1px 2px rgba(0,0,0,0.3);
        }

        .student-details {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 15px;
        }

        .detail-item {
            display: flex;
            justify-content: space-between;
            padding: 8px 0;
            border-bottom: 1px solid rgba(255,255,255,0.2);
        }

        .detail-label {
            font-weight: 500;
            opacity: 0.8;
        }

        .detail-value {
            font-weight: 600;
        }

        .cover-study-info {
            margin-bottom: 40px;
        }

        .study-details-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
        }

        .study-detail-card {
            background: rgba(255,255,255,0.1);
            padding: 20px;
            border-radius: 10px;
            backdrop-filter: blur(5px);
        }

        .study-detail-icon {
            font-size: 24pt;
            margin-bottom: 10px;
        }

        .study-detail-title {
            font-size: 10pt;
            opacity: 0.8;
            margin-bottom: 5px;
        }

        .study-detail-value {
            font-size: 14pt;
            font-weight: 600;
        }

        .cover-footer {
            margin-top: 40px;
        }

        .cover-quote {
            font-size: 14pt;
            font-style: italic;
            margin-bottom: 20px;
            opacity: 0.9;
        }

        .cover-generated {
            font-size: 10pt;
            opacity: 0.7;
        }

        /* Daily Views Styles */
        .daily-views-section {
            page-break-before: always;
        }

        .daily-page {
            page-break-before: always;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            background: white;
        }

        .daily-header {
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            padding: 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 3px solid #ddd;
        }

        .daily-header.cycle-c1 { background: linear-gradient(135deg, rgb(227, 242, 253) 0%, rgb(59, 130, 246) 100%); }
        .daily-header.cycle-c2 { background: linear-gradient(135deg, rgb(232, 245, 232) 0%, rgb(34, 197, 94) 100%); }
        .daily-header.cycle-c3 { background: linear-gradient(135deg, rgb(252, 228, 236) 0%, rgb(236, 72, 153) 100%); }
        .daily-header.cycle-c4 { background: linear-gradient(135deg, rgb(255, 235, 238) 0%, rgb(239, 68, 68) 100%); }
        .daily-header.cycle-c5 { background: linear-gradient(135deg, rgb(243, 229, 245) 0%, rgb(168, 85, 247) 100%); }
        .daily-header.cycle-c5b { background: linear-gradient(135deg, rgb(243, 229, 245) 0%, rgb(168, 85, 247) 100%); }
        .daily-header.cycle-c6 { background: linear-gradient(135deg, rgb(225, 245, 254) 0%, rgb(6, 182, 212) 100%); }
        .daily-header.cycle-c7 { background: linear-gradient(135deg, rgb(255, 243, 224) 0%, rgb(245, 158, 11) 100%); }
        .daily-header.cycle-c8 { background: linear-gradient(135deg, rgb(241, 248, 233) 0%, rgb(132, 204, 22) 100%); }

        .daily-date {
            text-align: left;
        }

        .daily-day-name {
            font-size: 18pt;
            font-weight: 700;
            color: #333;
        }

        .daily-day-number {
            font-size: 32pt;
            font-weight: 700;
            color: #333;
            line-height: 1;
        }

        .daily-month-year {
            font-size: 12pt;
            color: #666;
            margin-top: 5px;
        }

        .daily-cycle-info {
            text-align: right;
        }

        .cycle-badge {
            background: rgba(255,255,255,0.9);
            padding: 8px 16px;
            border-radius: 20px;
            font-size: 10pt;
            font-weight: 600;
            color: #333;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .daily-content {
            flex: 1;
            padding: 20px;
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        .daily-tasks-section {
            flex: 1;
        }

        .daily-tasks-title {
            font-size: 14pt;
            font-weight: 700;
            margin-bottom: 15px;
            color: #333;
            border-bottom: 2px solid #ddd;
            padding-bottom: 8px;
        }

        .daily-tasks-list {
            display: flex;
            flex-direction: column;
            gap: 10px;
        }

        .daily-task-item {
            display: flex;
            align-items: center;
            gap: 15px;
            padding: 15px;
            border: 1px solid #ddd;
            border-radius: 8px;
            background: #f9f9f9;
        }

        .daily-task-item.study { border-left: 4px solid #4CAF50; }
        .daily-task-item.revision { border-left: 4px solid #FF9800; }
        .daily-task-item.practice { border-left: 4px solid #2196F3; }
        .daily-task-item.current-affairs { border-left: 4px solid #E91E63; }
        .daily-task-item.optional { border-left: 4px solid #9C27B0; }

        .task-type-badge {
            font-size: 16pt;
            width: 40px;
            height: 40px;
            display: flex;
            align-items: center;
            justify-content: center;
            background: white;
            border-radius: 50%;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .task-content {
            flex: 1;
        }

        .task-subject {
            font-size: 12pt;
            font-weight: 700;
            color: #333;
            margin-bottom: 5px;
        }

        .task-description {
            font-size: 10pt;
            color: #666;
            margin-bottom: 5px;
        }

        .task-time {
            font-size: 9pt;
            color: #888;
            font-style: italic;
        }

        .task-checkbox {
            width: 30px;
            height: 30px;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .checkbox {
            font-size: 16pt;
            color: #666;
        }

        .no-tasks {
            text-align: center;
            padding: 40px;
            color: #999;
        }

        .no-tasks i {
            font-size: 24pt;
            margin-bottom: 10px;
            display: block;
        }

        .daily-notes-section {
            flex: 1;
        }

        .daily-notes-title {
            font-size: 14pt;
            font-weight: 700;
            margin-bottom: 15px;
            color: #333;
            border-bottom: 2px solid #ddd;
            padding-bottom: 8px;
        }

        .notes-area {
            background: #f9f9f9;
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 15px;
            min-height: 200px;
        }

        .notes-line {
            height: 20px;
            border-bottom: 1px solid #eee;
            margin-bottom: 10px;
        }

        .daily-progress-section {
            margin-top: 20px;
        }

        .daily-progress-title {
            font-size: 14pt;
            font-weight: 700;
            margin-bottom: 15px;
            color: #333;
            border-bottom: 2px solid #ddd;
            padding-bottom: 8px;
        }

        .progress-items {
            display: flex;
            flex-direction: column;
            gap: 15px;
        }

        .progress-item {
            display: flex;
            align-items: center;
            gap: 15px;
        }

        .progress-label {
            font-size: 10pt;
            font-weight: 600;
            color: #333;
            min-width: 120px;
        }

        .progress-bar {
            flex: 1;
            height: 20px;
            background: #f0f0f0;
            border-radius: 10px;
            overflow: hidden;
            border: 1px solid #ddd;
        }

        .progress-fill {
            height: 100%;
            background: linear-gradient(90deg, #4CAF50, #45a049);
            transition: width 0.3s ease;
        }

        .progress-value {
            font-size: 10pt;
            font-weight: 600;
            color: #666;
            min-width: 60px;
            text-align: right;
        }

        /* Weekly Views Styles */
        .weekly-views-section {
            page-break-before: always;
        }

        .weekly-page {
            page-break-before: always;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            background: white;
        }

        .weekly-header {
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            padding: 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 3px solid #ddd;
        }

        .weekly-header.cycle-c1 { background: linear-gradient(135deg, rgb(227, 242, 253) 0%, rgb(59, 130, 246) 100%); }
        .weekly-header.cycle-c2 { background: linear-gradient(135deg, rgb(232, 245, 232) 0%, rgb(34, 197, 94) 100%); }
        .weekly-header.cycle-c3 { background: linear-gradient(135deg, rgb(252, 228, 236) 0%, rgb(236, 72, 153) 100%); }
        .weekly-header.cycle-c4 { background: linear-gradient(135deg, rgb(255, 235, 238) 0%, rgb(239, 68, 68) 100%); }
        .weekly-header.cycle-c5 { background: linear-gradient(135deg, rgb(243, 229, 245) 0%, rgb(168, 85, 247) 100%); }
        .weekly-header.cycle-c5b { background: linear-gradient(135deg, rgb(243, 229, 245) 0%, rgb(168, 85, 247) 100%); }
        .weekly-header.cycle-c6 { background: linear-gradient(135deg, rgb(225, 245, 254) 0%, rgb(6, 182, 212) 100%); }
        .weekly-header.cycle-c7 { background: linear-gradient(135deg, rgb(255, 243, 224) 0%, rgb(245, 158, 11) 100%); }
        .weekly-header.cycle-c8 { background: linear-gradient(135deg, rgb(241, 248, 233) 0%, rgb(132, 204, 22) 100%); }

        .weekly-title {
            text-align: left;
        }

        .weekly-range {
            font-size: 18pt;
            font-weight: 700;
            color: white;
            margin-bottom: 5px;
        }

        .weekly-subtitle {
            font-size: 12pt;
            color: rgba(255, 255, 255, 0.9);
            font-weight: 500;
        }

        .weekly-cycle-info {
            text-align: right;
        }

        .weekly-content {
            flex: 1;
            padding: 20px;
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        .weekly-grid {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            gap: 15px;
            flex: 1;
            min-height: 400px;
        }

        .weekly-day-column {
            background: #f8f9fa;
            border: 2px solid #e9ecef;
            border-radius: 12px;
            display: flex;
            flex-direction: column;
            overflow: hidden;
        }

        .weekly-day-column.cycle-c1 { background: rgb(227, 242, 253); border-color: rgb(59, 130, 246); }
        .weekly-day-column.cycle-c2 { background: rgb(232, 245, 232); border-color: rgb(34, 197, 94); }
        .weekly-day-column.cycle-c3 { background: rgb(252, 228, 236); border-color: rgb(236, 72, 153); }
        .weekly-day-column.cycle-c4 { background: rgb(255, 235, 238); border-color: rgb(239, 68, 68); }
        .weekly-day-column.cycle-c5 { background: rgb(243, 229, 245); border-color: rgb(168, 85, 247); }
        .weekly-day-column.cycle-c5b { background: rgb(243, 229, 245); border-color: rgb(168, 85, 247); }
        .weekly-day-column.cycle-c6 { background: rgb(225, 245, 254); border-color: rgb(6, 182, 212); }
        .weekly-day-column.cycle-c7 { background: rgb(255, 243, 224); border-color: rgb(245, 158, 11); }
        .weekly-day-column.cycle-c8 { background: rgb(241, 248, 233); border-color: rgb(132, 204, 22); }

        .weekly-day-column.empty-day {
            background: #f1f3f4;
            border-color: #dadce0;
            opacity: 0.6;
        }

        .day-header {
            background: rgba(255, 255, 255, 0.8);
            padding: 12px 8px;
            text-align: center;
            border-bottom: 1px solid rgba(0, 0, 0, 0.1);
        }

        .day-name {
            font-size: 10pt;
            font-weight: 600;
            color: #333;
            margin-bottom: 4px;
        }

        .day-number {
            font-size: 14pt;
            font-weight: 700;
            color: #333;
        }

        .day-tasks {
            flex: 1;
            padding: 8px;
            display: flex;
            flex-direction: column;
            gap: 6px;
            overflow-y: auto;
        }

        .weekly-task-item {
            background: white;
            border: 1px solid #e0e0e0;
            border-radius: 8px;
            padding: 8px;
            display: flex;
            align-items: flex-start;
            gap: 8px;
            font-size: 8pt;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        }

        .weekly-task-item.theory { border-left: 4px solid #2196F3; }
        .weekly-task-item.practice { border-left: 4px solid #4CAF50; }
        .weekly-task-item.revision { border-left: 4px solid #FF9800; }
        .weekly-task-item.test { border-left: 4px solid #F44336; }

        .task-type-badge {
            font-size: 10pt;
            min-width: 16px;
            text-align: center;
        }

        .task-content {
            flex: 1;
            min-width: 0;
        }

        .task-subject {
            font-weight: 600;
            color: #333;
            margin-bottom: 2px;
            font-size: 9pt;
        }

        .task-description {
            color: #666;
            font-size: 8pt;
            margin-bottom: 2px;
            line-height: 1.2;
        }

        .task-time {
            color: #888;
            font-size: 7pt;
            font-weight: 500;
        }

        .task-checkbox {
            margin-left: auto;
        }

        .checkbox {
            font-size: 10pt;
            color: #666;
        }

        .no-tasks {
            text-align: center;
            color: #999;
            font-size: 8pt;
            padding: 20px 10px;
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 8px;
        }

        .no-tasks i {
            font-size: 16pt;
            opacity: 0.5;
        }

        .weekly-notes-section {
            margin-top: 20px;
        }

        .weekly-notes-title {
            font-size: 14pt;
            font-weight: 700;
            margin-bottom: 15px;
            color: #333;
            border-bottom: 2px solid #ddd;
            padding-bottom: 8px;
        }

        .weekly-notes-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
        }

        .notes-column {
            background: #f8f9fa;
            border: 1px solid #e9ecef;
            border-radius: 8px;
            padding: 15px;
        }

        .notes-label {
            font-size: 10pt;
            font-weight: 600;
            color: #333;
            margin-bottom: 10px;
            text-align: center;
        }

        .notes-area {
            display: flex;
            flex-direction: column;
            gap: 8px;
        }

        .notes-line {
            height: 1px;
            background: #ddd;
            margin: 2px 0;
        }

        .weekly-progress-section {
            margin-top: 20px;
        }

        .weekly-progress-title {
            font-size: 14pt;
            font-weight: 700;
            margin-bottom: 15px;
            color: #333;
            border-bottom: 2px solid #ddd;
            padding-bottom: 8px;
        }

        .progress-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
        }

    </style>
    `;
}


/**
 * Get unique subjects from study plan
 */
function getUniqueSubjects(studyPlan: StudyPlan): string[] {
  const subjects = new Set<string>();
  studyPlan.cycles?.forEach(cycle => {
    cycle.cycleBlocks?.forEach(block => {
      block.subjects?.forEach(subject => subjects.add(subject));
    });
  });
  return Array.from(subjects);
}

/**
 * Get subject name from subject code
 */
function getSubjectName(subjectCode: string): string {
  const subject = SubjectLoader.getSubjectByCode(subjectCode);
  return subject?.subjectName || subjectCode;
}


export function generateBirdsEyeView(studyPlan: StudyPlan): string {
  const cycles = studyPlan.cycles || [];
  let html = `<div class="year-calendar">`;

  const minDate = dayjs(studyPlan.start_date);
  const maxDate = dayjs(`${studyPlan.targeted_year}-08-31`);
  const endDate = maxDate.endOf('month');

  for (
    let currentDate = minDate.startOf('month');
    currentDate.isSameOrBefore(endDate, 'month');
    currentDate = currentDate.add(1, 'month')
  ) {
    const monthDate = currentDate;
    const monthName = monthDate.format('MMM'); // Use abbreviated month name

    let cycleLabel = '';
    let cycleClass = '';
    for (const cycle of cycles) {
      const cycleStart = dayjs(cycle.cycleStartDate);
      const cycleEnd = dayjs(cycle.cycleEndDate);
      if (monthDate.isBetween(cycleStart, cycleEnd, 'month', '[]')) {
        cycleLabel = cycle.cycleName || cycle.cycleType;
        cycleClass = `cycle-${cycle.cycleType.toLowerCase()}`;
        break;
      }
    }

    html += `
    <div class="month-card ${cycleClass}">
        <div class="cycle-label">${cycleLabel.replace(/ Cycle$/, '')}</div>
        <div class="month-header">
            <div class="month-name">${monthName.toUpperCase()} ${monthDate.format('YYYY')}</div>
        </div>
        <div class="month-grid">
            <div class="day-header">S</div>
            <div class="day-header">M</div>
            <div class="day-header">T</div>
            <div class="day-header">W</div>
            <div class="day-header">T</div>
            <div class="day-header">F</div>
            <div class="day-header">S</div>
    `;

    const daysInMonth = monthDate.daysInMonth();
    const firstDayOfMonth = monthDate.startOf('month').day();

    for (let j = 0; j < firstDayOfMonth; j++) {
      html += '<div class="day-cell"></div>';
    }

    for (let day = 1; day <= daysInMonth; day++) {
      html += `<div class="day-cell">${day}</div>`;
    }

    html += `
        </div>
    </div>
    `;
  }

  html += `</div>`;
  return html;
}

async function generateMonthlyResources(studyPlan: StudyPlan, monthDate: dayjs.Dayjs): Promise<string> {
  const cycles = studyPlan.cycles || [];
  const monthStart = monthDate.startOf('month');
  const monthEnd = monthDate.endOf('month');

  // Get all subjects that are active in this month
  const monthlySubjects = new Set<string>();

  for (const cycle of cycles) {
    for (const block of cycle.cycleBlocks) {
      const blockStart = dayjs(block.block_start_date);
      const blockEnd = dayjs(block.block_end_date);

      // Check if block overlaps with this month
      if (blockStart.isBefore(monthEnd) && blockEnd.isAfter(monthStart)) {
        for (const subject of block.subjects) {
          monthlySubjects.add(subject);
        }
      }
    }
  }

  if (monthlySubjects.size === 0) {
    return '<div class="monthly-resources"><p>No resources for this month.</p></div>';
  }

  let html = `
    <div class="monthly-resources">
        <div class="monthly-resources-title">
            <i class="fas fa-book"></i>
            Resources for ${monthDate.format('MMMM YYYY')}
        </div>
        <div class="monthly-resources-grid">
  `;

  for (const subjectCode of Array.from(monthlySubjects)) {
    const subjectName = getSubjectName(subjectCode);
    const resources = await ResourceService.getResourcesForSubject(subjectCode);

    html += `
      <div class="monthly-resource-card">
          <div class="monthly-resource-subject">${subjectName}</div>
          <div class="monthly-resource-lists">
              <div class="monthly-resource-category">
                  <div class="monthly-resource-category-title">📚 Primary Books</div>
                  <ul class="monthly-resource-list">
                      ${resources.primary_books.map(r => `<li>${r.resource_title}</li>`).join('')}
                  </ul>
              </div>
              <div class="monthly-resource-category">
                  <div class="monthly-resource-category-title">🎥 Video Content</div>
                  <ul class="monthly-resource-list">
                      ${resources.video_content.map(r => `<li>${r.resource_title}</li>`).join('')}
                  </ul>
              </div>
              <div class="monthly-resource-category">
                  <div class="monthly-resource-category-title">📝 Practice Materials</div>
                  <ul class="monthly-resource-list">
                      ${resources.practice_resources.map(r => `<li>${r.resource_title}</li>`).join('')}
                  </ul>
              </div>
              <div class="monthly-resource-category">
                  <div class="monthly-resource-category-title">📰 Current Affairs</div>
                  <ul class="monthly-resource-list">
                      ${resources.current_affairs_sources.map(r => `<li>${r.resource_title}</li>`).join('')}
                  </ul>
              </div>
          </div>
      </div>
    `;
  }

  html += `
        </div>
    </div>
  `;

  return html;
}

enum MONTH_DETAIL_VIEW {
  DAILY,
  WEEKLY
}
type MonthViewOptions = {
  monthDetails: MONTH_DETAIL_VIEW;
}
const defaultMonthViewOptions: MonthViewOptions = {
  monthDetails: MONTH_DETAIL_VIEW.WEEKLY
}

export async function generateMonthViewWithDailyPages(studyPlan: StudyPlan, options: MonthViewOptions = defaultMonthViewOptions): Promise<string> {
  const cycles = studyPlan.cycles || [];
  let html = '';

  const minDate = dayjs(studyPlan.start_date);
  const maxDate = dayjs(`${studyPlan.targeted_year}-08-31`);
  const endDate = maxDate.endOf('month');

  // Configurable limit - set to null for all months, or a number to limit
  const maxMonths = process.env.PDF_MAX_MONTHS ? parseInt(process.env.PDF_MAX_MONTHS) : null;
  let monthCount = 0;

  for (
    let currentDate = minDate.startOf('month');
    currentDate.isSameOrBefore(endDate, 'month') && (maxMonths === null || monthCount < maxMonths);
    currentDate = currentDate.add(1, 'month')
  ) {
    const monthDate = currentDate;
    const monthName = monthDate.format('MMMM');
    const monthYear = monthDate.format('YYYY');

    // console.log(`📅 Generating ${monthName} ${monthYear}...`);

    // Generate Month View
    html += `
    <div class="month-detail">
        <div class="month-detail-header">
            <div class="month-detail-title">${monthName.toUpperCase()}</div>
            <div class="month-detail-year">${monthYear}</div>
        </div>
        <div class="month-detail-grid">
            <div class="month-day-header">Sunday</div>
            <div class="month-day-header">Monday</div>
            <div class="month-day-header">Tuesday</div>
            <div class="month-day-header">Wednesday</div>
            <div class="month-day-header">Thursday</div>
            <div class="month-day-header">Friday</div>
            <div class="month-day-header">Saturday</div>
    `;

    const daysInMonth = monthDate.daysInMonth();
    const firstDayOfMonth = monthDate.startOf('month').day();

    for (let i = 0; i < firstDayOfMonth; i++) {
      html += '<div class="month-day-cell"></div>';
    }

    for (let day = 1; day <= daysInMonth; day++) {
      const currentDay = monthDate.date(day);

      // Determine which cycle this day belongs to for background color
      let dayCycleClass = '';
      for (const cycle of cycles) {
        const cycleStart = dayjs(cycle.cycleStartDate);
        const cycleEnd = dayjs(cycle.cycleEndDate);
        if (currentDay.isBetween(cycleStart, cycleEnd, 'day', '[]')) {
          dayCycleClass = `cycle-${cycle.cycleType.toLowerCase()}`;
          break;
        }
      }

      html += `
        <div class="month-day-cell ${dayCycleClass}">
            <div class="month-day-number">${day}</div>
        `;

      for (const cycle of cycles) {
        for (const block of cycle.cycleBlocks) {
          const blockStart = dayjs(block.block_start_date);
          const blockEnd = dayjs(block.block_end_date);

          if (currentDay.isBetween(blockStart, blockEnd, 'day', '[]')) {
            for (const subject of block.subjects) {
              const subjectName = getSubjectName(subject).toLowerCase();
              html += `<div class="subject-block ${subjectName}">${getSubjectName(subject)}</div>`;
            }
          }
        }
      }

      html += '</div>';
    }

    html += `
        </div>
    </div>
    ${await generateMonthlyResources(studyPlan, monthDate)}
    `;

    switch (options.monthDetails) {
      case MONTH_DETAIL_VIEW.WEEKLY: {
        // Generate Weekly Pages for this month
        html += `
        <div class="weekly-views-section">
      `;

        // Generate weekly pages for the month
        const weeks = getWeeksInMonth(monthDate, minDate, endDate);
        for (const week of weeks) {
          html += generateWeeklyView(week, cycles);
        }

        html += `</div>`;
      }
      break;
      default:
      case MONTH_DETAIL_VIEW.DAILY: {

        // Generate Daily Pages for this month immediately after month view
        html += `
        <div class="daily-views-section">
      `;

        // Generate daily pages for first 7 days of the month (sample week)
        const maxDays = 21;
        let dayCount = 0;

        for (let day = 1; day <= daysInMonth && dayCount < maxDays; day++) {
          const currentDay = monthDate.date(day);

          // Skip if day is before start date or after end date
          if (currentDay.isBefore(minDate) || currentDay.isAfter(endDate)) {
            continue;
          }

          html += generateDailyView(currentDay, cycles);
          dayCount++;
        }

        html += `</div>`;
      }
    }
    monthCount++;
  }

  return html;
}


function generateDailyView(day: dayjs.Dayjs, cycles: any[]): string {
  const dayName = day.format('dddd');
  const dayNumber = day.format('DD');
  const monthName = day.format('MMMM');
  const year = day.format('YYYY');

  // Determine which cycle this day belongs to
  let dayCycle = null;
  let dayCycleClass = '';
  for (const cycle of cycles) {
    const cycleStart = dayjs(cycle.cycleStartDate);
    const cycleEnd = dayjs(cycle.cycleEndDate);
    if (day.isBetween(cycleStart, cycleEnd, 'day', '[]')) {
      dayCycle = cycle;
      dayCycleClass = `cycle-${cycle.cycleType.toLowerCase()}`;
      break;
    }
  }

  // Get tasks for this day
  const dailyTasks = getDailyTasks(day, cycles);

  return `
    <div class="daily-page">
        <div class="daily-header ${dayCycleClass}">
            <div class="daily-date">
                <div class="daily-day-name">${dayName}</div>
                <div class="daily-day-number">${dayNumber}</div>
                <div class="daily-month-year">${monthName} ${year}</div>
            </div>
            <div class="daily-cycle-info">
                ${dayCycle ? `<div class="cycle-badge">${dayCycle.cycleName}</div>` : ''}
            </div>
        </div>
        
        <div class="daily-content">
            <div class="daily-tasks-section">
                <div class="daily-tasks-title">
                    <i class="fas fa-tasks"></i>
                    Today's Study Tasks
                </div>
                <div class="daily-tasks-list">
                    ${dailyTasks.length > 0 ? dailyTasks.map(task => `
                        <div class="daily-task-item ${task.type}">
                            <div class="task-type-badge">${task.typeIcon}</div>
                            <div class="task-content">
                                <div class="task-subject">${task.subject}</div>
                                <div class="task-description">${task.description}</div>
                                <div class="task-time">${task.timeSlot}</div>
                            </div>
                            <div class="task-checkbox">
                                <div class="checkbox">☐</div>
                            </div>
                        </div>
                    `).join('') : `
                        <div class="no-tasks">
                            <i class="fas fa-calendar-check"></i>
                            <div>No scheduled tasks for this day</div>
                        </div>
                    `}
                </div>
            </div>
            
            <div class="daily-notes-section">
                <div class="daily-notes-title">
                    <i class="fas fa-sticky-note"></i>
                    Daily Notes & Reflections
                </div>
                <div class="notes-area">
                    <div class="notes-line"></div>
                    <div class="notes-line"></div>
                    <div class="notes-line"></div>
                    <div class="notes-line"></div>
                    <div class="notes-line"></div>
                    <div class="notes-line"></div>
                    <div class="notes-line"></div>
                    <div class="notes-line"></div>
                </div>
            </div>
            
            <div class="daily-progress-section">
                <div class="daily-progress-title">
                    <i class="fas fa-chart-line"></i>
                    Daily Progress
                </div>
                <div class="progress-items">
                    <div class="progress-item">
                        <span class="progress-label">Study Hours:</span>
                        <div class="progress-bar">
                            <div class="progress-fill" style="width: 0%"></div>
                        </div>
                        <span class="progress-value">0/8 hrs</span>
                    </div>
                    <div class="progress-item">
                        <span class="progress-label">Tasks Completed:</span>
                        <div class="progress-bar">
                            <div class="progress-fill" style="width: 0%"></div>
                        </div>
                        <span class="progress-value">0/0</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
  `;
}

function getWeeksInMonth(monthDate: dayjs.Dayjs, minDate: dayjs.Dayjs, endDate: dayjs.Dayjs): (dayjs.Dayjs | null)[][] {
  const weeks: (dayjs.Dayjs | null)[][] = [];
  const startOfMonth = monthDate.startOf('month');
  const endOfMonth = monthDate.endOf('month');
  
  // Start from the Monday of the week containing the first day of the month
  let currentWeekStart = startOfMonth.startOf('week');
  
  while (currentWeekStart.isBefore(endOfMonth) || currentWeekStart.isSame(endOfMonth, 'week')) {
    const week: (dayjs.Dayjs | null)[] = [];
    
    // Generate 7 days for the week
    for (let i = 0; i < 7; i++) {
      const day = currentWeekStart.add(i, 'day');
      
      // Only include days within the study plan date range
      if (day.isBetween(minDate, endDate, 'day', '[]')) {
        week.push(day);
      } else {
        week.push(null); // Placeholder for days outside range
      }
    }
    
    // Only add week if it has at least one valid day
    if (week.some(day => day !== null)) {
      weeks.push(week);
    }
    
    currentWeekStart = currentWeekStart.add(1, 'week');
  }
  
  return weeks;
}

function generateWeeklyView(week: (dayjs.Dayjs | null)[], cycles: any[]): string {
  const weekStart = week.find(day => day !== null);
  const weekEnd = week.filter(day => day !== null).pop();
  
  if (!weekStart || !weekEnd) return '';
  
  const weekRange = `${weekStart.format('MMM DD')} - ${weekEnd.format('MMM DD, YYYY')}`;
  
  // Get the cycle for the week (use the first day's cycle)
  let weekCycle = null;
  let weekCycleClass = '';
  for (const cycle of cycles) {
    const cycleStart = dayjs(cycle.cycleStartDate);
    const cycleEnd = dayjs(cycle.cycleEndDate);
    if (weekStart.isBetween(cycleStart, cycleEnd, 'day', '[]')) {
      weekCycle = cycle;
      weekCycleClass = `cycle-${cycle.cycleType.toLowerCase()}`;
      break;
    }
  }

  return `
    <div class="weekly-page">
        <div class="weekly-header ${weekCycleClass}">
            <div class="weekly-title">
                <div class="weekly-range">${weekRange}</div>
                <div class="weekly-subtitle">Weekly Study Plan</div>
            </div>
            <div class="weekly-cycle-info">
                ${weekCycle ? `<div class="cycle-badge">${weekCycle.cycleName}</div>` : ''}
            </div>
        </div>
        
        <div class="weekly-content">
            <div class="weekly-grid">
                ${week.map((day, index) => {
                  if (day === null) {
                    return `
                      <div class="weekly-day-column empty-day">
                        <div class="day-header">
                          <div class="day-name">${['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][index]}</div>
                          <div class="day-number">-</div>
                        </div>
                        <div class="day-tasks">
                          <div class="no-tasks">Outside study period</div>
                        </div>
                      </div>
                    `;
                  }
                  
                  const dayName = day.format('ddd');
                  const dayNumber = day.format('DD');
                  const dayTasks = getDailyTasks(day, cycles);
                  
                  // Determine cycle for this specific day
                  let dayCycleClass = '';
                  for (const cycle of cycles) {
                    const cycleStart = dayjs(cycle.cycleStartDate);
                    const cycleEnd = dayjs(cycle.cycleEndDate);
                    if (day.isBetween(cycleStart, cycleEnd, 'day', '[]')) {
                      dayCycleClass = `cycle-${cycle.cycleType.toLowerCase()}`;
                      break;
                    }
                  }
                  
                  return `
                    <div class="weekly-day-column ${dayCycleClass}">
                        <div class="day-header">
                            <div class="day-name">${dayName}</div>
                            <div class="day-number">${dayNumber}</div>
                        </div>
                        <div class="day-tasks">
                            ${dayTasks.length > 0 ? dayTasks.map(task => `
                                <div class="weekly-task-item ${task.type}">
                                    <div class="task-type-badge">${task.typeIcon}</div>
                                    <div class="task-content">
                                        <div class="task-subject">${task.subject}</div>
                                        <div class="task-description">${task.description}</div>
                                        <div class="task-time">${task.timeSlot}</div>
                                    </div>
                                    <div class="task-checkbox">
                                        <div class="checkbox">☐</div>
                                    </div>
                                </div>
                            `).join('') : `
                                <div class="no-tasks">
                                    <i class="fas fa-calendar-check"></i>
                                    <div>No tasks</div>
                                </div>
                            `}
                        </div>
                    </div>
                  `;
                }).join('')}
            </div>
            
            <div class="weekly-notes-section">
                <div class="weekly-notes-title">
                    <i class="fas fa-sticky-note"></i>
                    Weekly Notes & Reflections
                </div>
                <div class="weekly-notes-grid">
                    <div class="notes-column">
                        <div class="notes-label">Monday - Wednesday</div>
                        <div class="notes-area">
                            <div class="notes-line"></div>
                            <div class="notes-line"></div>
                            <div class="notes-line"></div>
                            <div class="notes-line"></div>
                        </div>
                    </div>
                    <div class="notes-column">
                        <div class="notes-label">Thursday - Sunday</div>
                        <div class="notes-area">
                            <div class="notes-line"></div>
                            <div class="notes-line"></div>
                            <div class="notes-line"></div>
                            <div class="notes-line"></div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="weekly-progress-section">
                <div class="weekly-progress-title">
                    <i class="fas fa-chart-line"></i>
                    Weekly Progress Summary
                </div>
                <div class="progress-grid">
                    <div class="progress-item">
                        <span class="progress-label">Study Hours:</span>
                        <div class="progress-bar">
                            <div class="progress-fill" style="width: 0%"></div>
                        </div>
                        <span class="progress-value">0/40 hrs</span>
                    </div>
                    <div class="progress-item">
                        <span class="progress-label">Tasks Completed:</span>
                        <div class="progress-bar">
                            <div class="progress-fill" style="width: 0%"></div>
                        </div>
                        <span class="progress-value">0/0</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
  `;
}

function getDailyTasks(day: dayjs.Dayjs, cycles: any[]): any[] {
  const tasks = [];

  for (const cycle of cycles) {
    for (const block of cycle.cycleBlocks) {
      const blockStart = dayjs(block.block_start_date);
      const blockEnd = dayjs(block.block_end_date);

      if (day.isBetween(blockStart, blockEnd, 'day', '[]')) {
        for (const subject of block.subjects) {
          const subjectName = getSubjectName(subject);
          const taskType = determineTaskType(block.block_title, subjectName);

          tasks.push({
            subject: subjectName,
            description: `${block.block_title}`,
            type: taskType.type,
            typeIcon: taskType.icon,
            timeSlot: getTimeSlotForSubject(subjectName)
          });
        }
      }
    }
  }

  return tasks;
}

function determineTaskType(blockTitle: string, subjectName: string): { type: string, icon: string } {
  const title = blockTitle.toLowerCase();
  const subject = subjectName.toLowerCase();

  if (title.includes('revision') || title.includes('review')) {
    return { type: 'revision', icon: '🔄' };
  } else if (title.includes('practice') || title.includes('test') || title.includes('mock')) {
    return { type: 'practice', icon: '📝' };
  } else if (title.includes('current affairs') || subject.includes('current affairs')) {
    return { type: 'current-affairs', icon: '📰' };
  } else if (title.includes('optional') || subject.includes('optional')) {
    return { type: 'optional', icon: '📖' };
  } else {
    return { type: 'study', icon: '📚' };
  }
}

function getTimeSlotForSubject(subjectName: string): string {
  const subject = subjectName.toLowerCase();

  if (subject.includes('current affairs')) {
    return 'Morning (6:00-7:00 AM)';
  } else if (subject.includes('history')) {
    return 'Morning (9:00-11:00 AM)';
  } else if (subject.includes('geography')) {
    return 'Afternoon (2:00-4:00 PM)';
  } else if (subject.includes('polity')) {
    return 'Evening (5:00-7:00 PM)';
  } else if (subject.includes('economics')) {
    return 'Evening (7:00-9:00 PM)';
  } else if (subject.includes('optional')) {
    return 'Night (9:00-11:00 PM)';
  } else {
    return 'Flexible';
  }
}
