"""user refer id added in users

Revision ID: 3fc510a36cd7
Revises: 68d84cc8d6fb
Create Date: 2023-11-29 14:01:45.856814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc510a36cd7'
down_revision = '68d84cc8d6fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referred_by_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referred_by_id')
    # ### end Alembic commands ###
