"""

Revision ID: 6650a231b32c
Revises: ab558c9d92ef
Create Date: 2023-08-12 04:38:09.995500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6650a231b32c'
down_revision = 'ab558c9d92ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
