"""tenant module model upgrades

Revision ID: ab9f8f4f863b
Revises: 4ab34db9e261
Create Date: 2023-08-21 13:07:30.999667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ab9f8f4f863b"
down_revision = "4ab34db9e261"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("testshares")
    op.drop_column("questions", "source")
    op.drop_column("questions", "question")
    op.drop_column("questions", "question_type")
    op.drop_column("questions", "is_deleted")
    op.drop_column("questions", "topics")
    op.drop_column("questions", "publishing_status")
    op.drop_column("questions", "tenant")
    op.drop_column("questions", "question_form")
    op.drop_column("questions", "is_multi")
    op.drop_column("questions", "reference_material")
    op.drop_column("questions", "model_solution")
    op.drop_column("questions", "options")
    op.drop_column("questions", "explanation")
    op.drop_column("questions", "exams")
    op.drop_column("questions", "difficulty_level")
    op.drop_column("questions", "is_private")
    op.drop_column("questions", "papers")
    op.drop_column("questions", "cms_id")
    op.drop_column("questions", "subjects")
    op.add_column("tenants", sa.Column("domain", sa.String(), nullable=False))
    op.add_column("tenants", sa.Column("tag_line", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("company_name", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("company_info", sa.JSON(), nullable=True))
    op.drop_constraint("tenants_domain_name_key", "tenants", type_="unique")
    op.create_unique_constraint(op.f("tenants_domain_key"), "tenants", ["domain"])
    op.drop_column("tenants", "domain_name")
    op.drop_constraint(
        "testquestionattempts_test_id_fkey", "testquestionattempts", type_="foreignkey"
    )
    op.add_column(
        "testquestions", sa.Column("questions", sa.ARRAY(sa.JSON()), nullable=True)
    )
    op.drop_constraint(
        "testquestions_test_id_fkey", "testquestions", type_="foreignkey"
    )
    op.drop_constraint(
        "testquestions_question_id_fkey", "testquestions", type_="foreignkey"
    )
    op.drop_column("testquestions", "test_id")
    op.drop_column("testquestions", "correct_attempts_percent")
    op.drop_column("testquestions", "question_id")
    op.drop_index("tests_title_idx", table_name="tests")
    op.drop_constraint("tests_tenant_id_fkey", "tests", type_="foreignkey")
    op.drop_constraint("tests_created_by_id_fkey", "tests", type_="foreignkey")
    op.drop_column("tests", "max_score")
    op.drop_column("tests", "include_attempted")
    op.drop_column("tests", "topics")
    op.drop_column("tests", "test_size")
    op.drop_column("tests", "created_by_id")
    op.drop_column("tests", "max_duration")
    op.drop_column("tests", "exam")
    op.drop_column("tests", "is_active")
    op.drop_column("tests", "avg_score")
    op.drop_column("tests", "paper")
    op.drop_column("tests", "attempts_count")
    op.drop_column("tests", "is_recommended")
    op.drop_column("tests", "tenant_id")
    op.drop_column("tests", "stage")
    op.drop_column("tests", "difficulty_level")
    op.drop_column("tests", "title")
    op.drop_column("tests", "test_questions_count")
    op.drop_column("tests", "include_prev_year")
    op.drop_column("tests", "subjects")
    op.drop_column("tests", "max_marks")
    op.add_column("users", sa.Column("tenant_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("users_tenant_id_fkey"), "users", "tenants", ["tenant_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_tenant_id_fkey"), "users", type_="foreignkey")
    op.drop_column("users", "tenant_id")
    op.add_column(
        "tests",
        sa.Column("max_marks", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tests",
        sa.Column(
            "subjects",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tests",
        sa.Column(
            "include_prev_year", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "tests",
        sa.Column(
            "test_questions_count", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "tests", sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "tests",
        sa.Column("difficulty_level", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tests", sa.Column("stage", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "tests",
        sa.Column("tenant_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tests",
        sa.Column("is_recommended", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tests",
        sa.Column("attempts_count", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tests", sa.Column("paper", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "tests",
        sa.Column(
            "avg_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tests",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tests", sa.Column("exam", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "tests",
        sa.Column(
            "max_duration",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tests",
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tests",
        sa.Column("test_size", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tests",
        sa.Column(
            "topics", postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "tests",
        sa.Column(
            "include_attempted", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "tests",
        sa.Column(
            "max_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "tests_created_by_id_fkey", "tests", "users", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "tests_tenant_id_fkey", "tests", "tenants", ["tenant_id"], ["id"]
    )
    op.create_index("tests_title_idx", "tests", ["title"], unique=False)
    op.add_column(
        "testquestions",
        sa.Column("question_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "testquestions",
        sa.Column(
            "correct_attempts_percent",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "testquestions",
        sa.Column("test_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "testquestions_question_id_fkey",
        "testquestions",
        "questions",
        ["question_id"],
        ["id"],
    )
    op.create_foreign_key(
        "testquestions_test_id_fkey", "testquestions", "tests", ["test_id"], ["id"]
    )
    op.drop_column("testquestions", "questions")
    op.create_foreign_key(
        "testquestionattempts_test_id_fkey",
        "testquestionattempts",
        "tests",
        ["test_id"],
        ["id"],
    )
    op.add_column(
        "tenants",
        sa.Column("domain_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(op.f("tenants_domain_key"), "tenants", type_="unique")
    op.create_unique_constraint("tenants_domain_name_key", "tenants", ["domain_name"])
    op.drop_column("tenants", "company_info")
    op.drop_column("tenants", "company_name")
    op.drop_column("tenants", "tag_line")
    op.drop_column("tenants", "domain")
    op.add_column(
        "questions",
        sa.Column(
            "subjects",
            postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "questions",
        sa.Column("cms_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column(
            "papers",
            postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "questions",
        sa.Column("is_private", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column("difficulty_level", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column(
            "exams",
            postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "questions",
        sa.Column("explanation", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column(
            "options",
            postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "questions",
        sa.Column("model_solution", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column("reference_material", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column("is_multi", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column("question_form", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column("tenant", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column(
            "publishing_status", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "questions",
        sa.Column(
            "topics",
            postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "questions",
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column("question_type", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column("question", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column(
            "source",
            postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "testshares",
        sa.Column("test_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("shared_with_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("shared_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["shared_by_id"], ["users.id"], name="testshares_shared_by_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["shared_with_id"], ["users.id"], name="testshares_shared_with_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["test_id"], ["tests.id"], name="testshares_test_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="testshares_pkey"),
    )
    # ### end Alembic commands ###
