"""update test attempts model

Revision ID: cbfaa58d66ea
Revises: 73d3edcdd19a
Create Date: 2023-08-23 19:20:39.549989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbfaa58d66ea'
down_revision = '73d3edcdd19a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testattempts', sa.Column('test_attempt_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testattempts', 'test_attempt_mode')
    # ### end Alembic commands ###
