"""user model upgrade

Revision ID: 6ae207e20cdc
Revises: 5baef3be3152
Create Date: 2023-07-27 11:58:40.521993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae207e20cdc'
down_revision = '5baef3be3152'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription')
    # ### end Alembic commands ###
