"""added question report table

Revision ID: 6fde1e341787
Revises: 4a8cbde45bb2
Create Date: 2023-08-22 22:25:06.994606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6fde1e341787'
down_revision = '4a8cbde45bb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionreports',
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('questionreports_question_id_fkey')),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], name=op.f('questionreports_reported_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('questionreports_pkey'))
    )
    op.add_column('testquestionattempts', sa.Column('single_answer', sa.Text(), nullable=True))
    op.add_column('testquestionattempts', sa.Column('multi_answers', sa.ARRAY(sa.String()), nullable=True))
    op.drop_constraint('testquestionattempts_question_id_fkey', 'testquestionattempts', type_='foreignkey')
    op.create_foreign_key(op.f('testquestionattempts_question_id_fkey'), 'testquestionattempts', 'questions', ['question_id'], ['id'])
    op.drop_column('testquestionattempts', 'answer')
    op.drop_column('testquestionattempts', 'report')
    op.alter_column('testquestions', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('testquestions', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('testquestions', 'id')
    op.drop_column('testquestions', 'updated_at')
    op.drop_column('testquestions', 'created_at')
    op.add_column('tests', sa.Column('questions_count', sa.Integer(), nullable=True))
    op.drop_column('tests', 'test_questions_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('test_questions_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tests', 'questions_count')
    op.add_column('testquestions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('testquestions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('testquestions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('testquestions', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('testquestions', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('testquestionattempts', sa.Column('report', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.add_column('testquestionattempts', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('testquestionattempts_question_id_fkey'), 'testquestionattempts', type_='foreignkey')
    op.create_foreign_key('testquestionattempts_question_id_fkey', 'testquestionattempts', 'testquestions', ['question_id'], ['id'])
    op.drop_column('testquestionattempts', 'multi_answers')
    op.drop_column('testquestionattempts', 'single_answer')
    op.drop_table('questionreports')
    # ### end Alembic commands ###
