"""Type of tenant changed in question model

Revision ID: 4a8cbde45bb2
Revises: 510f75d18d32
Create Date: 2023-08-22 09:39:10.051787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8cbde45bb2'
down_revision = '510f75d18d32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.drop_column('questions', 'tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('tenant', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('questions', 'tenant_id')
    # ### end Alembic commands ###
