"""subs user_id addition

Revision ID: b82cf875628a
Revises: 3faf692aa783
Create Date: 2023-10-30 14:41:00.784869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b82cf875628a"
down_revision = "3faf692aa783"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("discountcodes_coupon_code_idx", table_name="discountcodes")
    op.create_index(
        op.f("discountcodes_coupon_code_idx"),
        "discountcodes",
        ["coupon_code"],
        unique=False,
    )
    op.add_column("subscriptions", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("subscriptions_user_id_fkey"),
        "subscriptions",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("subscriptions_user_id_fkey"), "subscriptions", type_="foreignkey"
    )
    op.drop_column("subscriptions", "user_id")
    op.drop_index(op.f("discountcodes_coupon_code_idx"), table_name="discountcodes")
    op.create_index(
        "discountcodes_coupon_code_idx", "discountcodes", ["coupon_code"], unique=False
    )
    # ### end Alembic commands ###
