"""question model changes

Revision ID: 1ddb5eff6a01
Revises: dff51c26254a
Create Date: 2023-09-13 14:03:04.590986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ddb5eff6a01'
down_revision = 'dff51c26254a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('max_marks', sa.Float(), nullable=True))
    op.add_column('questions', sa.Column('negative_marks', sa.Float(), nullable=True))
    op.add_column('questions', sa.Column('context', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('q_num', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('exam', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('paper', sa.JSON(), nullable=True))
    op.create_unique_constraint(op.f('questions_cms_id_key'), 'questions', ['cms_id', 'q_num', 'question_type'])
    op.drop_column('questions', 'papers')
    op.drop_column('questions', 'exams')
    op.add_column('testquestions', sa.Column('max_marks', sa.Float(), nullable=True))
    op.add_column('testquestions', sa.Column('negative_marks', sa.Float(), nullable=True))
    op.add_column('testquestions', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('tests', sa.Column('source', sa.ARRAY(sa.JSON()), nullable=True))
    op.drop_column('tests', 'include_prev_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('include_prev_year', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tests', 'source')
    op.drop_column('testquestions', 'duration')
    op.drop_column('testquestions', 'negative_marks')
    op.drop_column('testquestions', 'max_marks')
    op.add_column('questions', sa.Column('exams', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('papers', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('questions_cms_id_key'), 'questions', type_='unique')
    op.drop_column('questions', 'paper')
    op.drop_column('questions', 'exam')
    op.drop_column('questions', 'q_num')
    op.drop_column('questions', 'context')
    op.drop_column('questions', 'negative_marks')
    op.drop_column('questions', 'max_marks')
    # ### end Alembic commands ###
