"""added testqattempt and test attempt models

Revision ID: 3d744741cb02
Revises: 7111f4fbed7b
Create Date: 2023-09-15 13:11:44.649911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d744741cb02"
down_revision = "7111f4fbed7b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("testattempts")
    op.create_table(
        "testattempts",
        sa.Column("test_id", sa.Integer(), nullable=True),
        sa.Column("attempted_by_id", sa.Integer(), nullable=True),
        sa.Column("test_attempt_mode", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("macro_comment", sa.JSON(), nullable=True),
        sa.Column("answer_upload", sa.String(), nullable=True),
        sa.Column("time_elapsed", sa.Float(), nullable=True),
        sa.Column("correct", sa.Integer(), nullable=True),
        sa.Column("incorrect", sa.Integer(), nullable=True),
        sa.Column("unattempted", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempted_by_id"],
            ["users.id"],
            name=op.f("testattempts_attempted_by_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["test_id"], ["tests.id"], name=op.f("testattempts_test_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("testattempts_pkey")),
    )
    op.create_table(
        "testquestionattempts",
        sa.Column("test_attempt_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("test_id", sa.Integer(), nullable=True),
        sa.Column("attempted_by_id", sa.Integer(), nullable=True),
        sa.Column("micro_comment", sa.String(), nullable=True),
        sa.Column("time_elapsed", sa.Float(), nullable=True),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("selected_options", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("is_correct_attempt", sa.Boolean(), nullable=True),
        sa.Column("marks_obtained", sa.Float(), nullable=True),
        sa.Column("is_starred", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempted_by_id"],
            ["users.id"],
            name=op.f("testquestionattempts_attempted_by_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("testquestionattempts_question_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["test_attempt_id"],
            ["testattempts.id"],
            name=op.f("testquestionattempts_test_attempt_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["test_id"], ["tests.id"], name=op.f("testquestionattempts_test_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "test_attempt_id", "question_id", name=op.f("testquestionattempts_pkey")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("testquestionattempts")
    op.drop_table("testattempts")
    # ### end Alembic commands ###
