"""phonenumber type upgrade

Revision ID: 90913d52894d
Revises: fb0c4e561b6b
Create Date: 2023-07-27 11:22:10.839640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90913d52894d'
down_revision = 'fb0c4e561b6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
