"""

Revision ID: 5a263e8d82a2
Revises: 8880b34fb3a9
Create Date: 2023-08-02 10:34:23.736872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a263e8d82a2'
down_revision = '8880b34fb3a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
