"""pg related model changes and integers for amounts

Revision ID: 2cca6320d0a3
Revises: 1a8265d132c1
Create Date: 2023-10-18 13:34:03.839682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2cca6320d0a3"
down_revision = "1a8265d132c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "discountcodes",
        "discount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "plans",
        "rate",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.add_column(
        "subscriptions", sa.Column("discount_amount", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "subscriptions",
        "adjustment_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "subscriptions",
        "subscription_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "subscriptions",
        "start_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.drop_column("subscriptions", "auth_req_id")
    op.add_column(
        "subscriptions",
        sa.Column(
            "auth_req_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=True,
        ),
    )
    op.alter_column(
        "tests",
        "max_marks",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.add_column(
        "transactions",
        sa.Column(
            "tx_uuid",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=True,
        ),
    )
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.drop_column("transactions", "tx_uuid")
    op.alter_column(
        "tests",
        "max_marks",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "subscriptions",
        "auth_req_id",
        existing_type=sa.UUID(),
        server_default=None,
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "subscriptions",
        "start_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "subscription_amount",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "subscriptions",
        "adjustment_amount",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.drop_column("subscriptions", "discount_amount")
    op.alter_column(
        "plans",
        "rate",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "discountcodes",
        "discount",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
