"""user quota model and changes

Revision ID: 8a7a64546c2f
Revises: a05254b48ad6
Create Date: 2023-10-06 01:32:16.666074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7a64546c2f'
down_revision = 'a05254b48ad6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userquotas',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('quota_name', sa.String(), nullable=True),
    sa.Column('feature_name', sa.String(), nullable=True),
    sa.Column('plan_name', sa.String(), nullable=True),
    sa.Column('quota_consumed', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('userquotas_plan_id_fkey')),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('userquotas_subscription_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('userquotas_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('userquotas_pkey'))
    )
    op.create_index(op.f('userquotas_feature_name_idx'), 'userquotas', ['feature_name'], unique=False)
    op.create_index(op.f('userquotas_plan_name_idx'), 'userquotas', ['plan_name'], unique=False)
    op.create_index(op.f('userquotas_quota_name_idx'), 'userquotas', ['quota_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('userquotas_quota_name_idx'), table_name='userquotas')
    op.drop_index(op.f('userquotas_plan_name_idx'), table_name='userquotas')
    op.drop_index(op.f('userquotas_feature_name_idx'), table_name='userquotas')
    op.drop_table('userquotas')
    # ### end Alembic commands ###
