"""discount model updated

Revision ID: ddca33835a99
Revises: 4f6f73c03795
Create Date: 2023-08-12 12:45:16.690373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddca33835a99'
down_revision = '4f6f73c03795'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discountcodes', sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('discountcodes', sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discountcodes', 'valid_to')
    op.drop_column('discountcodes', 'valid_from')
    # ### end Alembic commands ###
