"""tenant relation

Revision ID: 180fee2c75eb
Revises: 1e63be659e52
Create Date: 2023-07-27 09:56:41.872718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180fee2c75eb'
down_revision = '1e63be659e52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tenant', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('users_tenant_fkey'), 'users', 'tenants', ['tenant'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_tenant_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'tenant')
    # ### end Alembic commands ###
