"""

Revision ID: 97be640704f8
Revises: e273be601a5c
Create Date: 2023-07-30 02:02:11.287205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97be640704f8'
down_revision = 'e273be601a5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('users', sa.Column('photo', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    op.drop_index('users_mobile_number_idx', table_name='users')
    op.create_index(op.f('users_phone_number_idx'), 'users', ['phone_number'], unique=True)
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'mobile_number')
    op.drop_column('users', 'is_phone_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_phone_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('mobile_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('users_phone_number_idx'), table_name='users')
    op.create_index('users_mobile_number_idx', 'users', ['mobile_number'], unique=False)
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'photo')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
