"""

Revision ID: fe75331e19e2
Revises: ddca33835a99
Create Date: 2023-08-18 18:36:51.427575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe75331e19e2'
down_revision = 'ddca33835a99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('tenant', sa.String(), nullable=True),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('options', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_multi', sa.Boolean(), nullable=True),
    sa.Column('question_form', sa.String(), nullable=True),
    sa.Column('model_solution', sa.Text(), nullable=True),
    sa.Column('cms_id', sa.Integer(), nullable=True),
    sa.Column('exams', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('papers', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('subjects', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('topics', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('source', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('reference_material', sa.Text(), nullable=True),
    sa.Column('publishing_status', sa.String(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('questions_pkey'))
    )
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_table('questions')
    # ### end Alembic commands ###
