"""auth models

Revision ID: 929dcea695fd
Revises: 7e0815bd3f38
Create Date: 2023-07-29 02:17:41.975880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "929dcea695fd"
down_revision = "7e0815bd3f38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "is_email_verified", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "users", "is_phone_verified", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "is_phone_verified", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "users", "is_email_verified", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###
