"""branch_id_in_Batch

Revision ID: ac9ac2b4c786
Revises: 64ab663aad0f
Create Date: 2024-10-03 16:10:00.104246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9ac2b4c786'
down_revision = '64ab663aad0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('batches_branch_id_fkey'), 'batches', 'branches', ['branch_id'], ['id'])
    op.drop_column('batches', 'branch')
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('batches', sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('batches_branch_id_fkey'), 'batches', type_='foreignkey')
    op.drop_column('batches', 'branch_id')
    # ### end Alembic commands ###
