"""question model subj,topic,currentaffairs

Revision ID: a1e0554300f7
Revises: f248b345f9e7
Create Date: 2024-01-23 10:01:44.162397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a1e0554300f7"
down_revision = "f248b345f9e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("subject", sa.JSON(), nullable=True))
    op.add_column("questions", sa.Column("topic", sa.JSON(), nullable=True))
    op.add_column(
        "questions", sa.Column("is_current_affairs", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "questions", sa.Column("current_affairs_topic", sa.JSON(), nullable=True)
    )
    op.drop_column("questions", "subjects")
    op.drop_column("questions", "topics")
    op.alter_column(
        "tests",
        "daily_test_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tests",
        "daily_test_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.add_column(
        "questions",
        sa.Column(
            "topics",
            postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "questions",
        sa.Column(
            "subjects",
            postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("questions", "current_affairs_topic")
    op.drop_column("questions", "is_current_affairs")
    op.drop_column("questions", "topic")
    op.drop_column("questions", "subject")
    # ### end Alembic commands ###
