"""select exam year in tests model

Revision ID: 56f129299894
Revises: ad5679265cb7
Create Date: 2024-03-18 23:46:19.984031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f129299894'
down_revision = 'ad5679265cb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('select_exam_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'select_exam_year')
    # ### end Alembic commands ###
