"""changes_in_user_model_and_branchuser_added

Revision ID: b3751cadd051
Revises: 341539c11e4b
Create Date: 2024-09-23 18:35:32.166016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3751cadd051'
down_revision = '341539c11e4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branchusers',
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('branchusers_branch_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('branchusers_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('branchusers_pkey'))
    )
    op.add_column('users', sa.Column('user_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tagline', sa.String(), nullable=True))
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'tagline')
    op.drop_column('users', 'user_type')
    op.drop_table('branchusers')
    # ### end Alembic commands ###
