"""adding_code_branch_to_products

Revision ID: 15a5e425e916
Revises: 7640d4e6fff2
Create Date: 2024-10-25 16:23:08.086512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a5e425e916'
down_revision = '7640d4e6fff2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('batches_branch_id_fkey', 'batches', type_='foreignkey')
    op.drop_column('batches', 'code')
    op.drop_column('batches', 'branch_id')
    op.drop_column('batches', 'name')
    op.add_column('products', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('name', sa.String(), nullable=True))
    op.add_column('products', sa.Column('code', sa.String(), nullable=True))
    op.create_foreign_key(op.f('products_branch_id_fkey'), 'products', 'branches', ['branch_id'], ['id'])
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('products_branch_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'code')
    op.drop_column('products', 'name')
    op.drop_column('products', 'branch_id')
    op.add_column('batches', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('batches', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('batches', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('batches_branch_id_fkey', 'batches', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###
