"""add_student_id_to_users

Revision ID: student_id_001
Revises: cycle_fields_001
Create Date: 2025-01-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'student_id_001'
down_revision = 'cycle_fields_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add student_id column to users table
    op.add_column('users', sa.Column('student_id', sa.String(length=8), nullable=True))
    
    # Create unique index for student_id
    op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=True)
    
    # Add is_faculty column to users table
    op.add_column('users', sa.Column('is_faculty', sa.Boolean(), nullable=True, default=False))
    
    # Create referrals table
    op.create_table('referrals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('referrer_student_id', sa.String(length=8), nullable=False),
        sa.Column('referred_student_id', sa.Integer(), nullable=True),
        sa.Column('referral_code', sa.String(length=8), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['referred_student_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for referrals table
    op.create_index(op.f('ix_referrals_referrer_student_id'), 'referrals', ['referrer_student_id'], unique=False)
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=False)
    
    # Extend studyplans table for approval workflow
    op.add_column('studyplans', sa.Column('student_id', sa.String(length=8), nullable=True))
    op.add_column('studyplans', sa.Column('approval_status', sa.String(length=20), nullable=True, default='draft'))
    op.add_column('studyplans', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('studyplans', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('studyplans', sa.Column('review_notes', sa.Text(), nullable=True))
    
    # Add foreign key constraint for approved_by
    op.create_foreign_key('fk_studyplans_approved_by', 'studyplans', 'users', ['approved_by'], ['id'])
    
    # Create indexes for studyplans
    op.create_index(op.f('ix_studyplans_student_id'), 'studyplans', ['student_id'], unique=False)
    op.create_index(op.f('ix_studyplans_approval_status'), 'studyplans', ['approval_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index(op.f('ix_studyplans_approval_status'), table_name='studyplans')
    op.drop_index(op.f('ix_studyplans_student_id'), table_name='studyplans')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referrer_student_id'), table_name='referrals')
    op.drop_index(op.f('ix_users_student_id'), table_name='users')
    
    # Drop foreign key constraints
    op.drop_constraint('fk_studyplans_approved_by', 'studyplans', type_='foreignkey')
    
    # Drop columns from studyplans
    op.drop_column('studyplans', 'review_notes')
    op.drop_column('studyplans', 'approved_at')
    op.drop_column('studyplans', 'approved_by')
    op.drop_column('studyplans', 'approval_status')
    op.drop_column('studyplans', 'student_id')
    
    # Drop referrals table
    op.drop_table('referrals')
    
    # Drop columns from users
    op.drop_column('users', 'is_faculty')
    op.drop_column('users', 'student_id')
    # ### end Alembic commands ###
