"""remove purchase id and installment id in txs

Revision ID: ca387e745744
Revises: 9d2851c0275f
Create Date: 2025-01-09 13:57:20.829922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca387e745744'
down_revision = '9d2851c0275f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_purchase_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_purchaseinstallment_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'purchaseinstallment_id')
    op.drop_column('transactions', 'purchase_id')
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('transactions', sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('purchaseinstallment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transactions_purchaseinstallment_id_fkey', 'transactions', 'purchaseinstallments', ['purchaseinstallment_id'], ['id'])
    op.create_foreign_key('transactions_purchase_id_fkey', 'transactions', 'purchases', ['purchase_id'], ['id'])
    # ### end Alembic commands ###
