"""add_cycle_fields_to_plantasks

Revision ID: cycle_fields_001
Revises: 11891231aca1
Create Date: 2025-09-16 14:47:56.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cycle_fields_001'
down_revision = '11891231aca1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add cycle fields to plantasks table
    op.add_column('plantasks', sa.Column('cycle_id', sa.String(length=255), nullable=True))
    op.add_column('plantasks', sa.Column('cycle_type', sa.String(length=100), nullable=True))
    op.add_column('plantasks', sa.Column('cycle_order', sa.Integer(), nullable=True))
    op.add_column('plantasks', sa.Column('cycle_name', sa.String(length=255), nullable=True))
    
    # Create indexes for better query performance
    op.create_index(op.f('ix_plantasks_cycle_id'), 'plantasks', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_plantasks_cycle_order'), 'plantasks', ['cycle_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index(op.f('ix_plantasks_cycle_order'), table_name='plantasks')
    op.drop_index(op.f('ix_plantasks_cycle_id'), table_name='plantasks')
    
    # Remove cycle fields from plantasks table
    op.drop_column('plantasks', 'cycle_name')
    op.drop_column('plantasks', 'cycle_order')
    op.drop_column('plantasks', 'cycle_type')
    op.drop_column('plantasks', 'cycle_id')
    # ### end Alembic commands ###
