"""testevaluation model added

Revision ID: bfacb01d9c7e
Revises: f634e16ee18c
Create Date: 2025-02-28 19:19:03.587620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfacb01d9c7e'
down_revision = 'f634e16ee18c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testevaluations',
    sa.Column('test_attempt_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('is_reevaluation', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], name=op.f('testevaluations_evaluator_id_fkey')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('testevaluations_reviewer_id_fkey')),
    sa.ForeignKeyConstraint(['test_attempt_id'], ['testattempts.id'], name=op.f('testevaluations_test_attempt_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('testevaluations_pkey'))
    )
    op.alter_column('plantasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantaskusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplans', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplanusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('testattempts', sa.Column('re_evaluation_request_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('testattempts', sa.Column('test_evaluation_status', sa.String(), nullable=True))
    op.drop_constraint('testattempts_test_re_reviewer_fkey', 'testattempts', type_='foreignkey')
    op.drop_constraint('testattempts_test_reviewer_fkey', 'testattempts', type_='foreignkey')
    op.drop_constraint('testattempts_test_evaluator_fkey', 'testattempts', type_='foreignkey')
    op.drop_constraint('testattempts_test_re_evaluator_fkey', 'testattempts', type_='foreignkey')
    op.drop_column('testattempts', 're_evaluated_date')
    op.drop_column('testattempts', 'assigned_date')
    op.drop_column('testattempts', 'rejected_date')
    op.drop_column('testattempts', 'evaluated_date')
    op.drop_column('testattempts', 'test_re_reviewer')
    op.drop_column('testattempts', 'test_assessment_status')
    op.drop_column('testattempts', 'test_re_evaluator')
    op.drop_column('testattempts', 'withdrawn_date')
    op.drop_column('testattempts', 'accepted_date')
    op.drop_column('testattempts', 'test_evaluator')
    op.drop_column('testattempts', 'test_reviewer')
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('testattempts', sa.Column('test_reviewer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('testattempts', sa.Column('test_evaluator', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('testattempts', sa.Column('accepted_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('testattempts', sa.Column('withdrawn_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('testattempts', sa.Column('test_re_evaluator', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('testattempts', sa.Column('test_assessment_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('testattempts', sa.Column('test_re_reviewer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('testattempts', sa.Column('evaluated_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('testattempts', sa.Column('rejected_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('testattempts', sa.Column('assigned_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('testattempts', sa.Column('re_evaluated_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key('testattempts_test_re_evaluator_fkey', 'testattempts', 'users', ['test_re_evaluator'], ['id'])
    op.create_foreign_key('testattempts_test_evaluator_fkey', 'testattempts', 'users', ['test_evaluator'], ['id'])
    op.create_foreign_key('testattempts_test_reviewer_fkey', 'testattempts', 'users', ['test_reviewer'], ['id'])
    op.create_foreign_key('testattempts_test_re_reviewer_fkey', 'testattempts', 'users', ['test_re_reviewer'], ['id'])
    op.drop_column('testattempts', 'test_evaluation_status')
    op.drop_column('testattempts', 're_evaluation_request_date')
    op.alter_column('studyplanusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplans', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantaskusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('testevaluations')
    # ### end Alembic commands ###
