colleges_and_universities_list = {
    "universities":
        [
            "University of Delhi (DU)",
            "Jawaharlal Nehru University (JNU)",
            "Banaras Hindu University (BHU)",
            "Aligarh Muslim University (AMU)",
            "Jamia Millia Islamia (JMI)",
            "University of Hyderabad (UoH)",
            "Visva-Bharati University",
            "Pondicherry University",
            "Indian Institute of Science (IISc), Bangalore",
            "Indian Institutes of Technology (IITs)",
            "Indian Institutes of Management (IIMs)",
            "Indian Statistical Institute (ISI)",
            "National Institutes of Technology (NITs)",
            "All India Institute of Medical Sciences (AIIMS)",
            "Savitribai Phule Pune University",
            "University of Calcutta",
            "University of Madras",
            "Jadavpur University",
            "Osmania University",
            "Punjab University, Chandigarh",
            "Bangalore University",
            "Anna University, Chennai",
            "Vellore Institute of Technology (VIT)",
            "Manipal Academy of Higher Education",
            "Birla Institute of Technology and Science (BITS Pilani)",
            "Symbiosis International University",
            "Amity University",
            "SRM Institute of Science and Technology",
            "Ashoka University",
            "O.P. Jindal Global University",
            "Shiv Nadar University",
            "Christ University, Bangalore",
            "Kalinga Institute of Industrial Technology (KIIT)",
            "Lovely Professional University (LPU)",
            # medical universities
            "All India Institute of Medical Sciences (AIIMS), Delhi",
            "Post Graduate Institute of Medical Education and Research (PGIMER), Chandigarh",
            "Jawaharlal Institute of Postgraduate Medical Education and Research (JIPMER), Puducherry",
            "Kasturba Medical College, Manipal",
            "King George's Medical University, Lucknow",
            "Sri Ramachandra Institute of Higher Education and Research, Chennai",
            "Banaras Hindu University (BHU), Varanasi",
            "Gujarat University, Ahmedabad",
            "NTR University of Health Sciences, Vijayawada",
            "University of Delhi (Medical Sciences)",
            "T.N. Dr. M.G.R. Medical University, Chennai",
            "Rajiv Gandhi University of Health Sciences, Bangalore",
            "KLE University, Belagavi",
            "Bharati Vidyapeeth Deemed University, Pune",
            "Dr. D.Y. Patil Vidyapeeth, Pune",
            "Mahatma Gandhi University of Medical Sciences and Technology, Jaipur",
            "Tamil Nadu Dr. M.G.R. Medical University, Chennai",
            "Indira Gandhi Institute of Medical Sciences, Patna",
            "Government Medical College and Hospital, Chandigarh"
        ],
    "colleges": 
        [
            "Indian Institute of Technology (IIT) Bombay",
            "Indian Institute of Technology (IIT) Delhi",
            "Indian Institute of Technology (IIT) Kanpur",
            "Indian Institute of Technology (IIT) Madras",
            "Indian Institute of Technology (IIT) Kharagpur",
            "National Institute of Technology (NIT) Trichy",
            "National Institute of Technology (NIT) Surathkal",
            "National Institute of Technology (NIT) Warangal",
            "Birla Institute of Technology and Science (BITS) Pilani",
            "Vellore Institute of Technology (VIT)",
            "Manipal Institute of Technology (MIT)",  
            "Thapar Institute of Engineering and Technology",
            "PES University",
            "Chennai Institute of Technology",
            "Shiv Nadar University",
            "Loyola Academy Degree and PG College",  
            "St. Stephen’s College",
            "Lady Shri Ram College for Women (LSR)",
            "Loyola College",
            "Presidency College",
            "Christ University",
            "Madras Christian College (MCC)",
            "Hindu College",
            "Miranda House",
            "Fergusson College",
            "St. Xavier’s College",
            "Hansraj College",
            "Ramjas College",
            "Sri Venkateswara College",
            "Mount Carmel College",
            "Symbiosis College of Arts and Commerce",
            "Indraprastha College for Women",
            "St. Joseph’s College",
            "Sophia College for Women",
            "Gargi College",
            "Kirori Mal College",
            "Nizam College",
            "St. Francis College for Women",
            "Loyola Academy Degree and PG College",
            "Osmania University College for Women",
            "St. Ann’s College for Women",
            "Bhavan’s Vivekananda College of Science, Humanities & Commerce",
            "Aurora’s Degree College",
            "Indian Institute of Management and Commerce (IIMC)",
            "AV College of Arts, Science & Commerce",
            "RBVRR Women’s College",
            "Badruka College of Commerce and Arts",
            "Malla Reddy College of Arts, Commerce & Science",
            "St. Joseph's Degree & PG College",
            "Kasturba Gandhi Degree & PG College for Women",
            "Villa Marie College for Women",
            "King Edward Memorial Hospital and Seth Gordhandas Sunderdas Medical College (KEM), Mumbai",
            "Christian Medical College (CMC), Vellore",
            "JIPMER (Jawaharlal Institute of Postgraduate Medical Education and Research), Puducherry",
            "Maulana Azad Medical College, Delhi",
            "Grant Medical College, Mumbai",
            "Lady Hardinge Medical College, Delhi",
            "Madras Medical College, Chennai",
            "Kasturba Medical College, Manipal",
            "B.J. Medical College, Ahmedabad",
            "Gujarat Medical Education and Research Society (GMERS), Gandhinagar",
            "Dr. D.Y. Patil Medical College, Navi Mumbai",
            "Sri Ramachandra Institute of Higher Education and Research, Chennai",
            "Rajasthan University of Health Sciences, Jaipur",
            "University College of Medical Sciences, Delhi",
            "Institute of Post Graduate Medical Education and Research, Kolkata",
            "Sree Chitra Tirunal Institute for Medical Sciences and Technology, Thiruvananthapuram",
            "Kerala University of Health Sciences, Thrissur",
            "Government Medical College, Thiruvananthapuram",
            "Lala Lajpat Rai Memorial Medical College, Meerut",
            "Indian Institute of Technology (IIT) Hyderabad",
            "International Institute of Information Technology (IIIT) Hyderabad",
            "Jawaharlal Nehru Technological University (JNTU) Hyderabad",
            "Osmania University College of Engineering",
            "Chaitanya Bharathi Institute of Technology (CBIT)",
            "Vasavi College of Engineering",
            "MVSR Engineering College",
            "Gokaraju Rangaraju Institute of Engineering and Technology (GRIET)",
            "CVR College of Engineering",
            "VNR Vignana Jyothi Institute of Engineering and Technology",
            "Malla Reddy Engineering College",
            "Sreenidhi Institute of Science and Technology (SNIST)",
            "Mahatma Gandhi Institute of Technology (MGIT)",
            "Institute of Aeronautical Engineering (IARE)",
            "Stanley College of Engineering and Technology for Women",
            "Chennai Institute of Technology",
            "Shiv Nadar University",
            "Loyola Academy Degree and PG College",
            "Mahatma Gandhi Institute of Technology (MGIT)",
            "Sardar Patel Institute of Technology (SPIT)",
            "Nirma University"
        ],

}