import type { StudyPlan, BlockResources, StudentIntake } from '../types/models';
import dayjs from 'dayjs';
import puppeteer, { type PDFOptions, type Browser } from 'puppeteer';

// Color mapping for different cycle types (matching the original PDFService)
const CYCLE_TYPE_COLORS = {
  'C1': { bg: '#e3f2fd', border: '#1976d2', text: '#0d47a1' }, // Blue
  'C2': { bg: '#e8f5e8', border: '#388e3c', text: '#1b5e20' }, // Green
  'C3': { bg: '#fce4ec', border: '#e91e63', text: '#880e4f' }, // Pink
  'C4': { bg: '#ffebee', border: '#f44336', text: '#b71c1c' }, // Red
  'C5': { bg: '#f3e5f5', border: '#9c27b0', text: '#4a148c' }, // Purple
  'C5.b': { bg: '#f3e5f5', border: '#9c27b0', text: '#4a148c' }, // Purple
  'C6': { bg: '#e1f5fe', border: '#00bcd4', text: '#006064' }, // Cyan
  'C7': { bg: '#fff3e0', border: '#ff9800', text: '#e65100' }, // Orange
  'C8': { bg: '#f1f8e9', border: '#8bc34a', text: '#33691e' }, // Light Green
} as const;

// Calendar view types
export type CalendarViewType = 'year' | 'month' | 'week';

/**
 * Calendar-oriented PDF generation service for Helios Study Planner
 * Specializes in calendar grid views at year, month, and week levels
 * Maintains drop-in compatibility with PDFService and HighFidelityPDFService
 */
export class CalendarPDFService {
  
  /**
   * Generate structured PDF that matches Word document format with calendar views
   * This is the RECOMMENDED method for calendar-oriented study plan PDFs
   */
  public static async generateStructuredPDF(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    filename?: string
  ): Promise<void> {
    try {
      // Create calendar-oriented HTML template
      const htmlContent = await this.createCalendarHTML(studyPlan, studentIntake, 'year');
      
      // Generate PDF using Puppeteer
      const pdfBuffer = await this.generatePDFFromHTML(htmlContent, {
        format: 'A4',
        printBackground: true,
        margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' },
        preferCSSPageSize: false,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `
          <div style="font-size: 10px; text-align: center; width: 100%; color: #666; margin: 0 15px;">
            <span class="title"></span> - Generated by Helios Study Planner on ${new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })} - Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </div>
        `
      });
      
      // Save the PDF
      await this.savePDF(pdfBuffer, filename || `calendar-study-plan-${studyPlan.study_plan_id || 'plan'}.pdf`);
      
    } catch (error) {
      console.error('Failed to generate calendar PDF:', error);
      throw new Error('Calendar PDF generation failed');
    }
  }

  /**
   * Generate visual PDF with calendar views and modern design
   * Use this for presentation-style PDFs with calendar visualizations
   */
  static async generateVisualPDF(
    studyPlan: StudyPlan,
    studentIntake: StudentIntake,
    filename?: string
  ): Promise<void> {
    try {
      // Create enhanced calendar visual HTML template
      const htmlContent = await this.createCalendarHTML(studyPlan, studentIntake, 'month');
      
      // Generate PDF using Puppeteer with enhanced visual settings
      const pdfBuffer = await this.generatePDFFromHTML(htmlContent, {
        format: 'A4',
        printBackground: true,
        margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' },
        preferCSSPageSize: false,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `
          <div style="font-size: 10px; text-align: center; width: 100%; color: #666; margin: 0 15px;">
            Generated by Helios Study Planner on ${new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })} - Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </div>
        `
      });
      
      // Save the PDF
      await this.savePDF(pdfBuffer, filename || `calendar-visual-study-plan-${studyPlan.study_plan_id || 'plan'}.pdf`);
      
    } catch (error) {
      console.error('Failed to generate visual calendar PDF:', error);
      throw new Error('Visual calendar PDF generation failed');
    }
  }

  /**
   * Main entry point - defaults to structured PDF (recommended)
   * Matches the exact interface of the original PDFService
   */
  static async generateStudyPlanPDF(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    options?: {
      filename?: string;
      type?: 'structured' | 'visual';
      calendarView?: CalendarViewType;
    }
  ): Promise<void> {
    const type = options?.type || 'structured';
    
    if (type === 'visual') {
      return this.generateVisualPDF(studyPlan, studentIntake, options?.filename);
    } else {
      return this.generateStructuredPDF(studyPlan, studentIntake, options?.filename);
    }
  }

  /**
   * Generate calendar PDF with specific view type
   */
  static async generateCalendarPDF(
    studyPlan: StudyPlan,
    studentIntake: StudentIntake,
    viewType: CalendarViewType = 'year',
    filename?: string
  ): Promise<void> {
    try {
      const htmlContent = await this.createCalendarHTML(studyPlan, studentIntake, viewType);
      
      const pdfBuffer = await this.generatePDFFromHTML(htmlContent, {
        format: 'A4',
        printBackground: true,
        margin: { top: '15px', right: '15px', bottom: '15px', left: '15px' },
        preferCSSPageSize: false,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `
          <div style="font-size: 9px; text-align: center; width: 100%; color: #666; margin: 0 10px;">
            ${viewType.charAt(0).toUpperCase() + viewType.slice(1)} Calendar View - 
            Generated on ${new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })} - Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </div>
        `
      });
      
      await this.savePDF(pdfBuffer, filename || `calendar-${viewType}-${studyPlan.study_plan_id || 'plan'}.pdf`);
      
    } catch (error) {
      console.error(`Failed to generate ${viewType} calendar PDF:`, error);
      throw new Error(`${viewType} calendar PDF generation failed`);
    }
  }

  // ===== CORE PDF GENERATION METHODS =====

  /**
   * Generate PDF from HTML using Puppeteer with high-quality settings
   */
  private static async generatePDFFromHTML(htmlContent: string, options: PDFOptions): Promise<Buffer> {
    let browser: Browser | null = null;
    
    try {
      // Launch browser with optimized settings for PDF generation
      browser = await puppeteer.launch({
        headless: true,
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--disable-gpu',
          '--disable-web-security',
          '--disable-features=VizDisplayCompositor',
          '--run-all-compositor-stages-before-draw',
          '--disable-extensions-http-throttling'
        ],
        // Use system Chrome if available for better font rendering
        executablePath: process.env.CHROME_PATH || undefined
      });

      const page = await browser.newPage();
      
      // Set viewport for consistent rendering
      await page.setViewport({ width: 1200, height: 1600, deviceScaleFactor: 2 });
      
      // Enable better font rendering
      await page.evaluateOnNewDocument(() => {
        // Improve text rendering
        const style = document.createElement('style');
        style.innerHTML = `
          * {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            text-rendering: optimizeLegibility;
          }
        `;
        document.head.appendChild(style);
      });

      // Set content with proper encoding
      await page.setContent(htmlContent, {
        waitUntil: ['networkidle0', 'domcontentloaded'],
        timeout: 30000
      });

      // Wait for any dynamic content to load
      await new Promise(resolve => setTimeout(resolve, 2000));

      // Generate PDF with high-quality settings
      const pdfBuffer = await page.pdf({
        ...options,
        preferCSSPageSize: false,
        printBackground: true
      });

      return Buffer.from(pdfBuffer);
    } finally {
      if (browser) {
        await browser.close();
      }
    }
  }

  /**
   * Save PDF to appropriate location (filesystem or browser download)
   */
  private static async savePDF(pdfBuffer: Buffer, filename: string): Promise<void> {
    if (typeof window !== 'undefined') {
      // Browser environment - trigger download
      const blob = new Blob([new Uint8Array(pdfBuffer)], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
      console.log(`📁 Calendar PDF download triggered: ${filename}`);
    } else {
      // Node.js environment - save to filesystem
      const fs = await import('fs');
      const path = await import('path');
      
      const outputDir = path.join(process.cwd(), 'generated-docs');
      
      // Ensure output directory exists
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }
      
      const outputPath = path.join(outputDir, filename);
      fs.writeFileSync(outputPath, pdfBuffer);
      
      console.log(`✅ Calendar PDF saved: ${filename}`);
      console.log(`   📁 Location: ${outputPath}`);
    }
  }

  // ===== CALENDAR HTML GENERATION METHODS =====

  /**
   * Create calendar-oriented HTML template
   */
  private static async createCalendarHTML(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    viewType: CalendarViewType
  ): Promise<string> {
    const targetYear = studyPlan.targeted_year || new Date().getFullYear() + 1;
    
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Study Planner Calendar - ${targetYear}</title>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        ${this.getCalendarCSS()}
    </head>
    <body>
        <div class="container">
            ${this.generateStudentProfile(studyPlan, studentIntake)}
            ${await this.generateCalendarView(studyPlan, studentIntake, viewType)}
            ${this.generateLegend()}
        </div>
    </body>
    </html>`;
  }

  /**
   * Generate student profile section
   */
  private static generateStudentProfile(studyPlan: StudyPlan, studentIntake: StudentIntake): string {
    const targetYear = studyPlan.targeted_year || new Date().getFullYear() + 1;
    const totalWeeks = this.calculateTotalWeeks(studyPlan);
    const totalBlocks = this.countTotalBlocks(studyPlan);
    const uniqueSubjects = this.getUniqueSubjects(studyPlan);
    
    return `
    <div class="student-profile">
        <div class="profile-header">
            <div class="profile-title">${studyPlan.plan_title || 'Study Plan Calendar'}</div>
            <div class="profile-subtitle">UPSC ${targetYear} Preparation Schedule</div>
        </div>
        
        <div class="profile-stats">
            <div class="stat-item">
                <div class="stat-label">Student</div>
                <div class="stat-value">${studentIntake.personal_details?.full_name || 'Student'}</div>
            </div>
            <div class="stat-item">
                <div class="stat-label">Start Date</div>
                <div class="stat-value">${dayjs(studentIntake.start_date).format('MMM DD, YYYY')}</div>
            </div>
            <div class="stat-item">
                <div class="stat-label">Duration</div>
                <div class="stat-value">${totalWeeks} weeks</div>
            </div>
            <div class="stat-item">
                <div class="stat-label">Cycles</div>
                <div class="stat-value">${studyPlan.cycles?.length || 0}</div>
            </div>
            <div class="stat-item">
                <div class="stat-label">Blocks</div>
                <div class="stat-value">${totalBlocks}</div>
            </div>
            <div class="stat-item">
                <div class="stat-label">Subjects</div>
                <div class="stat-value">${uniqueSubjects.length}</div>
            </div>
        </div>
    </div>`;
  }

  /**
   * Generate calendar view based on type
   */
  private static async generateCalendarView(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    viewType: CalendarViewType
  ): Promise<string> {
    switch (viewType) {
      case 'year':
        return this.generateYearView(studyPlan, studentIntake);
      case 'month':
        return this.generateMonthView(studyPlan, studentIntake);
      case 'week':
        return this.generateWeekView(studyPlan, studentIntake);
      default:
        return this.generateYearView(studyPlan, studentIntake);
    }
  }

  /**
   * Generate year view calendar
   */
  private static generateYearView(studyPlan: StudyPlan, studentIntake: StudentIntake): string {
    const targetYear = studyPlan.targeted_year || new Date().getFullYear() + 1;
    const startDate = dayjs(studentIntake.start_date);
    const studyPlanMap = this.createStudyPlanMap(studyPlan);
    
    let monthsHTML = '';
    
    // Generate 12 months starting from start date
    for (let i = 0; i < 12; i++) {
      const monthDate = startDate.add(i, 'month');
      monthsHTML += this.generateMonthGrid(monthDate, studyPlanMap);
    }
    
    return `
    <div class="calendar-section">
        <div class="section-header">
            <h2 class="section-title">📅 Year Calendar View - ${targetYear}</h2>
            <p class="section-description">Complete year overview showing all study cycles and blocks</p>
        </div>
        
        <div class="year-grid">
            ${monthsHTML}
        </div>
    </div>`;
  }

  /**
   * Generate month view calendar
   */
  private static generateMonthView(studyPlan: StudyPlan, studentIntake: StudentIntake): string {
    const startDate = dayjs(studentIntake.start_date);
    const studyPlanMap = this.createStudyPlanMap(studyPlan);
    
    let monthsHTML = '';
    
    // Generate detailed monthly views for the study period
    const totalMonths = Math.ceil(this.calculateTotalWeeks(studyPlan) / 4);
    
    for (let i = 0; i < Math.min(totalMonths, 18); i++) { // Limit to 18 months for PDF size
      const monthDate = startDate.add(i, 'month');
      monthsHTML += this.generateDetailedMonthView(monthDate, studyPlanMap);
    }
    
    return `
    <div class="calendar-section">
        <div class="section-header">
            <h2 class="section-title">📅 Monthly Calendar View</h2>
            <p class="section-description">Detailed monthly breakdown of study cycles and daily activities</p>
        </div>
        
        <div class="month-view-container">
            ${monthsHTML}
        </div>
    </div>`;
  }

  /**
   * Generate week view calendar
   */
  private static generateWeekView(studyPlan: StudyPlan, studentIntake: StudentIntake): string {
    const startDate = dayjs(studentIntake.start_date);
    const studyPlanMap = this.createStudyPlanMap(studyPlan);
    
    let weeksHTML = '';
    const totalWeeks = Math.min(this.calculateTotalWeeks(studyPlan), 52); // Limit to 1 year for PDF size
    
    for (let i = 0; i < totalWeeks; i++) {
      const weekStart = startDate.add(i, 'week').startOf('week');
      weeksHTML += this.generateWeekGrid(weekStart, studyPlanMap, i + 1);
    }
    
    return `
    <div class="calendar-section">
        <div class="section-header">
            <h2 class="section-title">📅 Weekly Calendar View</h2>
            <p class="section-description">Week-by-week detailed study schedule with daily breakdowns</p>
        </div>
        
        <div class="week-view-container">
            ${weeksHTML}
        </div>
    </div>`;
  }

  /**
   * Generate a single month grid for year view
   */
  private static generateMonthGrid(monthDate: dayjs.Dayjs, studyPlanMap: Map<string, any>): string {
    const monthName = monthDate.format('MMMM');
    const year = monthDate.format('YYYY');
    const firstDay = monthDate.startOf('month');
    const lastDay = monthDate.endOf('month');
    const startOfWeek = firstDay.startOf('week');
    
    let daysHTML = '';
    
    // Generate day headers
    const dayHeaders = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
    dayHeaders.forEach(day => {
      daysHTML += `<div class="day-header">${day}</div>`;
    });
    
    // Generate calendar days
    let currentDay = startOfWeek;
    for (let i = 0; i < 42; i++) { // 6 weeks max
      const isCurrentMonth = currentDay.month() === monthDate.month();
      const dayKey = currentDay.format('YYYY-MM-DD');
      const studyInfo = studyPlanMap.get(dayKey);
      
      let dayClass = 'calendar-day';
      let dayContent = currentDay.format('D');
      let studyIndicator = '';
      
      if (!isCurrentMonth) {
        dayClass += ' other-month';
      } else if (studyInfo) {
        dayClass += ` study-day cycle-${studyInfo.cycleType}`;
        studyIndicator = `<div class="study-indicator" style="background-color: ${CYCLE_TYPE_COLORS[studyInfo.cycleType as keyof typeof CYCLE_TYPE_COLORS]?.border || '#666'}"></div>`;
      }
      
      daysHTML += `
        <div class="${dayClass}">
          ${dayContent}
          ${studyIndicator}
        </div>
      `;
      
      currentDay = currentDay.add(1, 'day');
      if (currentDay.isAfter(lastDay.add(7, 'day'))) break;
    }
    
    return `
    <div class="month-container">
        <div class="month-header">
            <div class="month-name">${monthName}</div>
            <div class="month-year">${year}</div>
        </div>
        <div class="month-grid">
            ${daysHTML}
        </div>
    </div>`;
  }

  /**
   * Generate detailed month view
   */
  private static generateDetailedMonthView(monthDate: dayjs.Dayjs, studyPlanMap: Map<string, any>): string {
    const monthName = monthDate.format('MMMM YYYY');
    const firstDay = monthDate.startOf('month');
    const lastDay = monthDate.endOf('month');
    const startOfWeek = firstDay.startOf('week');
    
    let weeksHTML = '';
    let currentWeekStart = startOfWeek;
    
    while (currentWeekStart.isBefore(lastDay.add(1, 'week'))) {
      let weekDaysHTML = '';
      
      for (let i = 0; i < 7; i++) {
        const currentDay = currentWeekStart.add(i, 'day');
        const isCurrentMonth = currentDay.month() === monthDate.month();
        const dayKey = currentDay.format('YYYY-MM-DD');
        const studyInfo = studyPlanMap.get(dayKey);
        
        let dayClass = 'detailed-day';
        if (!isCurrentMonth) dayClass += ' other-month';
        if (studyInfo) dayClass += ` study-day cycle-${studyInfo.cycleType}`;
        
        const cycleInfo = studyInfo ? CYCLE_TYPE_COLORS[studyInfo.cycleType as keyof typeof CYCLE_TYPE_COLORS] : null;
        
        weekDaysHTML += `
          <div class="${dayClass}" ${cycleInfo ? `style="border-left: 4px solid ${cycleInfo.border}; background-color: ${cycleInfo.bg};"` : ''}>
            <div class="day-number">${currentDay.format('D')}</div>
            <div class="day-name">${currentDay.format('ddd')}</div>
            ${studyInfo ? `
              <div class="study-content">
                <div class="cycle-name">${studyInfo.cycleName || studyInfo.cycleType}</div>
                <div class="block-name">${studyInfo.blockTitle}</div>
                <div class="subjects">${studyInfo.subjects?.slice(0, 2).join(', ') || ''}</div>
              </div>
            ` : '<div class="no-study">Rest Day</div>'}
          </div>
        `;
      }
      
      weeksHTML += `<div class="detailed-week">${weekDaysHTML}</div>`;
      currentWeekStart = currentWeekStart.add(1, 'week');
    }
    
    return `
    <div class="detailed-month">
        <div class="detailed-month-header">
            <h3>${monthName}</h3>
        </div>
        <div class="detailed-month-grid">
            ${weeksHTML}
        </div>
    </div>`;
  }

  /**
   * Generate week grid
   */
  private static generateWeekGrid(weekStart: dayjs.Dayjs, studyPlanMap: Map<string, any>, weekNumber: number): string {
    const weekEnd = weekStart.endOf('week');
    let daysHTML = '';
    
    for (let i = 0; i < 7; i++) {
      const currentDay = weekStart.add(i, 'day');
      const dayKey = currentDay.format('YYYY-MM-DD');
      const studyInfo = studyPlanMap.get(dayKey);
      
      const cycleInfo = studyInfo ? CYCLE_TYPE_COLORS[studyInfo.cycleType as keyof typeof CYCLE_TYPE_COLORS] : null;
      
      daysHTML += `
        <div class="week-day" ${cycleInfo ? `style="border: 2px solid ${cycleInfo.border}; background-color: ${cycleInfo.bg};"` : ''}>
          <div class="week-day-header">
            <div class="week-day-name">${currentDay.format('dddd')}</div>
            <div class="week-day-date">${currentDay.format('MMM D')}</div>
          </div>
          <div class="week-day-content">
            ${studyInfo ? `
              <div class="week-cycle-info">
                <div class="week-cycle-name">${studyInfo.cycleName || studyInfo.cycleType}</div>
                <div class="week-block-name">${studyInfo.blockTitle}</div>
              </div>
              <div class="week-subjects">
                ${studyInfo.subjects?.map((subject: string) => `<span class="subject-tag">${subject}</span>`).join('') || ''}
              </div>
              <div class="week-resources">
                ${studyInfo.resources?.slice(0, 3).map((resource: string) => `<div class="resource-item">• ${resource}</div>`).join('') || ''}
              </div>
            ` : '<div class="no-study-week">Rest Day</div>'}
          </div>
        </div>
      `;
    }
    
    return `
    <div class="week-container">
        <div class="week-header">
            <div class="week-title">Week ${weekNumber}</div>
            <div class="week-dates">${weekStart.format('MMM D')} - ${weekEnd.format('MMM D, YYYY')}</div>
        </div>
        <div class="week-grid">
            ${daysHTML}
        </div>
    </div>`;
  }

  /**
   * Generate legend for cycle types
   */
  private static generateLegend(): string {
    let legendHTML = '';
    
    Object.entries(CYCLE_TYPE_COLORS).forEach(([cycleType, colors]) => {
      const description = this.getCycleTypeDescription(cycleType);
      legendHTML += `
        <div class="legend-item">
          <div class="legend-color" style="background-color: ${colors.border};"></div>
          <div class="legend-text">
            <span class="legend-cycle">${cycleType}</span>
            <span class="legend-desc">${description}</span>
          </div>
        </div>
      `;
    });
    
    return `
    <div class="legend-section">
        <div class="legend-header">
            <h3>📚 Study Cycle Legend</h3>
        </div>
        <div class="legend-grid">
            ${legendHTML}
        </div>
    </div>`;
  }

  /**
   * Create study plan map for quick date lookups
   */
  private static createStudyPlanMap(studyPlan: StudyPlan): Map<string, any> {
    const studyMap = new Map();
    
    studyPlan.cycles?.forEach(cycle => {
      cycle.cycleBlocks?.forEach(block => {
        const startDate = dayjs(block.block_start_date);
        const endDate = dayjs(block.block_end_date);
        
        if (startDate.isValid() && endDate.isValid()) {
          let currentDate = startDate;
          while (currentDate.isBefore(endDate) || currentDate.isSame(endDate)) {
            const dateKey = currentDate.format('YYYY-MM-DD');
            studyMap.set(dateKey, {
              cycleType: cycle.cycleType,
              cycleName: cycle.cycleName,
              blockTitle: block.block_title,
              subjects: block.subjects,
              resources: this.getBlockResourceTitles(block.block_resources)
            });
            currentDate = currentDate.add(1, 'day');
          }
        }
      });
    });
    
    return studyMap;
  }

  /**
   * Get block resource titles
   */
  private static getBlockResourceTitles(blockResources?: BlockResources): string[] {
    if (!blockResources) return [];
    
    const titles: string[] = [];
    
    if (blockResources.primary_books) {
      titles.push(...blockResources.primary_books.map(book => book.resource_title));
    }
    
    if (blockResources.supplementary_materials) {
      titles.push(...blockResources.supplementary_materials.map(mat => mat.resource_title));
    }
    
    if (blockResources.current_affairs_sources) {
      titles.push(...blockResources.current_affairs_sources.map(ca => ca.resource_title));
    }
    
    return titles.slice(0, 5); // Limit for display
  }

  /**
   * Get cycle type description
   */
  private static getCycleTypeDescription(cycleType: string): string {
    switch (cycleType) {
      case 'C1': return 'NCERT Foundation';
      case 'C2': return 'Foundation Building';
      case 'C3': return 'Mains Pre-Prelims';
      case 'C4': return 'Prelims Reading';
      case 'C5': return 'Prelims Revision';
      case 'C5.b': return 'Prelims Rapid Revision';
      case 'C6': return 'Mains Revision';
      case 'C7': return 'Mains Rapid Revision';
      case 'C8': return 'Mains Foundation';
      default: return 'Study Cycle';
    }
  }

  /**
   * Get calendar CSS styles
   */
  private static getCalendarCSS(): string {
    return `
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
      
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        text-rendering: optimizeLegibility;
      }
      
      body {
        font-family: 'Inter', sans-serif;
        background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
        min-height: 100vh;
        padding: 10px;
        font-size: 12px;
        line-height: 1.4;
      }
      
      .container {
        max-width: 1200px;
        margin: 0 auto;
        background: white;
        border-radius: 15px;
        box-shadow: 0 15px 35px rgba(0,0,0,0.1);
        overflow: hidden;
      }
      
      /* Student Profile Section */
      .student-profile {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        padding: 25px;
      }
      
      .profile-header {
        text-align: center;
        margin-bottom: 20px;
      }
      
      .profile-title {
        font-size: 1.8rem;
        font-weight: 700;
        margin-bottom: 6px;
        letter-spacing: -0.02em;
      }
      
      .profile-subtitle {
        font-size: 1rem;
        font-weight: 300;
        opacity: 0.9;
      }
      
      .profile-stats {
        display: grid;
        grid-template-columns: repeat(6, 1fr);
        gap: 15px;
        margin-top: 20px;
      }
      
      .stat-item {
        text-align: center;
        background: rgba(255, 255, 255, 0.1);
        padding: 12px 8px;
        border-radius: 8px;
        backdrop-filter: blur(10px);
      }
      
      .stat-label {
        font-size: 0.75rem;
        font-weight: 500;
        opacity: 0.8;
        margin-bottom: 4px;
      }
      
      .stat-value {
        font-size: 0.9rem;
        font-weight: 600;
      }
      
      /* Calendar Section */
      .calendar-section {
        padding: 25px;
      }
      
      .section-header {
        margin-bottom: 20px;
        text-align: center;
      }
      
      .section-title {
        font-size: 1.4rem;
        font-weight: 700;
        color: #2d3748;
        margin-bottom: 6px;
      }
      
      .section-description {
        font-size: 0.9rem;
        color: #718096;
      }
      
      /* Year View */
      .year-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 15px;
        margin-bottom: 20px;
      }
      
      .month-container {
        background: #fff;
        border: 1px solid #e2e8f0;
        border-radius: 8px;
        overflow: hidden;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
      }
      
      .month-header {
        background: #f7fafc;
        padding: 8px;
        text-align: center;
        border-bottom: 1px solid #e2e8f0;
      }
      
      .month-name {
        font-size: 0.8rem;
        font-weight: 600;
        color: #2d3748;
      }
      
      .month-year {
        font-size: 0.7rem;
        color: #718096;
      }
      
      .month-grid {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        gap: 1px;
        background: #e2e8f0;
      }
      
      .day-header {
        background: #4a5568;
        color: white;
        padding: 4px 2px;
        text-align: center;
        font-size: 0.65rem;
        font-weight: 600;
      }
      
      .calendar-day {
        background: white;
        padding: 4px 2px;
        text-align: center;
        font-size: 0.65rem;
        min-height: 24px;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        position: relative;
      }
      
      .calendar-day.other-month {
        background: #f7fafc;
        color: #a0aec0;
      }
      
      .calendar-day.study-day {
        font-weight: 600;
      }
      
      .study-indicator {
        position: absolute;
        bottom: 1px;
        left: 50%;
        transform: translateX(-50%);
        width: 4px;
        height: 2px;
        border-radius: 1px;
      }
      
      /* Month View */
      .month-view-container {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 20px;
      }
      
      .detailed-month {
        background: white;
        border: 1px solid #e2e8f0;
        border-radius: 8px;
        overflow: hidden;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
      }
      
      .detailed-month-header {
        background: #2d3748;
        color: white;
        padding: 12px;
        text-align: center;
      }
      
      .detailed-month-header h3 {
        font-size: 1rem;
        font-weight: 600;
      }
      
      .detailed-month-grid {
        padding: 8px;
      }
      
      .detailed-week {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        gap: 2px;
        margin-bottom: 2px;
      }
      
      .detailed-day {
        background: #f7fafc;
        border: 1px solid #e2e8f0;
        border-radius: 4px;
        padding: 6px 4px;
        min-height: 60px;
        font-size: 0.7rem;
      }
      
      .detailed-day.other-month {
        opacity: 0.5;
      }
      
      .day-number {
        font-weight: 600;
        margin-bottom: 2px;
      }
      
      .day-name {
        font-size: 0.6rem;
        color: #718096;
        margin-bottom: 4px;
      }
      
      .study-content {
        font-size: 0.6rem;
      }
      
      .cycle-name {
        font-weight: 600;
        margin-bottom: 1px;
      }
      
      .block-name {
        color: #4a5568;
        margin-bottom: 1px;
      }
      
      .subjects {
        color: #718096;
        font-size: 0.55rem;
      }
      
      .no-study {
        color: #a0aec0;
        font-style: italic;
        font-size: 0.6rem;
      }
      
      /* Week View */
      .week-view-container {
        display: grid;
        gap: 15px;
      }
      
      .week-container {
        background: white;
        border: 1px solid #e2e8f0;
        border-radius: 8px;
        overflow: hidden;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
      }
      
      .week-header {
        background: #2d3748;
        color: white;
        padding: 10px 15px;
        display: flex;
        justify-content: space-between;
        align-items: center;
      }
      
      .week-title {
        font-size: 0.9rem;
        font-weight: 600;
      }
      
      .week-dates {
        font-size: 0.8rem;
        opacity: 0.9;
      }
      
      .week-grid {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        gap: 8px;
        padding: 12px;
      }
      
      .week-day {
        background: #f7fafc;
        border: 1px solid #e2e8f0;
        border-radius: 6px;
        padding: 8px;
        min-height: 120px;
      }
      
      .week-day-header {
        margin-bottom: 6px;
        padding-bottom: 4px;
        border-bottom: 1px solid #e2e8f0;
      }
      
      .week-day-name {
        font-size: 0.7rem;
        font-weight: 600;
        color: #2d3748;
      }
      
      .week-day-date {
        font-size: 0.65rem;
        color: #718096;
      }
      
      .week-cycle-info {
        margin-bottom: 4px;
      }
      
      .week-cycle-name {
        font-size: 0.65rem;
        font-weight: 600;
        color: #2d3748;
      }
      
      .week-block-name {
        font-size: 0.6rem;
        color: #4a5568;
      }
      
      .week-subjects {
        margin-bottom: 4px;
      }
      
      .subject-tag {
        background: #edf2f7;
        color: #4a5568;
        padding: 1px 4px;
        border-radius: 3px;
        font-size: 0.55rem;
        margin-right: 2px;
        margin-bottom: 2px;
        display: inline-block;
      }
      
      .week-resources {
        font-size: 0.55rem;
        color: #718096;
      }
      
      .resource-item {
        margin-bottom: 1px;
      }
      
      .no-study-week {
        color: #a0aec0;
        font-style: italic;
        font-size: 0.65rem;
        text-align: center;
        margin-top: 20px;
      }
      
      /* Legend */
      .legend-section {
        background: #f7fafc;
        padding: 20px;
        margin-top: 20px;
      }
      
      .legend-header {
        text-align: center;
        margin-bottom: 15px;
      }
      
      .legend-header h3 {
        font-size: 1.1rem;
        font-weight: 600;
        color: #2d3748;
      }
      
      .legend-grid {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 10px;
      }
      
      .legend-item {
        display: flex;
        align-items: center;
        background: white;
        padding: 8px;
        border-radius: 6px;
        border: 1px solid #e2e8f0;
      }
      
      .legend-color {
        width: 12px;
        height: 12px;
        border-radius: 2px;
        margin-right: 8px;
        flex-shrink: 0;
      }
      
      .legend-cycle {
        font-weight: 600;
        color: #2d3748;
        font-size: 0.75rem;
        margin-right: 6px;
      }
      
      .legend-desc {
        color: #718096;
        font-size: 0.7rem;
      }
      
      /* Print Styles */
      @page {
        size: A4;
        margin: 15mm;
      }
      
      @media print {
        body {
          background: white;
          padding: 0;
        }
        
        .container {
          box-shadow: none;
          border-radius: 0;
        }
        
        .calendar-section {
          page-break-inside: avoid;
        }
        
        .week-container {
          page-break-inside: avoid;
        }
        
        .detailed-month {
          page-break-inside: avoid;
        }
      }
      
      /* Responsive adjustments for PDF */
      @media (max-width: 800px) {
        .year-grid {
          grid-template-columns: repeat(3, 1fr);
        }
        
        .month-view-container {
          grid-template-columns: 1fr;
        }
        
        .profile-stats {
          grid-template-columns: repeat(3, 1fr);
        }
        
        .legend-grid {
          grid-template-columns: repeat(2, 1fr);
        }
      }
    </style>`;
  }

  // ===== HELPER METHODS (matching original PDFService interface) =====

  /**
   * Get unique subjects from study plan
   */
  private static getUniqueSubjects(studyPlan: StudyPlan): string[] {
    const subjects = new Set<string>();
    studyPlan.cycles?.forEach(cycle => {
      cycle.cycleBlocks?.forEach(block => {
        block.subjects?.forEach(subject => subjects.add(subject));
      });
    });
    return Array.from(subjects);
  }

  /**
   * Calculate total weeks across all cycles
   */
  private static calculateTotalWeeks(studyPlan: StudyPlan): number {
    return studyPlan.cycles?.reduce((total, cycle) => total + (cycle.cycleDuration || 0), 0) || 0;
  }

  /**
   * Count total blocks across all cycles
   */
  private static countTotalBlocks(studyPlan: StudyPlan): number {
    return studyPlan.cycles?.reduce((total, cycle) => total + (cycle.cycleBlocks?.length || 0), 0) || 0;
  }
}

export default CalendarPDFService;