import type { StudyPlan, StudyCycle, Block, BlockResources, StudentIntake } from '../types/models';
import { CycleType } from '../types/Types';
import { ResourceService } from './ResourceService';
import { SubjectLoader } from './SubjectLoader';
import dayjs from 'dayjs';
import puppeteer, { type PDFOptions, type Browser } from 'puppeteer';

// Calendar-specific color mapping for different cycle types
const CALENDAR_CYCLE_COLORS = {
  'C1': { bg: '#E3F2FD', border: '#2196F3', text: '#0D47A1' }, // Blue
  'C2': { bg: '#E8F5E8', border: '#4CAF50', text: '#1B5E20' }, // Green  
  'C3': { bg: '#FCE4EC', border: '#E91E63', text: '#880E4F' }, // Pink
  'C4': { bg: '#FFEBEE', border: '#F44336', text: '#B71C1C' }, // Red
  'C5': { bg: '#F3E5F5', border: '#9C27B0', text: '#4A148C' }, // Purple
  'C5.b': { bg: '#F3E5F5', border: '#9C27B0', text: '#4A148C' }, // Purple
  'C6': { bg: '#E1F5FE', border: '#00BCD4', text: '#006064' }, // Cyan
  'C7': { bg: '#FFF3E0', border: '#FF9800', text: '#E65100' }, // Orange
  'C8': { bg: '#F1F8E9', border: '#8BC34A', text: '#33691E' }, // Light Green
} as const;

/**
 * Calendar-focused PDF generation service using Puppeteer
 * Specialized for calendar views, timeline visualizations, and schedule-based PDFs
 * Maintains the same interface as PDFService and HighFidelityPDFService for easy swapping
 */
export class CalendarPDFService {
  
  /**
   * Generate structured PDF with calendar-focused layout
   * Emphasizes timeline, scheduling, and calendar views
   */
  public static async generateStructuredPDF(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    filename?: string
  ): Promise<void> {
    try {
      // Create calendar-optimized HTML template
      const htmlContent = await this.createCalendarStructuredHTML(studyPlan, studentIntake);
      
      // Generate PDF using Puppeteer with calendar-specific settings
      const pdfBuffer = await this.generatePDFFromHTML(htmlContent, {
        format: 'A4',
        printBackground: true,
        margin: { top: '15px', right: '20px', bottom: '15px', left: '20px' },
        preferCSSPageSize: false,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `
          <div style="font-size: 10px; text-align: center; width: 100%; color: #666; margin: 0 15px;">
            <span class="title"></span> - Generated by Helios Calendar Planner on ${new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })} - Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </div>
        `
      });
      
      // Save the PDF
      await this.savePDF(pdfBuffer, filename || `calendar-study-plan-${studyPlan.study_plan_id || 'plan'}.pdf`);
      
    } catch (error) {
      console.error('Failed to generate calendar structured PDF:', error);
      throw new Error('Calendar structured PDF generation failed');
    }
  }

  /**
   * Generate visual PDF with calendar charts and timeline visualizations
   * Specialized for calendar views and scheduling presentations
   */
  static async generateVisualPDF(
    studyPlan: StudyPlan,
    studentIntake: StudentIntake,
    filename?: string
  ): Promise<void> {
    try {
      // Create calendar-focused visual HTML template
      const htmlContent = await this.createCalendarVisualHTML(studyPlan, studentIntake);
      
      // Generate PDF using Puppeteer with enhanced visual settings
      const pdfBuffer = await this.generatePDFFromHTML(htmlContent, {
        format: 'A4',
        printBackground: true,
        margin: { top: '15px', right: '20px', bottom: '15px', left: '20px' },
        preferCSSPageSize: false,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `
          <div style="font-size: 10px; text-align: center; width: 100%; color: #666; margin: 0 15px;">
            Generated by Helios Calendar Planner on ${new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })} - Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </div>
        `
      });
      
      // Save the PDF
      await this.savePDF(pdfBuffer, filename || `calendar-visual-study-plan-${studyPlan.study_plan_id || 'plan'}.pdf`);
      
    } catch (error) {
      console.error('Failed to generate calendar visual PDF:', error);
      throw new Error('Calendar visual PDF generation failed');
    }
  }

  /**
   * Main entry point - defaults to structured PDF (recommended)
   * Matches the exact interface of the original PDFService and HighFidelityPDFService
   */
  static async generateStudyPlanPDF(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    options?: {
      filename?: string;
      type?: 'structured' | 'visual';
    }
  ): Promise<void> {
    const type = options?.type || 'structured';
    
    if (type === 'visual') {
      return this.generateVisualPDF(studyPlan, studentIntake, options?.filename);
    } else {
      return this.generateStructuredPDF(studyPlan, studentIntake, options?.filename);
    }
  }

  // ===== CORE PDF GENERATION METHODS =====

  /**
   * Generate PDF from HTML using Puppeteer with calendar-optimized settings
   */
  private static async generatePDFFromHTML(htmlContent: string, options: PDFOptions): Promise<Buffer> {
    let browser: Browser | null = null;
    
    try {
      // Launch browser with optimized settings for calendar PDF generation
      browser = await puppeteer.launch({
        headless: true,
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--disable-gpu',
          '--disable-web-security',
          '--disable-features=VizDisplayCompositor',
          '--run-all-compositor-stages-before-draw',
          '--disable-extensions-http-throttling'
        ],
        // Use system Chrome if available for better font rendering
        executablePath: process.env.CHROME_PATH || undefined
      });

      const page = await browser.newPage();
      
      // Set viewport for consistent calendar rendering
      await page.setViewport({ width: 1200, height: 1600, deviceScaleFactor: 2 });
      
      // Enable better font rendering for calendar elements
      await page.evaluateOnNewDocument(() => {
        // Improve text rendering for calendar dates and schedules
        const style = document.createElement('style');
        style.innerHTML = `
          * {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            text-rendering: optimizeLegibility;
          }
          .calendar-date, .schedule-time {
            font-variant-numeric: tabular-nums;
          }
        `;
        document.head.appendChild(style);
      });

      // Set content with proper encoding
      await page.setContent(htmlContent, {
        waitUntil: ['networkidle0', 'domcontentloaded'],
        timeout: 30000
      });

      // Wait for calendar charts and dynamic content to load
      await new Promise(resolve => setTimeout(resolve, 3000));

      // Generate PDF with high-quality settings
      const pdfBuffer = await page.pdf({
        ...options,
        preferCSSPageSize: false,
        printBackground: true
      });

      return Buffer.from(pdfBuffer);
    } finally {
      if (browser) {
        await browser.close();
      }
    }
  }

  /**
   * Save PDF to appropriate location (filesystem or browser download)
   */
  private static async savePDF(pdfBuffer: Buffer, filename: string): Promise<void> {
    if (typeof window !== 'undefined') {
      // Browser environment - trigger download
      const blob = new Blob([new Uint8Array(pdfBuffer)], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
      console.log(`📁 Calendar PDF download triggered: ${filename}`);
    } else {
      // Node.js environment - save to filesystem
      const fs = await import('fs');
      const path = await import('path');
      
      const outputDir = path.join(process.cwd(), 'generated-docs');
      
      // Ensure output directory exists
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }
      
      const outputPath = path.join(outputDir, filename);
      fs.writeFileSync(outputPath, pdfBuffer);
      
      console.log(`✅ Calendar PDF saved: ${filename}`);
      console.log(`   📁 Location: ${outputPath}`);
    }
  }

  // ===== CALENDAR HTML TEMPLATE GENERATION METHODS =====

  /**
   * Create calendar-structured HTML template optimized for scheduling and timeline views
   */
  private static async createCalendarStructuredHTML(studyPlan: StudyPlan, studentIntake: StudentIntake): Promise<string> {
    const totalWeeks = this.calculateTotalWeeks(studyPlan);
    const totalBlocks = this.countTotalBlocks(studyPlan);
    const uniqueSubjects = this.getUniqueSubjects(studyPlan);
    const timelineData = this.generateTimelineData(studyPlan);
    
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${studyPlan.plan_title || 'Calendar Study Plan'}</title>
        ${this.getCalendarStructuredCSS()}
    </head>
    <body>
        ${this.generateCalendarHeaderSection(studyPlan, studentIntake)}
        ${this.generateCalendarOverviewSection(studyPlan, studentIntake, totalWeeks, totalBlocks)}
        ${this.generateTimelineSection(studyPlan, timelineData)}
        ${this.generateStudentProfileSection(studentIntake)}
        ${this.generateCalendarBlocksSection(studyPlan)}
        ${await this.generateResourcesSection(studyPlan, uniqueSubjects)}
        ${this.generateCalendarFooter()}
    </body>
    </html>`;
  }

  /**
   * Create calendar-visual HTML template with interactive calendar views and charts
   */
  private static async createCalendarVisualHTML(studyPlan: StudyPlan, studentIntake: StudentIntake): Promise<string> {
    const totalWeeks = this.calculateTotalWeeks(studyPlan);
    const totalBlocks = this.countTotalBlocks(studyPlan);
    const uniqueSubjects = this.getUniqueSubjects(studyPlan);
    const subjectHours = this.calculateSubjectHours(studyPlan);
    const calendarData = this.generateCalendarViewData(studyPlan);
    
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${studyPlan.plan_title || 'Calendar Study Plan'}</title>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns"></script>
        ${this.getCalendarVisualCSS()}
    </head>
    <body>
        <div class="calendar-page">
            <!-- Calendar Header -->
            <div class="calendar-header">
                <h1>${studyPlan.plan_title || 'Calendar Study Plan'}</h1>
                <div class="calendar-subtitle">
                    Strategic UPSC ${studyPlan.targeted_year || '2025'} Calendar & Timeline
                </div>
            </div>
            
            <!-- Calendar Stats Dashboard -->
            <div class="calendar-stats-grid">
                <div class="calendar-stat-card primary">
                    <div class="stat-icon">📅</div>
                    <div class="stat-number">${totalWeeks}</div>
                    <div class="stat-label">Total Weeks</div>
                </div>
                <div class="calendar-stat-card secondary">
                    <div class="stat-icon">🔄</div>
                    <div class="stat-number">${studyPlan.cycles?.length || 0}</div>
                    <div class="stat-label">Study Cycles</div>
                </div>
                <div class="calendar-stat-card success">
                    <div class="stat-icon">📚</div>
                    <div class="stat-number">${totalBlocks}</div>
                    <div class="stat-label">Study Blocks</div>
                </div>
                <div class="calendar-stat-card warning">
                    <div class="stat-icon">🎯</div>
                    <div class="stat-number">${uniqueSubjects.length}</div>
                    <div class="stat-label">Subjects</div>
                </div>
            </div>
            
            <!-- Calendar Timeline Visualization -->
            <div class="calendar-section">
                <div class="calendar-section-header">
                    <h2 class="calendar-section-title">📊 Study Plan Timeline</h2>
                </div>
                
                <div class="calendar-charts-row">
                    <div class="calendar-chart-container">
                        <h3>Cycle Timeline (Gantt View)</h3>
                        <canvas id="timelineChart" width="800" height="300"></canvas>
                    </div>
                    
                    <div class="calendar-chart-container">
                        <h3>Subject Distribution</h3>
                        <canvas id="subjectsChart" width="400" height="300"></canvas>
                    </div>
                </div>
            </div>
            
            <!-- Monthly Calendar View -->
            <div class="calendar-section">
                <div class="calendar-section-header">
                    <h2 class="calendar-section-title">🗓️ Monthly Calendar View</h2>
                </div>
                
                ${this.generateMonthlyCalendarView(studyPlan, calendarData)}
            </div>
            
            <!-- Weekly Schedule View -->
            <div class="calendar-section">
                <div class="calendar-section-header">
                    <h2 class="calendar-section-title">📋 Weekly Schedule Overview</h2>
                </div>
                
                ${this.generateWeeklyScheduleView(studyPlan)}
            </div>
            
            <!-- Calendar Footer -->
            <div class="calendar-footer">
                <div class="calendar-footer-content">
                    <div class="calendar-footer-left">
                        Generated on ${dayjs().format('MMMM DD, YYYY')} | Helios Calendar Planner
                    </div>
                    <div class="calendar-footer-right">
                        Your Scheduled Path to Success
                    </div>
                </div>
            </div>
        </div>
        
        <script>
          // Initialize calendar charts after page load
          document.addEventListener('DOMContentLoaded', function() {
            setTimeout(() => {
              ${this.generateCalendarChartScript(uniqueSubjects, subjectHours, studyPlan, calendarData)}
            }, 200);
          });
        </script>
    </body>
    </html>`;
  }

  // ===== CALENDAR SECTION GENERATION METHODS =====

  private static generateCalendarHeaderSection(studyPlan: StudyPlan, studentIntake: StudentIntake): string {
    const startDate = dayjs(studentIntake.start_date);
    const targetYear = studyPlan.targeted_year || new Date().getFullYear() + 1;
    const planDuration = this.calculateDuration(startDate, targetYear);
    
    return `
    <div class="calendar-header">
        <h1 class="calendar-title">${studyPlan.plan_title || 'Calendar Study Plan'}</h1>
        <div class="calendar-subtitle">
            📅 Start Date: ${startDate.format('DD/MM/YYYY')} | 
            🎯 Target Year: ${targetYear} | 
            ⏱️ Duration: ${planDuration}
        </div>
        <div class="calendar-student-info">
            👤 Student: ${studentIntake.personal_details?.full_name || 'Student'} | 
            📧 ${studentIntake.personal_details?.email || 'N/A'}
        </div>
    </div>`;
  }

  private static generateCalendarOverviewSection(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    totalWeeks: number, 
    totalBlocks: number
  ): string {
    const cycles = studyPlan.cycles || [];
    const targetYear = studyPlan.targeted_year || new Date().getFullYear() + 1;
    const studentName = studentIntake.personal_details?.full_name || 'you';
    
    return `
    <div class="calendar-overview-section">
        <h2 class="calendar-section-title">📋 Calendar Overview</h2>
        
        <div class="calendar-overview-grid">
            <div class="calendar-overview-card">
                <h3>📊 Plan Statistics</h3>
                <div class="calendar-stats">
                    <div class="calendar-stat-item">
                        <span class="calendar-stat-label">Total Duration:</span>
                        <span class="calendar-stat-value">${totalWeeks} weeks</span>
                    </div>
                    <div class="calendar-stat-item">
                        <span class="calendar-stat-label">Study Cycles:</span>
                        <span class="calendar-stat-value">${cycles.length}</span>
                    </div>
                    <div class="calendar-stat-item">
                        <span class="calendar-stat-label">Study Blocks:</span>
                        <span class="calendar-stat-value">${totalBlocks}</span>
                    </div>
                </div>
            </div>
            
            <div class="calendar-overview-card">
                <h3>🎯 Target Information</h3>
                <div class="calendar-stats">
                    <div class="calendar-stat-item">
                        <span class="calendar-stat-label">Target Year:</span>
                        <span class="calendar-stat-value">${targetYear}</span>
                    </div>
                    <div class="calendar-stat-item">
                        <span class="calendar-stat-label">Student:</span>
                        <span class="calendar-stat-value">${studentName}</span>
                    </div>
                    <div class="calendar-stat-item">
                        <span class="calendar-stat-label">Generated:</span>
                        <span class="calendar-stat-value">${dayjs().format('MMM DD, YYYY')}</span>
                    </div>
                </div>
            </div>
        </div>
        
        <p class="calendar-overview-text">
            This calendar-based study plan is strategically designed for ${studentName} 
            for UPSC ${targetYear} preparation, organized across ${cycles.length} specialized 
            cycles spanning ${totalWeeks} weeks with ${totalBlocks} focused study blocks.
        </p>
    </div>`;
  }

  private static generateTimelineSection(studyPlan: StudyPlan, timelineData: any): string {
    const cycles = studyPlan.cycles || [];
    
    const timelineItems = cycles.map((cycle, index) => {
      const cycleColor = CALENDAR_CYCLE_COLORS[cycle.cycleType as keyof typeof CALENDAR_CYCLE_COLORS] || 
                        { bg: '#F5F5F5', border: '#9E9E9E', text: '#424242' };
      
      const startDate = cycle.cycleStartDate ? dayjs(cycle.cycleStartDate).format('MMM DD') : 'TBD';
      const endDate = cycle.cycleEndDate ? dayjs(cycle.cycleEndDate).format('MMM DD') : 'TBD';
      const duration = cycle.cycleDuration || 0;
      
      return `
        <div class="timeline-item" style="border-left: 4px solid ${cycleColor.border};">
          <div class="timeline-marker" style="background-color: ${cycleColor.border};"></div>
          <div class="timeline-content">
            <div class="timeline-header">
              <h4 style="color: ${cycleColor.text};">${cycle.cycleName || cycle.cycleType}</h4>
              <span class="timeline-duration">${duration} weeks</span>
            </div>
            <div class="timeline-dates">${startDate} - ${endDate}</div>
            <div class="timeline-description">${this.getCycleDescription(cycle)}</div>
            <div class="timeline-blocks">
              ${(cycle.cycleBlocks || []).length} study blocks
            </div>
          </div>
        </div>
      `;
    }).join('');
    
    return `
    <div class="calendar-timeline-section">
        <h2 class="calendar-section-title">⏰ Study Plan Timeline</h2>
        <div class="timeline-container">
            ${timelineItems}
        </div>
    </div>`;
  }

  private static generateStudentProfileSection(studentIntake: StudentIntake): string {
    const profileData = this.generateStudentProfileData(studentIntake);
    
    const profileRows = profileData.map(row => `
      <tr>
        <td class="calendar-profile-label">${row[0]}</td>
        <td class="calendar-profile-value">${row[1]}</td>
        <td class="calendar-profile-label">${row[2] || ''}</td>
        <td class="calendar-profile-value">${row[3] || ''}</td>
      </tr>
    `).join('');
    
    return `
    <div class="calendar-profile-section">
        <h2 class="calendar-section-title">👤 Student Profile</h2>
        
        <table class="calendar-profile-table">
            ${profileRows}
        </table>
    </div>`;
  }

  private static generateCalendarBlocksSection(studyPlan: StudyPlan): string {
    if (!studyPlan.cycles) return '';
    
    const cyclesHTML = studyPlan.cycles.map(cycle => this.generateCalendarCycleHTML(cycle)).join('');
    
    return `
    <div class="calendar-blocks-section">
        <h2 class="calendar-section-title">📚 Study Blocks Calendar</h2>
        ${cyclesHTML}
    </div>`;
  }

  private static generateCalendarCycleHTML(cycle: StudyCycle): string {
    const cycleName = cycle.cycleName || 'Untitled Cycle';
    const cycleDescription = this.getCycleDescription(cycle);
    const durationText = `📅 ${cycle.cycleStartDate || 'TBD'} to ${cycle.cycleEndDate || 'TBD'} (${cycle.cycleDuration || 0} weeks)`;
    
    const cycleColor = CALENDAR_CYCLE_COLORS[cycle.cycleType as keyof typeof CALENDAR_CYCLE_COLORS] || 
                     { bg: '#F5F5F5', border: '#9E9E9E', text: '#424242' };
    
    const blocksHTML = (cycle.cycleBlocks || []).map((block, index) => {
      const blockDates = this.calculateBlockDates(cycle, block, index);
      const weekNumber = index + 1;
      const resourceSummary = this.summarizeBlockResources(block.block_resources);
      
      return `
        <div class="calendar-block-item" style="background-color: ${cycleColor.bg}; border-left: 3px solid ${cycleColor.border};">
          <div class="calendar-block-header">
            <div class="calendar-block-title">${block.block_title || 'Untitled Block'}</div>
            <div class="calendar-block-week">Week ${weekNumber}</div>
          </div>
          <div class="calendar-block-dates">
            📅 ${blockDates.start} - ${blockDates.end}
          </div>
          <div class="calendar-block-duration">
            ⏱️ ${block.duration_weeks || 0} week(s)
          </div>
          <div class="calendar-block-subjects">
            🎯 ${block.subjects?.join(', ') || 'No subjects'}
          </div>
          <div class="calendar-block-resources">
            📚 ${resourceSummary.slice(0, 3).join(', ')}${resourceSummary.length > 3 ? '...' : ''}
          </div>
        </div>
      `;
    }).join('');
    
    return `
    <div class="calendar-cycle-container" style="border: 2px solid ${cycleColor.border};">
        <div class="calendar-cycle-header" style="background: linear-gradient(135deg, ${cycleColor.border}, ${cycleColor.bg}); color: ${cycleColor.text};">
            <h3>${cycleName}</h3>
            <div class="calendar-cycle-duration">${durationText}</div>
        </div>
        <div class="calendar-cycle-description">${cycleDescription}</div>
        <div class="calendar-cycle-blocks">
            ${blocksHTML}
        </div>
    </div>`;
  }

  private static async generateResourcesSection(studyPlan: StudyPlan, uniqueSubjects: string[]): Promise<string> {
    let resourcesHTML = '';
    
    for (const subjectCode of uniqueSubjects.slice(0, 8)) { // Limit for calendar view
      try {
        const subjectName = this.getSubjectName(subjectCode);
        const resources = await ResourceService.getResourcesForSubject(subjectCode);
        
        const resourceNames: string[] = [];
        
        if (resources.primary_books && resources.primary_books.length > 0) {
          resources.primary_books.slice(0, 3).forEach(book => {
            resourceNames.push(`📖 ${book.resource_title}`);
          });
        }
        
        if (resources.current_affairs_sources && resources.current_affairs_sources.length > 0) {
          resources.current_affairs_sources.slice(0, 2).forEach(ca => {
            resourceNames.push(`📰 ${ca.resource_title}`);
          });
        }
        
        if (resources.practice_resources && resources.practice_resources.length > 0) {
          resources.practice_resources.slice(0, 2).forEach(practice => {
            resourceNames.push(`✏️ ${practice.resource_title}`);
          });
        }
        
        resourcesHTML += `
        <div class="calendar-subject-resources">
            <h4>${subjectName}</h4>
            <div class="calendar-resource-list">
              ${resourceNames.slice(0, 5).map(resource => `<div class="calendar-resource-item">${resource}</div>`).join('')}
              ${resourceNames.length > 5 ? `<div class="calendar-resource-more">+${resourceNames.length - 5} more resources</div>` : ''}
            </div>
        </div>`;
        
      } catch (error) {
        console.warn(`Failed to load resources for ${subjectCode}`, error);
        const subjectName = this.getSubjectName(subjectCode);
        resourcesHTML += `
        <div class="calendar-subject-resources">
            <h4>${subjectName}</h4>
            <div class="calendar-resource-list">
              <div class="calendar-resource-item">📚 Comprehensive resources available</div>
            </div>
        </div>`;
      }
    }
    
    return `
    <div class="calendar-resources-section">
        <h2 class="calendar-section-title">📚 Study Resources</h2>
        
        <p class="calendar-resources-intro">
            Key study resources organized by subject for your calendar-based study plan:
        </p>
        
        <div class="calendar-resources-grid">
            ${resourcesHTML}
        </div>
    </div>`;
  }

  private static generateCalendarFooter(): string {
    return `
    <div class="calendar-footer">
        <div class="calendar-footer-content">
            <div class="calendar-footer-left">
                Generated on ${dayjs().format('MMMM DD, YYYY')} | Helios Calendar Planner
            </div>
            <div class="calendar-footer-right">
                📅 Your Scheduled Path to Success
            </div>
        </div>
    </div>`;
  }

  // ===== CALENDAR-SPECIFIC VISUALIZATION METHODS =====

  private static generateMonthlyCalendarView(studyPlan: StudyPlan, calendarData: any): string {
    // Generate a simplified monthly calendar view showing cycle phases
    const cycles = studyPlan.cycles || [];
    const currentYear = studyPlan.targeted_year || new Date().getFullYear() + 1;
    
    const months = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ];
    
    const monthsHTML = months.map((month, index) => {
      const monthCycles = cycles.filter(cycle => {
        if (!cycle.cycleStartDate) return false;
        const cycleMonth = dayjs(cycle.cycleStartDate).month();
        return cycleMonth === index;
      });
      
      const monthEventsHTML = monthCycles.map(cycle => {
        const cycleColor = CALENDAR_CYCLE_COLORS[cycle.cycleType as keyof typeof CALENDAR_CYCLE_COLORS] || 
                          { bg: '#F5F5F5', border: '#9E9E9E', text: '#424242' };
        
        return `
          <div class="calendar-month-event" style="background-color: ${cycleColor.bg}; border-left: 3px solid ${cycleColor.border};">
            <div class="calendar-event-title">${cycle.cycleName || cycle.cycleType}</div>
            <div class="calendar-event-duration">${cycle.cycleDuration || 0}w</div>
          </div>
        `;
      }).join('');
      
      return `
        <div class="calendar-month">
          <div class="calendar-month-header">
            <h4>${month} ${currentYear}</h4>
          </div>
          <div class="calendar-month-events">
            ${monthEventsHTML || '<div class="calendar-no-events">No scheduled activities</div>'}
          </div>
        </div>
      `;
    }).join('');
    
    return `
    <div class="calendar-monthly-view">
        ${monthsHTML}
    </div>`;
  }

  private static generateWeeklyScheduleView(studyPlan: StudyPlan): string {
    const cycles = studyPlan.cycles || [];
    
    const weeklyScheduleHTML = cycles.slice(0, 6).map((cycle, cycleIndex) => {
      const cycleColor = CALENDAR_CYCLE_COLORS[cycle.cycleType as keyof typeof CALENDAR_CYCLE_COLORS] || 
                        { bg: '#F5F5F5', border: '#9E9E9E', text: '#424242' };
      
      const blocksHTML = (cycle.cycleBlocks || []).slice(0, 4).map((block, blockIndex) => {
        const weekNumber = blockIndex + 1;
        const subjects = block.subjects?.slice(0, 3).join(', ') || 'No subjects';
        
        return `
          <div class="weekly-schedule-block" style="background-color: ${cycleColor.bg};">
            <div class="weekly-block-week">Week ${weekNumber}</div>
            <div class="weekly-block-title">${block.block_title || 'Study Block'}</div>
            <div class="weekly-block-subjects">${subjects}</div>
            <div class="weekly-block-duration">${block.duration_weeks || 1} week</div>
          </div>
        `;
      }).join('');
      
      return `
        <div class="weekly-schedule-cycle" style="border-left: 4px solid ${cycleColor.border};">
          <div class="weekly-cycle-header">
            <h4 style="color: ${cycleColor.text};">${cycle.cycleName || cycle.cycleType}</h4>
            <span class="weekly-cycle-duration">${cycle.cycleDuration || 0} weeks</span>
          </div>
          <div class="weekly-schedule-blocks">
            ${blocksHTML}
          </div>
        </div>
      `;
    }).join('');
    
    return `
    <div class="weekly-schedule-container">
        ${weeklyScheduleHTML}
    </div>`;
  }

  private static generateCalendarChartScript(
    uniqueSubjects: string[], 
    subjectHours: Record<string, number>, 
    studyPlan: StudyPlan, 
    calendarData: any
  ): string {
    const chartColors = [
      '#2196F3', '#4CAF50', '#FF9800', '#F44336', '#9C27B0', 
      '#00BCD4', '#FF5722', '#795548', '#607D8B', '#E91E63'
    ];
    
    const subjectData = uniqueSubjects.map(subject => subjectHours[subject] || 0);
    const subjectColors = uniqueSubjects.map((_, index) => chartColors[index % chartColors.length]);
    
    // Generate timeline data for Gantt-like chart
    const cycles = studyPlan.cycles || [];
    const timelineLabels = cycles.map(cycle => cycle.cycleName || cycle.cycleType || 'Cycle');
    const timelineData = cycles.map((cycle, index) => ({
      x: cycle.cycleDuration || 0,
      y: index,
      label: cycle.cycleName || cycle.cycleType || 'Cycle'
    }));
    
    return `
      // Timeline Gantt Chart
      const timelineCtx = document.getElementById('timelineChart');
      if (timelineCtx) {
        new Chart(timelineCtx, {
          type: 'bar',
          data: {
            labels: ${JSON.stringify(timelineLabels)},
            datasets: [{
              label: 'Duration (Weeks)',
              data: ${JSON.stringify(cycles.map(cycle => cycle.cycleDuration || 0))},
              backgroundColor: ${JSON.stringify(cycles.map((_, index) => chartColors[index % chartColors.length]))},
              borderColor: ${JSON.stringify(cycles.map((_, index) => chartColors[index % chartColors.length]))},
              borderWidth: 1
            }]
          },
          options: {
            indexAxis: 'y',
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
              legend: { display: false },
              title: {
                display: true,
                text: 'Study Cycle Timeline'
              }
            },
            scales: {
              x: {
                beginAtZero: true,
                title: { display: true, text: 'Weeks' }
              },
              y: {
                title: { display: true, text: 'Cycles' }
              }
            }
          }
        });
      }
      
      // Subjects pie chart
      const subjectsCtx = document.getElementById('subjectsChart');
      if (subjectsCtx) {
        new Chart(subjectsCtx, {
          type: 'doughnut',
          data: {
            labels: ${JSON.stringify(uniqueSubjects)},
            datasets: [{
              data: ${JSON.stringify(subjectData)},
              backgroundColor: ${JSON.stringify(subjectColors)},
              borderWidth: 2,
              borderColor: '#ffffff'
            }]
          },
          options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
              legend: {
                position: 'right',
                labels: {
                  font: { family: 'Inter, sans-serif', size: 10 }
                }
              },
              title: {
                display: true,
                text: 'Subject Time Distribution'
              }
            }
          }
        });
      }
    `;
  }

  // ===== CALENDAR CSS GENERATION METHODS =====

  private static getCalendarStructuredCSS(): string {
    return `
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
      
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        text-rendering: optimizeLegibility;
      }
      
      body {
        font-family: 'Inter', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        font-size: 11px;
        line-height: 1.6;
        color: #1e293b;
        background: white;
        padding: 8px;
        margin: 0;
      }
      
      .calendar-header {
        text-align: center;
        margin-bottom: 25px;
        padding: 18px 0;
        border: 2px solid #2196F3;
        border-radius: 8px;
        background: linear-gradient(135deg, #E3F2FD 0%, #BBDEFB 100%);
      }
      
      .calendar-title {
        font-size: 22px;
        font-weight: 800;
        color: #0D47A1;
        margin-bottom: 8px;
        letter-spacing: -0.025em;
      }
      
      .calendar-subtitle {
        font-size: 13px;
        font-weight: 500;
        color: #1565C0;
        margin-bottom: 5px;
      }
      
      .calendar-student-info {
        font-size: 11px;
        font-weight: 400;
        color: #1976D2;
      }
      
      .calendar-overview-section {
        margin-bottom: 25px;
        padding: 15px;
        border: 1px solid #E3F2FD;
        border-radius: 6px;
        background-color: #FAFAFA;
      }
      
      .calendar-section-title {
        font-size: 16px;
        font-weight: 700;
        color: #0D47A1;
        margin-bottom: 12px;
        padding-bottom: 5px;
        border-bottom: 2px solid #2196F3;
      }
      
      .calendar-overview-grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 15px;
        margin-bottom: 15px;
      }
      
      .calendar-overview-card {
        background: white;
        border: 1px solid #E3F2FD;
        border-radius: 6px;
        padding: 12px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      }
      
      .calendar-overview-card h3 {
        color: #1565C0;
        font-weight: 600;
        margin-bottom: 10px;
        font-size: 12px;
      }
      
      .calendar-stat-item {
        display: flex;
        justify-content: space-between;
        margin-bottom: 5px;
        padding: 4px 0;
        border-bottom: 1px solid #F5F5F5;
      }
      
      .calendar-stat-label {
        font-weight: 500;
        color: #64748b;
        font-size: 10px;
      }
      
      .calendar-stat-value {
        font-weight: 600;
        color: #1e293b;
        font-size: 10px;
      }
      
      .calendar-overview-text {
        font-size: 11px;
        line-height: 1.6;
        color: #374151;
        text-align: justify;
      }
      
      .calendar-timeline-section {
        margin-bottom: 25px;
      }
      
      .timeline-container {
        position: relative;
        padding-left: 20px;
      }
      
      .timeline-item {
        position: relative;
        margin-bottom: 20px;
        padding-left: 25px;
        padding-bottom: 15px;
      }
      
      .timeline-marker {
        position: absolute;
        left: -8px;
        top: 5px;
        width: 12px;
        height: 12px;
        border-radius: 50%;
        border: 2px solid white;
        box-shadow: 0 0 0 2px #2196F3;
      }
      
      .timeline-content {
        background: white;
        border: 1px solid #E3F2FD;
        border-radius: 6px;
        padding: 12px;
      }
      
      .timeline-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 8px;
      }
      
      .timeline-header h4 {
        font-size: 13px;
        font-weight: 600;
        margin: 0;
      }
      
      .timeline-duration {
        background: #2196F3;
        color: white;
        padding: 2px 8px;
        border-radius: 12px;
        font-size: 9px;
        font-weight: 600;
      }
      
      .timeline-dates {
        font-size: 10px;
        color: #1976D2;
        font-weight: 500;
        margin-bottom: 5px;
      }
      
      .timeline-description {
        font-size: 10px;
        color: #4b5563;
        line-height: 1.4;
        margin-bottom: 5px;
      }
      
      .timeline-blocks {
        font-size: 9px;
        color: #6b7280;
        font-style: italic;
      }
      
      .calendar-profile-section {
        margin-bottom: 25px;
      }
      
      .calendar-profile-table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 15px;
        font-size: 10px;
      }
      
      .calendar-profile-table td {
        padding: 6px;
        border: 1px solid #E3F2FD;
        vertical-align: top;
      }
      
      .calendar-profile-label {
        font-weight: 600;
        color: #1565C0;
        background-color: #E3F2FD;
        width: 25%;
      }
      
      .calendar-profile-value {
        color: #1f2937;
        width: 25%;
      }
      
      .calendar-blocks-section {
        margin-bottom: 25px;
      }
      
      .calendar-cycle-container {
        margin-bottom: 20px;
        border-radius: 8px;
        overflow: hidden;
      }
      
      .calendar-cycle-header {
        padding: 12px 15px;
        color: white;
      }
      
      .calendar-cycle-header h3 {
        font-size: 14px;
        font-weight: 700;
        margin-bottom: 5px;
      }
      
      .calendar-cycle-duration {
        font-size: 11px;
        opacity: 0.9;
      }
      
      .calendar-cycle-description {
        padding: 10px 15px;
        font-size: 10px;
        color: #4b5563;
        background-color: #F8F9FA;
        border-bottom: 1px solid #E9ECEF;
      }
      
      .calendar-cycle-blocks {
        padding: 10px;
        background-color: white;
      }
      
      .calendar-block-item {
        margin-bottom: 12px;
        padding: 10px;
        border-radius: 6px;
        border: 1px solid #E9ECEF;
      }
      
      .calendar-block-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 8px;
      }
      
      .calendar-block-title {
        font-size: 12px;
        font-weight: 600;
        color: #1e293b;
      }
      
      .calendar-block-week {
        background: #6C757D;
        color: white;
        padding: 2px 8px;
        border-radius: 10px;
        font-size: 9px;
        font-weight: 600;
      }
      
      .calendar-block-dates,
      .calendar-block-duration,
      .calendar-block-subjects,
      .calendar-block-resources {
        font-size: 10px;
        margin-bottom: 3px;
        line-height: 1.4;
      }
      
      .calendar-block-dates { color: #1976D2; }
      .calendar-block-duration { color: #388E3C; }
      .calendar-block-subjects { color: #F57C00; }
      .calendar-block-resources { color: #7B1FA2; }
      
      .calendar-resources-section {
        margin-bottom: 25px;
      }
      
      .calendar-resources-intro {
        font-size: 11px;
        color: #374151;
        margin-bottom: 15px;
      }
      
      .calendar-resources-grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 12px;
      }
      
      .calendar-subject-resources {
        background-color: #F8F9FA;
        padding: 10px;
        border-radius: 6px;
        border-left: 3px solid #2196F3;
      }
      
      .calendar-subject-resources h4 {
        font-size: 11px;
        font-weight: 600;
        color: #0D47A1;
        margin-bottom: 8px;
      }
      
      .calendar-resource-item {
        font-size: 9px;
        color: #4b5563;
        margin-bottom: 2px;
        line-height: 1.3;
      }
      
      .calendar-footer {
        margin-top: 30px;
        padding: 12px 15px;
        background-color: #0D47A1;
        color: white;
        border-radius: 6px;
      }
      
      .calendar-footer-content {
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-size: 10px;
      }
      
      .calendar-footer-left { opacity: 0.9; }
      .calendar-footer-right { font-weight: 600; }
      
      @page {
        size: A4;
        margin: 15mm;
      }
      
      @media print {
        body { print-color-adjust: exact; }
        .calendar-cycle-container { page-break-inside: avoid; }
        .calendar-block-item { page-break-inside: avoid; }
      }
    </style>`;
  }

  private static getCalendarVisualCSS(): string {
    return `
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
      
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        text-rendering: optimizeLegibility;
      }
      
      body {
        font-family: 'Inter', sans-serif;
        font-size: 11px;
        line-height: 1.6;
        color: #1e293b;
        background: #f8fafc;
        padding: 8px;
        margin: 0;
      }
      
      .calendar-page {
        width: 210mm;
        min-height: 297mm;
        background: white;
        padding: 0;
      }
      
      .calendar-header {
        background: linear-gradient(135deg, #2196F3 0%, #1976D2 100%);
        color: white;
        padding: 25px 20px;
        text-align: center;
      }
      
      .calendar-header h1 {
        font-size: 2.2em;
        font-weight: 800;
        margin-bottom: 6px;
        letter-spacing: -0.02em;
      }
      
      .calendar-header .calendar-subtitle {
        font-size: 1.0em;
        font-weight: 300;
        opacity: 0.95;
      }
      
      .calendar-stats-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 10px;
        padding: 20px;
        margin-bottom: 15px;
      }
      
      .calendar-stat-card {
        background: white;
        border-radius: 8px;
        padding: 15px;
        text-align: center;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        border-left: 3px solid #2196F3;
      }
      
      .calendar-stat-card.primary { border-left-color: #2196F3; }
      .calendar-stat-card.secondary { border-left-color: #6C757D; }
      .calendar-stat-card.success { border-left-color: #4CAF50; }
      .calendar-stat-card.warning { border-left-color: #FF9800; }
      
      .stat-icon {
        font-size: 1.5em;
        margin-bottom: 5px;
      }
      
      .stat-number {
        font-size: 1.8em;
        font-weight: 800;
        color: #2196F3;
        margin-bottom: 3px;
      }
      
      .stat-label {
        font-size: 0.8em;
        color: #64748b;
        font-weight: 500;
      }
      
      .calendar-section {
        margin: 25px 20px;
      }
      
      .calendar-section-header {
        margin-bottom: 15px;
        padding-bottom: 8px;
        border-bottom: 2px solid #e2e8f0;
      }
      
      .calendar-section-title {
        font-size: 1.3em;
        font-weight: 700;
        color: #0f172a;
      }
      
      .calendar-charts-row {
        display: grid;
        grid-template-columns: 2fr 1fr;
        gap: 15px;
        margin-bottom: 15px;
      }
      
      .calendar-chart-container {
        background: white;
        border: 1px solid #e2e8f0;
        border-radius: 8px;
        padding: 15px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      }
      
      .calendar-chart-container h3 {
        color: #2196F3;
        font-weight: 600;
        margin-bottom: 12px;
        text-align: center;
        font-size: 1.0em;
      }
      
      .calendar-chart-container canvas {
        max-width: 100% !important;
      }
      
      .calendar-monthly-view {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 10px;
        margin-bottom: 20px;
      }
      
      .calendar-month {
        background: white;
        border: 1px solid #e2e8f0;
        border-radius: 6px;
        overflow: hidden;
      }
      
      .calendar-month-header {
        background: #2196F3;
        color: white;
        padding: 8px 10px;
        text-align: center;
      }
      
      .calendar-month-header h4 {
        font-size: 0.9em;
        font-weight: 600;
      }
      
      .calendar-month-events {
        padding: 8px;
        min-height: 80px;
      }
      
      .calendar-month-event {
        margin-bottom: 5px;
        padding: 4px 6px;
        border-radius: 4px;
        font-size: 0.8em;
      }
      
      .calendar-event-title {
        font-weight: 600;
        margin-bottom: 2px;
      }
      
      .calendar-event-duration {
        font-size: 0.7em;
        opacity: 0.8;
      }
      
      .calendar-no-events {
        font-size: 0.8em;
        color: #9ca3af;
        font-style: italic;
        text-align: center;
        padding: 20px 5px;
      }
      
      .weekly-schedule-container {
        display: grid;
        grid-template-columns: 1fr;
        gap: 15px;
      }
      
      .weekly-schedule-cycle {
        background: white;
        border: 1px solid #e2e8f0;
        border-radius: 8px;
        padding: 15px;
        margin-bottom: 10px;
      }
      
      .weekly-cycle-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 12px;
        padding-bottom: 8px;
        border-bottom: 1px solid #f1f5f9;
      }
      
      .weekly-cycle-header h4 {
        font-size: 1.1em;
        font-weight: 600;
        margin: 0;
      }
      
      .weekly-cycle-duration {
        background: #6C757D;
        color: white;
        padding: 3px 10px;
        border-radius: 12px;
        font-size: 0.8em;
        font-weight: 600;
      }
      
      .weekly-schedule-blocks {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 10px;
      }
      
      .weekly-schedule-block {
        padding: 10px;
        border-radius: 6px;
        border: 1px solid #e9ecef;
      }
      
      .weekly-block-week {
        background: #495057;
        color: white;
        padding: 2px 8px;
        border-radius: 10px;
        font-size: 0.7em;
        font-weight: 600;
        display: inline-block;
        margin-bottom: 5px;
      }
      
      .weekly-block-title {
        font-size: 0.9em;
        font-weight: 600;
        color: #1e293b;
        margin-bottom: 4px;
      }
      
      .weekly-block-subjects {
        font-size: 0.8em;
        color: #64748b;
        margin-bottom: 3px;
      }
      
      .weekly-block-duration {
        font-size: 0.8em;
        color: #059669;
        font-weight: 500;
      }
      
      .calendar-footer {
        background: #0f172a;
        color: white;
        padding: 15px 20px;
        margin-top: 25px;
      }
      
      .calendar-footer-content {
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-size: 0.85em;
      }
      
      .calendar-footer-left { opacity: 0.8; }
      .calendar-footer-right { font-weight: 600; }
      
      @page {
        size: A4;
        margin: 15mm;
      }
      
      @media print {
        body { print-color-adjust: exact; }
      }
    </style>`;
  }

  // ===== HELPER METHODS (matching original services) =====

  /**
   * Generate timeline data for calendar visualization
   */
  private static generateTimelineData(studyPlan: StudyPlan): any {
    const cycles = studyPlan.cycles || [];
    return cycles.map(cycle => ({
      name: cycle.cycleName || cycle.cycleType,
      startDate: cycle.cycleStartDate,
      endDate: cycle.cycleEndDate,
      duration: cycle.cycleDuration || 0,
      type: cycle.cycleType,
      blocks: cycle.cycleBlocks?.length || 0
    }));
  }

  /**
   * Generate calendar view data for monthly/weekly displays
   */
  private static generateCalendarViewData(studyPlan: StudyPlan): any {
    const cycles = studyPlan.cycles || [];
    const events: any[] = [];
    
    cycles.forEach(cycle => {
      if (cycle.cycleStartDate && cycle.cycleEndDate) {
        events.push({
          title: cycle.cycleName || cycle.cycleType,
          start: cycle.cycleStartDate,
          end: cycle.cycleEndDate,
          type: cycle.cycleType,
          duration: cycle.cycleDuration,
          blocks: cycle.cycleBlocks?.length || 0
        });
      }
    });
    
    return { events };
  }

  /**
   * Generate student profile data for table - enhanced to match DOCX version
   */
  private static generateStudentProfileData(studentIntake: StudentIntake): string[][] {
    const rows: string[][] = [];
    
    // Personal Details
    if (studentIntake.personal_details) {
      const pd = studentIntake.personal_details;
      rows.push([
        'Full Name', pd.full_name || 'Not provided',
        'Email', pd.email || 'Not provided'
      ]);
      rows.push([
        'Phone', pd.phone_number || 'Not provided',
        'Location', pd.present_location || 'Not provided'
      ]);
      rows.push([
        'Student Type', pd.student_archetype || 'Not provided',
        'Graduation Stream', pd.graduation_stream || 'Not provided'
      ]);
    }
    
    // Preparation Background
    if (studentIntake.preparation_background) {
      const pb = studentIntake.preparation_background;
      rows.push([
        'Preparing Since', pb.preparing_since || 'Not provided',
        'Number of Attempts', pb.number_of_attempts || 'Not provided'
      ]);
      rows.push([
        'Highest Stage Reached', pb.highest_stage_per_attempt || 'Not provided',
        'Previous Prelims Score', (pb.last_attempt_gs_prelims_score && pb.last_attempt_gs_prelims_score > 0) ? pb.last_attempt_gs_prelims_score.toString() : 'N/A'
      ]);
    }
    
    // Study Strategy
    if (studentIntake.study_strategy) {
      const ss = studentIntake.study_strategy;
      rows.push([
        'Weekly Study Hours', ss.weekly_study_hours || 'Not provided',
        'Study Approach', ss.study_approach || 'Not provided'
      ]);
      rows.push([
        'Focus Combination', ss.study_focus_combo || 'Not provided',
        'Time Distribution', ss.time_distribution || 'Balanced'
      ]);
    }
    
    // Target Year and Exam Details
    rows.push([
      'Target Year', studentIntake.target_year || 'Not provided',
      'Plan Start Date', studentIntake.start_date || 'Not provided'
    ]);
    
    return rows;
  }

  /**
   * Get cycle description based on cycle type
   */
  private static getCycleDescription(cycle: StudyCycle): string {
    const duration = cycle.cycleDuration || 0;
    const startDate = cycle.cycleStartDate || 'TBD';
    const endDate = cycle.cycleEndDate || 'TBD';
    
    switch (cycle.cycleType) {
      case CycleType.C1:
        return `📚 NCERT Foundation Phase: Building fundamental concepts through systematic NCERT study.`;
      case CycleType.C2:
        return `🏗️ Foundation Building Phase: Establishing solid conceptual foundation across all subjects.`;
      case CycleType.C3:
        return `📝 Mains Preparation Phase: Developing analytical thinking and answer writing skills.`;
      case CycleType.C4:
        return `📖 Prelims Reading Phase: Intensive reading and practice test preparation.`;
      case CycleType.C5:
        return `🔄 Prelims Revision Phase: Consolidating knowledge for Prelims examination.`;
      case CycleType.C5B:
        return `⚡ Prelims Final Sprint: Last-minute revision and high-yield topic focus.`;
      case CycleType.C6:
        return `✍️ Mains Revision Phase: Comprehensive Mains preparation with answer writing practice.`;
      case CycleType.C7:
        return `🎯 Mains Rapid Revision: Intensive post-Prelims Mains preparation.`;
      case CycleType.C8:
        return `📋 Mains Foundation Phase: Specialized Mains preparation with analytical focus.`;
      default:
        return `📅 Study Phase: Focused preparation designed to optimize learning outcomes.`;
    }
  }

  /**
   * Calculate block dates from cycle dates and block position
   */
  private static calculateBlockDates(_cycle: StudyCycle, block: Block, _blockIndex: number): { start: string; end: string } {
    return {
      start: block.block_start_date ? dayjs(block.block_start_date).format('MMM DD') : 'TBD',
      end: block.block_end_date ? dayjs(block.block_end_date).format('MMM DD') : 'TBD'
    };
  }

  /**
   * Summarize block resources for calendar display
   */
  private static summarizeBlockResources(blockResources?: BlockResources): string[] {
    if (!blockResources) {
      return ['No resources available'];
    }

    const resourceNames: string[] = [];
    
    // Collect all resource names
    if (blockResources.primary_books && blockResources.primary_books.length > 0) {
      blockResources.primary_books.forEach(book => {
        resourceNames.push(book.resource_title);
      });
    }
    
    if (blockResources.supplementary_materials && blockResources.supplementary_materials.length > 0) {
      blockResources.supplementary_materials.forEach(mat => {
        resourceNames.push(mat.resource_title);
      });
    }
    
    if (blockResources.current_affairs_sources && blockResources.current_affairs_sources.length > 0) {
      blockResources.current_affairs_sources.forEach(ca => {
        resourceNames.push(ca.resource_title);
      });
    }
    
    if (blockResources.practice_resources && blockResources.practice_resources.length > 0) {
      blockResources.practice_resources.forEach(practice => {
        resourceNames.push(practice.resource_title);
      });
    }
    
    if (blockResources.video_content && blockResources.video_content.length > 0) {
      blockResources.video_content.forEach(video => {
        resourceNames.push(video.resource_title);
      });
    }
    
    return resourceNames.length > 0 ? resourceNames : ['Resources available'];
  }

  /**
   * Get unique subjects from study plan
   */
  private static getUniqueSubjects(studyPlan: StudyPlan): string[] {
    const subjects = new Set<string>();
    studyPlan.cycles?.forEach(cycle => {
      cycle.cycleBlocks?.forEach(block => {
        block.subjects?.forEach(subject => subjects.add(subject));
      });
    });
    return Array.from(subjects);
  }

  /**
   * Get subject name from subject code
   */
  private static getSubjectName(subjectCode: string): string {
    const subject = SubjectLoader.getSubjectByCode(subjectCode);
    return subject?.subjectName || subjectCode;
  }

  /**
   * Calculate total weeks across all cycles
   */
  private static calculateTotalWeeks(studyPlan: StudyPlan): number {
    return studyPlan.cycles?.reduce((total, cycle) => total + (cycle.cycleDuration || 0), 0) || 0;
  }

  /**
   * Count total blocks across all cycles
   */
  private static countTotalBlocks(studyPlan: StudyPlan): number {
    return studyPlan.cycles?.reduce((total, cycle) => total + (cycle.cycleBlocks?.length || 0), 0) || 0;
  }

  /**
   * Calculate subject hours distribution
   */
  private static calculateSubjectHours(studyPlan: StudyPlan): Record<string, number> {
    const subjectHours: Record<string, number> = {};
    const uniqueSubjects = this.getUniqueSubjects(studyPlan);
    
    uniqueSubjects.forEach(subject => {
      let totalHours = 0;
      studyPlan.cycles?.forEach(cycle => {
        cycle.cycleBlocks?.forEach(block => {
          if (block.subjects?.includes(subject)) {
            const blockHours = (block.duration_weeks || 0) * 35;
            const subjectHours = blockHours / (block.subjects?.length || 1);
            totalHours += subjectHours;
          }
        });
      });
      subjectHours[subject] = Math.round(totalHours);
    });
    
    return subjectHours;
  }

  /**
   * Calculate duration string
   */
  private static calculateDuration(startDate: dayjs.Dayjs, targetYear: number): string {
    const targetDate = dayjs(`${targetYear}-05-19`);
    
    const years = targetDate.diff(startDate, 'year');
    const months = targetDate.diff(startDate, 'month') % 12;
    const weeks = Math.floor(targetDate.diff(startDate, 'day') % 30 / 7);
    
    const parts: string[] = [];
    
    if (years > 0) {
      parts.push(`${years} year${years !== 1 ? 's' : ''}`);
    }
    if (months > 0) {
      parts.push(`${months} month${months !== 1 ? 's' : ''}`);
    }
    if (weeks > 0) {
      parts.push(`${weeks} week${weeks !== 1 ? 's' : ''}`);
    }
    
    return parts.length > 0 ? parts.join(' ') : '0 days';
  }
}

export default CalendarPDFService;