import type { StudyPlan, StudyCycle, Block, BlockResources, StudentIntake } from '../types/models';
import { CycleType } from '../types/Types';
import { ResourceService } from './ResourceService';
import { SubjectLoader } from './SubjectLoader';
import dayjs from 'dayjs';
import puppeteer, { type PDFOptions, type Browser } from 'puppeteer';

// Calendar-specific color mapping for different cycle types
const CALENDAR_CYCLE_COLORS = {
  'C1': { bg: '#E3F2FD', border: '#2196F3', text: '#0D47A1' }, // Blue
  'C2': { bg: '#E8F5E8', border: '#4CAF50', text: '#1B5E20' }, // Green  
  'C3': { bg: '#FCE4EC', border: '#E91E63', text: '#880E4F' }, // Pink
  'C4': { bg: '#FFEBEE', border: '#F44336', text: '#B71C1C' }, // Red
  'C5': { bg: '#F3E5F5', border: '#9C27B0', text: '#4A148C' }, // Purple
  'C5.b': { bg: '#F3E5F5', border: '#9C27B0', text: '#4A148C' }, // Purple
  'C6': { bg: '#E1F5FE', border: '#00BCD4', text: '#006064' }, // Cyan
  'C7': { bg: '#FFF3E0', border: '#FF9800', text: '#E65100' }, // Orange
  'C8': { bg: '#F1F8E9', border: '#8BC34A', text: '#33691E' }, // Light Green
} as const;

// Interface for calendar events
interface CalendarEvent {
  title: string;
  startDate: dayjs.Dayjs;
  endDate: dayjs.Dayjs;
  type: 'cycle' | 'block';
  cycleType?: string;
  color: {
    bg: string;
    border: string;
    text: string;
  };
  subjects: string[];
  duration?: number;
}

/**
 * Calendar-focused PDF generation service using Puppeteer
 * Specialized for calendar views, timeline visualizations, and schedule-based PDFs
 * Maintains the same interface as PDFService and HighFidelityPDFService for easy swapping
 */
export class CalendarPDFService {
  
  /**
   * Generate structured PDF with calendar-focused layout
   * Emphasizes timeline, scheduling, and calendar views
   */
  public static async generateStructuredPDF(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    filename?: string
  ): Promise<void> {
    try {
      // Create calendar-optimized HTML template
      const htmlContent = await this.createCalendarStructuredHTML(studyPlan, studentIntake);
      
      // Generate PDF using Puppeteer with calendar-specific settings
      const pdfBuffer = await this.generatePDFFromHTML(htmlContent, {
        format: 'A4',
        printBackground: true,
        margin: { top: '15px', right: '20px', bottom: '15px', left: '20px' },
        preferCSSPageSize: false,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `
          <div style="font-size: 10px; text-align: center; width: 100%; color: #666; margin: 0 15px;">
            <span class="title"></span> - Generated by Helios Calendar Planner on ${new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })} - Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </div>
        `
      });
      
      // Save the PDF
      await this.savePDF(pdfBuffer, filename || `calendar-study-plan-${studyPlan.study_plan_id || 'plan'}.pdf`);
      
    } catch (error) {
      console.error('Failed to generate calendar structured PDF:', error);
      throw new Error('Calendar structured PDF generation failed');
    }
  }

  /**
   * Generate visual PDF with calendar charts and timeline visualizations
   * Specialized for calendar views and scheduling presentations
   */
  static async generateVisualPDF(
    studyPlan: StudyPlan,
    studentIntake: StudentIntake,
    filename?: string
  ): Promise<void> {
    try {
      // Create calendar-focused visual HTML template
      const htmlContent = await this.createCalendarVisualHTML(studyPlan, studentIntake);
      
      // Generate PDF using Puppeteer with enhanced visual settings
      const pdfBuffer = await this.generatePDFFromHTML(htmlContent, {
        format: 'A4',
        printBackground: true,
        margin: { top: '15px', right: '20px', bottom: '15px', left: '20px' },
        preferCSSPageSize: false,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `
          <div style="font-size: 10px; text-align: center; width: 100%; color: #666; margin: 0 15px;">
            Generated by Helios Calendar Planner on ${new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })} - Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </div>
        `
      });
      
      // Save the PDF
      await this.savePDF(pdfBuffer, filename || `calendar-visual-study-plan-${studyPlan.study_plan_id || 'plan'}.pdf`);
      
    } catch (error) {
      console.error('Failed to generate calendar visual PDF:', error);
      throw new Error('Calendar visual PDF generation failed');
    }
  }

  /**
   * Main entry point - defaults to structured PDF (recommended)
   * Matches the exact interface of the original PDFService and HighFidelityPDFService
   */
  static async generateStudyPlanPDF(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    options?: {
      filename?: string;
      type?: 'structured' | 'visual';
    }
  ): Promise<void> {
    const type = options?.type || 'structured';
    
    if (type === 'visual') {
      return this.generateVisualPDF(studyPlan, studentIntake, options?.filename);
    } else {
      return this.generateStructuredPDF(studyPlan, studentIntake, options?.filename);
    }
  }

  // ===== CORE PDF GENERATION METHODS =====

  /**
   * Generate PDF from HTML using Puppeteer with calendar-optimized settings
   */
  private static async generatePDFFromHTML(htmlContent: string, options: PDFOptions): Promise<Buffer> {
    let browser: Browser | null = null;
    
    try {
      // Launch browser with optimized settings for calendar PDF generation
      browser = await puppeteer.launch({
        headless: true,
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--disable-gpu',
          '--disable-web-security',
          '--disable-features=VizDisplayCompositor',
          '--run-all-compositor-stages-before-draw',
          '--disable-extensions-http-throttling'
        ],
        // Use system Chrome if available for better font rendering
        executablePath: process.env.CHROME_PATH || undefined
      });

      const page = await browser.newPage();
      
      // Set viewport for consistent calendar rendering
      await page.setViewport({ width: 1200, height: 1600, deviceScaleFactor: 2 });
      
      // Enable better font rendering for calendar elements
      await page.evaluateOnNewDocument(() => {
        // Improve text rendering for calendar dates and schedules
        const style = document.createElement('style');
        style.innerHTML = `
          * {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            text-rendering: optimizeLegibility;
          }
          .calendar-date, .schedule-time {
            font-variant-numeric: tabular-nums;
          }
        `;
        document.head.appendChild(style);
      });

      // Set content with proper encoding
      await page.setContent(htmlContent, {
        waitUntil: ['networkidle0', 'domcontentloaded'],
        timeout: 30000
      });

      // Wait for calendar charts and dynamic content to load
      await new Promise(resolve => setTimeout(resolve, 3000));

      // Generate PDF with high-quality settings
      const pdfBuffer = await page.pdf({
        ...options,
        preferCSSPageSize: false,
        printBackground: true
      });

      return Buffer.from(pdfBuffer);
    } finally {
      if (browser) {
        await browser.close();
      }
    }
  }

  /**
   * Save PDF to appropriate location (filesystem or browser download)
   */
  private static async savePDF(pdfBuffer: Buffer, filename: string): Promise<void> {
    if (typeof window !== 'undefined') {
      // Browser environment - trigger download
      const blob = new Blob([new Uint8Array(pdfBuffer)], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
      console.log(`📁 Calendar PDF download triggered: ${filename}`);
    } else {
      // Node.js environment - save to filesystem
      const fs = await import('fs');
      const path = await import('path');
      
      const outputDir = path.join(process.cwd(), 'generated-docs');
      
      // Ensure output directory exists
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }
      
      const outputPath = path.join(outputDir, filename);
      fs.writeFileSync(outputPath, pdfBuffer);
      
      console.log(`✅ Calendar PDF saved: ${filename}`);
      console.log(`   📁 Location: ${outputPath}`);
    }
  }

  // ===== CALENDAR HTML TEMPLATE GENERATION METHODS =====

  /**
   * Create calendar-structured HTML template optimized for scheduling and timeline views
   */
  private static async createCalendarStructuredHTML(studyPlan: StudyPlan, studentIntake: StudentIntake): Promise<string> {
    const totalWeeks = this.calculateTotalWeeks(studyPlan);
    const totalBlocks = this.countTotalBlocks(studyPlan);
    const uniqueSubjects = this.getUniqueSubjects(studyPlan);
    const timelineData = this.generateTimelineData(studyPlan);
    
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${studyPlan.plan_title || 'Calendar Study Plan'}</title>
        ${this.getCalendarStructuredCSS()}
    </head>
    <body>
        ${this.generateCalendarHeaderSection(studyPlan, studentIntake)}
        ${this.generateCalendarOverviewSection(studyPlan, studentIntake, totalWeeks, totalBlocks)}
        ${this.generateTimelineSection(studyPlan, timelineData)}
        ${this.generateStudentProfileSection(studentIntake)}
        ${this.generateCalendarBlocksSection(studyPlan)}
        ${await this.generateResourcesSection(studyPlan, uniqueSubjects)}
        ${this.generateCalendarFooter()}
    </body>
    </html>`;
  }

  /**
   * Create calendar-visual HTML template with interactive calendar views and charts
   */
  private static async createCalendarVisualHTML(studyPlan: StudyPlan, studentIntake: StudentIntake): Promise<string> {
    const totalWeeks = this.calculateTotalWeeks(studyPlan);
    const totalBlocks = this.countTotalBlocks(studyPlan);
    const uniqueSubjects = this.getUniqueSubjects(studyPlan);
    const subjectHours = this.calculateSubjectHours(studyPlan);
    const calendarData = this.generateCalendarViewData(studyPlan);
    
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${studyPlan.plan_title || 'Calendar Study Plan'}</title>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns"></script>
        ${this.getCalendarVisualCSS()}
    </head>
    <body>
        <div class="calendar-page">
            <!-- Calendar Header -->
            <div class="calendar-header">
                <h1>${studyPlan.plan_title || 'Calendar Study Plan'}</h1>
                <div class="calendar-subtitle">
                    Strategic UPSC ${studyPlan.targeted_year || '2025'} Calendar & Timeline
                </div>
            </div>
            
            <!-- Calendar Stats Dashboard -->
            <div class="calendar-stats-grid">
                <div class="calendar-stat-card primary">
                    <div class="stat-icon">📅</div>
                    <div class="stat-number">${totalWeeks}</div>
                    <div class="stat-label">Total Weeks</div>
                </div>
                <div class="calendar-stat-card secondary">
                    <div class="stat-icon">🔄</div>
                    <div class="stat-number">${studyPlan.cycles?.length || 0}</div>
                    <div class="stat-label">Study Cycles</div>
                </div>
                <div class="calendar-stat-card success">
                    <div class="stat-icon">📚</div>
                    <div class="stat-number">${totalBlocks}</div>
                    <div class="stat-label">Study Blocks</div>
                </div>
                <div class="calendar-stat-card warning">
                    <div class="stat-icon">🎯</div>
                    <div class="stat-number">${uniqueSubjects.length}</div>
                    <div class="stat-label">Subjects</div>
                </div>
            </div>
            
            <!-- Calendar Timeline Visualization -->
            <div class="calendar-section">
                <div class="calendar-section-header">
                    <h2 class="calendar-section-title">📊 Study Plan Timeline</h2>
                </div>
                
                <div class="calendar-charts-row">
                    <div class="calendar-chart-container">
                        <h3>Cycle Timeline (Gantt View)</h3>
                        <canvas id="timelineChart" width="800" height="300"></canvas>
                    </div>
                    
                    <div class="calendar-chart-container">
                        <h3>Subject Distribution</h3>
                        <canvas id="subjectsChart" width="400" height="300"></canvas>
                    </div>
                </div>
            </div>
            
            <!-- Monthly Calendar View -->
            <div class="calendar-section">
                <div class="calendar-section-header">
                    <h2 class="calendar-section-title">🗓️ Monthly Calendar View</h2>
                </div>
                
                ${this.generateMonthlyCalendarView(studyPlan, calendarData)}
            </div>
            
            <!-- Weekly Schedule View -->
            <div class="calendar-section">
                <div class="calendar-section-header">
                    <h2 class="calendar-section-title">📋 Weekly Schedule Overview</h2>
                </div>
                
                ${this.generateWeeklyScheduleView(studyPlan)}
            </div>
            
            <!-- Calendar Footer -->
            <div class="calendar-footer">
                <div class="calendar-footer-content">
                    <div class="calendar-footer-left">
                        Generated on ${dayjs().format('MMMM DD, YYYY')} | Helios Calendar Planner
                    </div>
                    <div class="calendar-footer-right">
                        Your Scheduled Path to Success
                    </div>
                </div>
            </div>
        </div>
        
        <script>
          // Initialize calendar charts after page load
          document.addEventListener('DOMContentLoaded', function() {
            setTimeout(() => {
              ${this.generateCalendarChartScript(uniqueSubjects, subjectHours, studyPlan, calendarData)}
            }, 200);
          });
        </script>
    </body>
    </html>`;
  }

  // ===== CALENDAR SECTION GENERATION METHODS =====

  private static generateCalendarHeaderSection(studyPlan: StudyPlan, studentIntake: StudentIntake): string {
    const startDate = dayjs(studentIntake.start_date);
    const targetYear = studyPlan.targeted_year || new Date().getFullYear() + 1;
    const planDuration = this.calculateDuration(startDate, targetYear);
    
    return `
    <div class="calendar-header">
        <h1 class="calendar-title">${studyPlan.plan_title || 'Calendar Study Plan'}</h1>
        <div class="calendar-subtitle">
            📅 Start Date: ${startDate.format('DD/MM/YYYY')} | 
            🎯 Target Year: ${targetYear} | 
            ⏱️ Duration: ${planDuration}
        </div>
        <div class="calendar-student-info">
            👤 Student: ${studentIntake.personal_details?.full_name || 'Student'} | 
            📧 ${studentIntake.personal_details?.email || 'N/A'}
        </div>
    </div>`;
  }

  private static generateCalendarOverviewSection(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    totalWeeks: number, 
    totalBlocks: number
  ): string {
    const cycles = studyPlan.cycles || [];
    const targetYear = studyPlan.targeted_year || new Date().getFullYear() + 1;
    const studentName = studentIntake.personal_details?.full_name || 'you';
    
    return `
    <div class="calendar-overview-section">
        <h2 class="calendar-section-title">📋 Calendar Overview</h2>
        
        <div class="calendar-overview-grid">
            <div class="calendar-overview-card">
                <h3>📊 Plan Statistics</h3>
                <div class="calendar-stats">
                    <div class="calendar-stat-item">
                        <span class="calendar-stat-label">Total Duration:</span>
                        <span class="calendar-stat-value">${totalWeeks} weeks</span>
                    </div>
                    <div class="calendar-stat-item">
                        <span class="calendar-stat-label">Study Cycles:</span>
                        <span class="calendar-stat-value">${cycles.length}</span>
                    </div>
                    <div class="calendar-stat-item">
                        <span class="calendar-stat-label">Study Blocks:</span>
                        <span class="calendar-stat-value">${totalBlocks}</span>
                    </div>
                </div>
            </div>
            
            <div class="calendar-overview-card">
                <h3>🎯 Target Information</h3>
                <div class="calendar-stats">
                    <div class="calendar-stat-item">
                        <span class="calendar-stat-label">Target Year:</span>
                        <span class="calendar-stat-value">${targetYear}</span>
                    </div>
                    <div class="calendar-stat-item">
                        <span class="calendar-stat-label">Student:</span>
                        <span class="calendar-stat-value">${studentName}</span>
                    </div>
                    <div class="calendar-stat-item">
                        <span class="calendar-stat-label">Generated:</span>
                        <span class="calendar-stat-value">${dayjs().format('MMM DD, YYYY')}</span>
                    </div>
                </div>
            </div>
        </div>
        
        <p class="calendar-overview-text">
            This calendar-based study plan is strategically designed for ${studentName} 
            for UPSC ${targetYear} preparation, organized across ${cycles.length} specialized 
            cycles spanning ${totalWeeks} weeks with ${totalBlocks} focused study blocks.
        </p>
    </div>`;
  }

  private static generateTimelineSection(studyPlan: StudyPlan, timelineData: any): string {
    const cycles = studyPlan.cycles || [];
    
    const timelineItems = cycles.map((cycle, index) => {
      const cycleColor = CALENDAR_CYCLE_COLORS[cycle.cycleType as keyof typeof CALENDAR_CYCLE_COLORS] || 
                        { bg: '#F5F5F5', border: '#9E9E9E', text: '#424242' };
      
      const startDate = cycle.cycleStartDate ? dayjs(cycle.cycleStartDate).format('MMM DD') : 'TBD';
      const endDate = cycle.cycleEndDate ? dayjs(cycle.cycleEndDate).format('MMM DD') : 'TBD';
      const duration = cycle.cycleDuration || 0;
      
      return `
        <div class="timeline-item" style="border-left: 4px solid ${cycleColor.border};">
          <div class="timeline-marker" style="background-color: ${cycleColor.border};"></div>
          <div class="timeline-content">
            <div class="timeline-header">
              <h4 style="color: ${cycleColor.text};">${cycle.cycleName || cycle.cycleType}</h4>
              <span class="timeline-duration">${duration} weeks</span>
            </div>
            <div class="timeline-dates">${startDate} - ${endDate}</div>
            <div class="timeline-description">${this.getCycleDescription(cycle)}</div>
            <div class="timeline-blocks">
              ${(cycle.cycleBlocks || []).length} study blocks
            </div>
          </div>
        </div>
      `;
    }).join('');
    
    return `
    <div class="calendar-timeline-section">
        <h2 class="calendar-section-title">⏰ Study Plan Timeline</h2>
        <div class="timeline-container">
            ${timelineItems}
        </div>
    </div>`;
  }

  private static generateStudentProfileSection(studentIntake: StudentIntake): string {
    const profileData = this.generateStudentProfileData(studentIntake);
    
    const profileRows = profileData.map(row => `
      <tr>
        <td class="calendar-profile-label">${row[0]}</td>
        <td class="calendar-profile-value">${row[1]}</td>
        <td class="calendar-profile-label">${row[2] || ''}</td>
        <td class="calendar-profile-value">${row[3] || ''}</td>
      </tr>
    `).join('');
    
    return `
    <div class="calendar-profile-section">
        <h2 class="calendar-section-title">👤 Student Profile</h2>
        
        <table class="calendar-profile-table">
            ${profileRows}
        </table>
    </div>`;
  }

  private static generateCalendarBlocksSection(studyPlan: StudyPlan): string {
    if (!studyPlan.cycles) return '';
    
    const cyclesHTML = studyPlan.cycles.map(cycle => this.generateCalendarCycleHTML(cycle)).join('');
    
    return `
    <div class="calendar-blocks-section">
        <h2 class="calendar-section-title">📚 Study Blocks Calendar</h2>
        ${cyclesHTML}
    </div>`;
  }

  private static generateCalendarCycleHTML(cycle: StudyCycle): string {
    const cycleName = cycle.cycleName || 'Untitled Cycle';
    const cycleDescription = this.getCycleDescription(cycle);
    const durationText = `📅 ${cycle.cycleStartDate || 'TBD'} to ${cycle.cycleEndDate || 'TBD'} (${cycle.cycleDuration || 0} weeks)`;
    
    const cycleColor = CALENDAR_CYCLE_COLORS[cycle.cycleType as keyof typeof CALENDAR_CYCLE_COLORS] || 
                     { bg: '#F5F5F5', border: '#9E9E9E', text: '#424242' };
    
    const blocksHTML = (cycle.cycleBlocks || []).map((block, index) => {
      const blockDates = this.calculateBlockDates(cycle, block, index);
      const weekNumber = index + 1;
      const resourceSummary = this.summarizeBlockResources(block.block_resources);
      
      return `
        <div class="calendar-block-item" style="background-color: ${cycleColor.bg}; border-left: 3px solid ${cycleColor.border};">
          <div class="calendar-block-header">
            <div class="calendar-block-title">${block.block_title || 'Untitled Block'}</div>
            <div class="calendar-block-week">Week ${weekNumber}</div>
          </div>
          <div class="calendar-block-dates">
            📅 ${blockDates.start} - ${blockDates.end}
          </div>
          <div class="calendar-block-duration">
            ⏱️ ${block.duration_weeks || 0} week(s)
          </div>
          <div class="calendar-block-subjects">
            🎯 ${block.subjects?.join(', ') || 'No subjects'}
          </div>
          <div class="calendar-block-resources">
            📚 ${resourceSummary.slice(0, 3).join(', ')}${resourceSummary.length > 3 ? '...' : ''}
          </div>
        </div>
      `;
    }).join('');
    
    return `
    <div class="calendar-cycle-container" style="border: 2px solid ${cycleColor.border};">
        <div class="calendar-cycle-header" style="background: linear-gradient(135deg, ${cycleColor.border}, ${cycleColor.bg}); color: ${cycleColor.text};">
            <h3>${cycleName}</h3>
            <div class="calendar-cycle-duration">${durationText}</div>
        </div>
        <div class="calendar-cycle-description">${cycleDescription}</div>
        <div class="calendar-cycle-blocks">
            ${blocksHTML}
        </div>
    </div>`;
  }

  private static async generateResourcesSection(studyPlan: StudyPlan, uniqueSubjects: string[]): Promise<string> {
    let resourcesHTML = '';
    
    for (const subjectCode of uniqueSubjects.slice(0, 8)) { // Limit for calendar view
      try {
        const subjectName = this.getSubjectName(subjectCode);
        const resources = await ResourceService.getResourcesForSubject(subjectCode);
        
        const resourceNames: string[] = [];
        
        if (resources.primary_books && resources.primary_books.length > 0) {
          resources.primary_books.slice(0, 3).forEach(book => {
            resourceNames.push(`📖 ${book.resource_title}`);
          });
        }
        
        if (resources.current_affairs_sources && resources.current_affairs_sources.length > 0) {
          resources.current_affairs_sources.slice(0, 2).forEach(ca => {
            resourceNames.push(`📰 ${ca.resource_title}`);
          });
        }
        
        if (resources.practice_resources && resources.practice_resources.length > 0) {
          resources.practice_resources.slice(0, 2).forEach(practice => {
            resourceNames.push(`✏️ ${practice.resource_title}`);
          });
        }
        
        resourcesHTML += `
        <div class="calendar-subject-resources">
            <h4>${subjectName}</h4>
            <div class="calendar-resource-list">
              ${resourceNames.slice(0, 5).map(resource => `<div class="calendar-resource-item">${resource}</div>`).join('')}
              ${resourceNames.length > 5 ? `<div class="calendar-resource-more">+${resourceNames.length - 5} more resources</div>` : ''}
            </div>
        </div>`;
        
      } catch (error) {
        console.warn(`Failed to load resources for ${subjectCode}`, error);
        const subjectName = this.getSubjectName(subjectCode);
        resourcesHTML += `
        <div class="calendar-subject-resources">
            <h4>${subjectName}</h4>
            <div class="calendar-resource-list">
              <div class="calendar-resource-item">📚 Comprehensive resources available</div>
            </div>
        </div>`;
      }
    }
    
    return `
    <div class="calendar-resources-section">
        <h2 class="calendar-section-title">📚 Study Resources</h2>
        
        <p class="calendar-resources-intro">
            Key study resources organized by subject for your calendar-based study plan:
        </p>
        
        <div class="calendar-resources-grid">
            ${resourcesHTML}
        </div>
    </div>`;
  }

  private static generateCalendarFooter(): string {
    return `
    <div class="calendar-footer">
        <div class="calendar-footer-content">
            <div class="calendar-footer-left">
                Generated on ${dayjs().format('MMMM DD, YYYY')} | Helios Calendar Planner
            </div>
            <div class="calendar-footer-right">
                📅 Your Scheduled Path to Success
            </div>
        </div>
    </div>`;
  }

  // ===== ACTUAL CALENDAR GENERATION METHODS =====

  /**
   * Map study plan cycles and blocks to calendar events with actual dates
   */
  private static mapStudyPlanToCalendarEvents(studyPlan: StudyPlan): CalendarEvent[] {
    const events: CalendarEvent[] = [];
    const cycles = studyPlan.cycles || [];
    
    cycles.forEach(cycle => {
      if (cycle.cycleStartDate && cycle.cycleEndDate) {
        // Add cycle as an event
        events.push({
          title: cycle.cycleName || cycle.cycleType || 'Study Cycle',
          startDate: dayjs(cycle.cycleStartDate),
          endDate: dayjs(cycle.cycleEndDate),
          type: 'cycle',
          cycleType: cycle.cycleType,
          color: CALENDAR_CYCLE_COLORS[cycle.cycleType as keyof typeof CALENDAR_CYCLE_COLORS] || 
                 { bg: '#F5F5F5', border: '#9E9E9E', text: '#424242' },
          subjects: this.getUniqueSubjectsFromCycle(cycle.cycleBlocks)
        });
        
        // Add individual blocks as events
        cycle.cycleBlocks?.forEach(block => {
          if (block.block_start_date && block.block_end_date) {
            events.push({
              title: block.block_title || 'Study Block',
              startDate: dayjs(block.block_start_date),
              endDate: dayjs(block.block_end_date),
              type: 'block',
              cycleType: cycle.cycleType,
              color: CALENDAR_CYCLE_COLORS[cycle.cycleType as keyof typeof CALENDAR_CYCLE_COLORS] || 
                     { bg: '#F5F5F5', border: '#9E9E9E', text: '#424242' },
              subjects: block.subjects || [],
              duration: block.duration_weeks || 1
            });
          }
        });
      }
    });
    
    return events.sort((a, b) => a.startDate.valueOf() - b.startDate.valueOf());
  }

  /**
   * Generate actual monthly calendar grids with date cells
   */
  private static generateMonthlyCalendarGrids(studyPlan: StudyPlan, events: CalendarEvent[]): string {
    const startDate = dayjs(studyPlan.cycles?.[0]?.cycleStartDate || new Date());
    const endDate = dayjs(studyPlan.cycles?.[studyPlan.cycles.length - 1]?.cycleEndDate || new Date().setFullYear(new Date().getFullYear() + 1));
    
    const months: string[] = [];
    let currentMonth = startDate.startOf('month');
    
    while (currentMonth.isBefore(endDate) || currentMonth.isSame(endDate, 'month')) {
      months.push(this.generateSingleMonthCalendar(currentMonth, events));
      currentMonth = currentMonth.add(1, 'month');
    }
    
    return months.join('');
  }

  /**
   * Generate a single month calendar grid with actual dates
   */
  private static generateSingleMonthCalendar(month: dayjs.Dayjs, events: CalendarEvent[]): string {
    const monthName = month.format('MMMM YYYY');
    const firstDay = month.startOf('month');
    const lastDay = month.endOf('month');
    const startCalendar = firstDay.startOf('week'); // Start from Sunday
    const endCalendar = lastDay.endOf('week'); // End on Saturday
    
    // Generate calendar header
    const weekDays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    const headerHTML = weekDays.map(day => 
      `<div class="calendar-day-header">${day}</div>`
    ).join('');
    
    // Generate calendar days
    const daysHTML: string[] = [];
    let currentDay = startCalendar;
    
    while (currentDay.isBefore(endCalendar) || currentDay.isSame(endCalendar, 'day')) {
      const isCurrentMonth = currentDay.isSame(month, 'month');
      const dayEvents = events.filter(event => 
        currentDay.isBetween(event.startDate, event.endDate, 'day', '[]')
      );
      
      const dayClass = [
        'calendar-day',
        isCurrentMonth ? 'current-month' : 'other-month',
        dayEvents.length > 0 ? 'has-events' : '',
        currentDay.isSame(dayjs(), 'day') ? 'today' : ''
      ].filter(Boolean).join(' ');
      
      const eventsHTML = dayEvents.slice(0, 3).map(event => 
        `<div class="calendar-event" style="background-color: ${event.color.bg}; border-left: 2px solid ${event.color.border};">
          <span class="event-title">${event.title}</span>
          ${event.subjects.length > 0 ? `<span class="event-subjects">${event.subjects.slice(0, 2).join(', ')}</span>` : ''}
        </div>`
      ).join('');
      
      const moreEventsHTML = dayEvents.length > 3 ? 
        `<div class="more-events">+${dayEvents.length - 3} more</div>` : '';
      
      daysHTML.push(`
        <div class="${dayClass}">
          <div class="calendar-date-number">${currentDay.date()}</div>
          <div class="calendar-events">
            ${eventsHTML}
            ${moreEventsHTML}
          </div>
        </div>
      `);
      
      currentDay = currentDay.add(1, 'day');
    }
    
    return `
    <div class="monthly-calendar">
      <div class="calendar-month-title">
        <h2>${monthName}</h2>
      </div>
      <div class="calendar-grid">
        <div class="calendar-header-row">
          ${headerHTML}
        </div>
        <div class="calendar-days-grid">
          ${daysHTML.join('')}
        </div>
      </div>
    </div>`;
  }

  /**
   * Generate weekly calendar view with time slots
   */
  private static generateWeeklyCalendarView(studyPlan: StudyPlan, events: CalendarEvent[]): string {
    const startDate = dayjs(studyPlan.cycles?.[0]?.cycleStartDate || new Date());
    const endDate = dayjs(studyPlan.cycles?.[studyPlan.cycles.length - 1]?.cycleEndDate || new Date().setFullYear(new Date().getFullYear() + 1));
    
    const weeks: string[] = [];
    let currentWeek = startDate.startOf('week');
    let weekCount = 0;
    
    while (currentWeek.isBefore(endDate) && weekCount < 12) { // Limit to 12 weeks for PDF
      weeks.push(this.generateSingleWeekView(currentWeek, events, weekCount + 1));
      currentWeek = currentWeek.add(1, 'week');
      weekCount++;
    }
    
    return `<div class="weekly-calendars">${weeks.join('')}</div>`;
  }

  /**
   * Generate a single week view with daily schedule
   */
  private static generateSingleWeekView(weekStart: dayjs.Dayjs, events: CalendarEvent[], weekNumber: number): string {
    const weekEnd = weekStart.endOf('week');
    const weekDays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    
    const daysHTML = weekDays.map((dayName, index) => {
      const currentDay = weekStart.add(index, 'day');
      const dayEvents = events.filter(event => 
        currentDay.isBetween(event.startDate, event.endDate, 'day', '[]')
      );
      
      const eventsHTML = dayEvents.map(event => 
        `<div class="week-event" style="background-color: ${event.color.bg}; border-left: 3px solid ${event.color.border};">
          <div class="week-event-title">${event.title}</div>
          <div class="week-event-subjects">${event.subjects.slice(0, 3).join(', ')}</div>
        </div>`
      ).join('');
      
      return `
        <div class="week-day">
          <div class="week-day-header">
            <div class="week-day-name">${dayName}</div>
            <div class="week-day-date">${currentDay.format('MMM DD')}</div>
          </div>
          <div class="week-day-events">
            ${eventsHTML || '<div class="no-events">No study sessions</div>'}
          </div>
        </div>
      `;
    }).join('');
    
    return `
    <div class="weekly-calendar">
      <div class="week-header">
        <h3>Week ${weekNumber}: ${weekStart.format('MMM DD')} - ${weekEnd.format('MMM DD, YYYY')}</h3>
      </div>
      <div class="week-grid">
        ${daysHTML}
      </div>
    </div>`;
  }

  /**
   * Generate calendar legend for cycle types
   */
  private static generateCalendarLegend(): string {
    const legendItems = Object.entries(CALENDAR_CYCLE_COLORS).map(([cycleType, colors]) => 
      `<div class="legend-item">
        <div class="legend-color" style="background-color: ${colors.bg}; border-left: 4px solid ${colors.border};"></div>
        <span class="legend-label">${this.getCycleTypeName(cycleType)}</span>
      </div>`
    ).join('');
    
    return legendItems;
  }

  /**
   * Get human-readable cycle type name
   */
  private static getCycleTypeName(cycleType: string): string {
    const names: Record<string, string> = {
      'C1': 'NCERT Foundation',
      'C2': 'Foundation Building', 
      'C3': 'Mains Preparation',
      'C4': 'Prelims Reading',
      'C5': 'Prelims Revision',
      'C5.b': 'Prelims Final Sprint',
      'C6': 'Mains Revision',
      'C7': 'Mains Rapid Revision',
      'C8': 'Mains Foundation'
    };
    return names[cycleType] || cycleType;
  }

  /**
   * Generate study block summary table
   */
  private static generateStudyBlockSummary(studyPlan: StudyPlan): string {
    const cycles = studyPlan.cycles || [];
    
    const summaryRows = cycles.map(cycle => {
      const cycleColor = CALENDAR_CYCLE_COLORS[cycle.cycleType as keyof typeof CALENDAR_CYCLE_COLORS] || 
                        { bg: '#F5F5F5', border: '#9E9E9E', text: '#424242' };
      
      const blocksCount = cycle.cycleBlocks?.length || 0;
      const subjects = this.getUniqueSubjectsFromCycle(cycle.cycleBlocks);
      
      return `
        <tr style="background-color: ${cycleColor.bg};">
          <td style="border-left: 4px solid ${cycleColor.border}; font-weight: 600;">
            ${cycle.cycleName || cycle.cycleType}
          </td>
          <td>${cycle.cycleStartDate ? dayjs(cycle.cycleStartDate).format('MMM DD, YYYY') : 'TBD'}</td>
          <td>${cycle.cycleEndDate ? dayjs(cycle.cycleEndDate).format('MMM DD, YYYY') : 'TBD'}</td>
          <td>${cycle.cycleDuration || 0} weeks</td>
          <td>${blocksCount} blocks</td>
          <td>${subjects.join(', ')}</td>
        </tr>
      `;
    }).join('');
    
    return `
    <table class="summary-table">
      <thead>
        <tr>
          <th>Cycle</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th>Duration</th>
          <th>Blocks</th>
          <th>Subjects</th>
        </tr>
      </thead>
      <tbody>
        ${summaryRows}
      </tbody>
    </table>`;
  }

  /**
   * Get unique subjects from cycle blocks
   */
  private static getUniqueSubjectsFromCycle(cycleBlocks?: Block[]): string[] {
    const subjects = new Set<string>();
    cycleBlocks?.forEach(block => {
      if (block.subjects) {
        block.subjects.forEach(subject => subjects.add(subject));
      }
    });
    return Array.from(subjects);
  }

  private static generateCalendarChartScript(
    uniqueSubjects: string[], 
    subjectHours: Record<string, number>, 
    studyPlan: StudyPlan, 
    calendarData: any
  ): string {
    const chartColors = [
      '#2196F3', '#4CAF50', '#FF9800', '#F44336', '#9C27B0', 
      '#00BCD4', '#FF5722', '#795548', '#607D8B', '#E91E63'
    ];
    
    const subjectData = uniqueSubjects.map(subject => subjectHours[subject] || 0);
    const subjectColors = uniqueSubjects.map((_, index) => chartColors[index % chartColors.length]);
    
    // Generate timeline data for Gantt-like chart
    const cycles = studyPlan.cycles || [];
    const timelineLabels = cycles.map(cycle => cycle.cycleName || cycle.cycleType || 'Cycle');
    const timelineData = cycles.map((cycle, index) => ({
      x: cycle.cycleDuration || 0,
      y: index,
      label: cycle.cycleName || cycle.cycleType || 'Cycle'
    }));
    
    return `
      // Timeline Gantt Chart
      const timelineCtx = document.getElementById('timelineChart');
      if (timelineCtx) {
        new Chart(timelineCtx, {
          type: 'bar',
          data: {
            labels: ${JSON.stringify(timelineLabels)},
            datasets: [{
              label: 'Duration (Weeks)',
              data: ${JSON.stringify(cycles.map(cycle => cycle.cycleDuration || 0))},
              backgroundColor: ${JSON.stringify(cycles.map((_, index) => chartColors[index % chartColors.length]))},
              borderColor: ${JSON.stringify(cycles.map((_, index) => chartColors[index % chartColors.length]))},
              borderWidth: 1
            }]
          },
          options: {
            indexAxis: 'y',
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
              legend: { display: false },
              title: {
                display: true,
                text: 'Study Cycle Timeline'
              }
            },
            scales: {
              x: {
                beginAtZero: true,
                title: { display: true, text: 'Weeks' }
              },
              y: {
                title: { display: true, text: 'Cycles' }
              }
            }
          }
        });
      }
      
      // Subjects pie chart
      const subjectsCtx = document.getElementById('subjectsChart');
      if (subjectsCtx) {
        new Chart(subjectsCtx, {
          type: 'doughnut',
          data: {
            labels: ${JSON.stringify(uniqueSubjects)},
            datasets: [{
              data: ${JSON.stringify(subjectData)},
              backgroundColor: ${JSON.stringify(subjectColors)},
              borderWidth: 2,
              borderColor: '#ffffff'
            }]
          },
          options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
              legend: {
                position: 'right',
                labels: {
                  font: { family: 'Inter, sans-serif', size: 10 }
                }
              },
              title: {
                display: true,
                text: 'Subject Time Distribution'
              }
            }
          }
        });
      }
    `;
  }

  // ===== CALENDAR CSS GENERATION METHODS =====

  private static getCalendarStructuredCSS(): string {
    return `
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
      
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        text-rendering: optimizeLegibility;
      }
      
      body {
        font-family: 'Inter', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        font-size: 11px;
        line-height: 1.6;
        color: #1e293b;
        background: white;
        padding: 8px;
        margin: 0;
      }
      
      .calendar-header {
        text-align: center;
        margin-bottom: 25px;
        padding: 18px 0;
        border: 2px solid #2196F3;
        border-radius: 8px;
        background: linear-gradient(135deg, #E3F2FD 0%, #BBDEFB 100%);
      }
      
      .calendar-title {
        font-size: 22px;
        font-weight: 800;
        color: #0D47A1;
        margin-bottom: 8px;
        letter-spacing: -0.025em;
      }
      
      .calendar-subtitle {
        font-size: 13px;
        font-weight: 500;
        color: #1565C0;
        margin-bottom: 5px;
      }
      
      .calendar-student-info {
        font-size: 11px;
        font-weight: 400;
        color: #1976D2;
      }
      
      .calendar-overview-section {
        margin-bottom: 25px;
        padding: 15px;
        border: 1px solid #E3F2FD;
        border-radius: 6px;
        background-color: #FAFAFA;
      }
      
      .calendar-section-title {
        font-size: 16px;
        font-weight: 700;
        color: #0D47A1;
        margin-bottom: 12px;
        padding-bottom: 5px;
        border-bottom: 2px solid #2196F3;
      }
      
      .calendar-overview-grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 15px;
        margin-bottom: 15px;
      }
      
      .calendar-overview-card {
        background: white;
        border: 1px solid #E3F2FD;
        border-radius: 6px;
        padding: 12px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      }
      
      .calendar-overview-card h3 {
        color: #1565C0;
        font-weight: 600;
        margin-bottom: 10px;
        font-size: 12px;
      }
      
      .calendar-stat-item {
        display: flex;
        justify-content: space-between;
        margin-bottom: 5px;
        padding: 4px 0;
        border-bottom: 1px solid #F5F5F5;
      }
      
      .calendar-stat-label {
        font-weight: 500;
        color: #64748b;
        font-size: 10px;
      }
      
      .calendar-stat-value {
        font-weight: 600;
        color: #1e293b;
        font-size: 10px;
      }
      
      .calendar-overview-text {
        font-size: 11px;
        line-height: 1.6;
        color: #374151;
        text-align: justify;
      }
      
      .calendar-timeline-section {
        margin-bottom: 25px;
      }
      
      .timeline-container {
        position: relative;
        padding-left: 20px;
      }
      
      .timeline-item {
        position: relative;
        margin-bottom: 20px;
        padding-left: 25px;
        padding-bottom: 15px;
      }
      
      .timeline-marker {
        position: absolute;
        left: -8px;
        top: 5px;
        width: 12px;
        height: 12px;
        border-radius: 50%;
        border: 2px solid white;
        box-shadow: 0 0 0 2px #2196F3;
      }
      
      .timeline-content {
        background: white;
        border: 1px solid #E3F2FD;
        border-radius: 6px;
        padding: 12px;
      }
      
      .timeline-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 8px;
      }
      
      .timeline-header h4 {
        font-size: 13px;
        font-weight: 600;
        margin: 0;
      }
      
      .timeline-duration {
        background: #2196F3;
        color: white;
        padding: 2px 8px;
        border-radius: 12px;
        font-size: 9px;
        font-weight: 600;
      }
      
      .timeline-dates {
        font-size: 10px;
        color: #1976D2;
        font-weight: 500;
        margin-bottom: 5px;
      }
      
      .timeline-description {
        font-size: 10px;
        color: #4b5563;
        line-height: 1.4;
        margin-bottom: 5px;
      }
      
      .timeline-blocks {
        font-size: 9px;
        color: #6b7280;
        font-style: italic;
      }
      
      .calendar-profile-section {
        margin-bottom: 25px;
      }
      
      .calendar-profile-table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 15px;
        font-size: 10px;
      }
      
      .calendar-profile-table td {
        padding: 6px;
        border: 1px solid #E3F2FD;
        vertical-align: top;
      }
      
      .calendar-profile-label {
        font-weight: 600;
        color: #1565C0;
        background-color: #E3F2FD;
        width: 25%;
      }
      
      .calendar-profile-value {
        color: #1f2937;
        width: 25%;
      }
      
      .calendar-blocks-section {
        margin-bottom: 25px;
      }
      
      .calendar-cycle-container {
        margin-bottom: 20px;
        border-radius: 8px;
        overflow: hidden;
      }
      
      .calendar-cycle-header {
        padding: 12px 15px;
        color: white;
      }
      
      .calendar-cycle-header h3 {
        font-size: 14px;
        font-weight: 700;
        margin-bottom: 5px;
      }
      
      .calendar-cycle-duration {
        font-size: 11px;
        opacity: 0.9;
      }
      
      .calendar-cycle-description {
        padding: 10px 15px;
        font-size: 10px;
        color: #4b5563;
        background-color: #F8F9FA;
        border-bottom: 1px solid #E9ECEF;
      }
      
      .calendar-cycle-blocks {
        padding: 10px;
        background-color: white;
      }
      
      .calendar-block-item {
        margin-bottom: 12px;
        padding: 10px;
        border-radius: 6px;
        border: 1px solid #E9ECEF;
      }
      
      .calendar-block-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 8px;
      }
      
      .calendar-block-title {
        font-size: 12px;
        font-weight: 600;
        color: #1e293b;
      }
      
      .calendar-block-week {
        background: #6C757D;
        color: white;
        padding: 2px 8px;
        border-radius: 10px;
        font-size: 9px;
        font-weight: 600;
      }
      
      .calendar-block-dates,
      .calendar-block-duration,
      .calendar-block-subjects,
      .calendar-block-resources {
        font-size: 10px;
        margin-bottom: 3px;
        line-height: 1.4;
      }
      
      .calendar-block-dates { color: #1976D2; }
      .calendar-block-duration { color: #388E3C; }
      .calendar-block-subjects { color: #F57C00; }
      .calendar-block-resources { color: #7B1FA2; }
      
      .calendar-resources-section {
        margin-bottom: 25px;
      }
      
      .calendar-resources-intro {
        font-size: 11px;
        color: #374151;
        margin-bottom: 15px;
      }
      
      .calendar-resources-grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 12px;
      }
      
      .calendar-subject-resources {
        background-color: #F8F9FA;
        padding: 10px;
        border-radius: 6px;
        border-left: 3px solid #2196F3;
      }
      
      .calendar-subject-resources h4 {
        font-size: 11px;
        font-weight: 600;
        color: #0D47A1;
        margin-bottom: 8px;
      }
      
      .calendar-resource-item {
        font-size: 9px;
        color: #4b5563;
        margin-bottom: 2px;
        line-height: 1.3;
      }
      
      .calendar-footer {
        margin-top: 30px;
        padding: 12px 15px;
        background-color: #0D47A1;
        color: white;
        border-radius: 6px;
      }
      
      .calendar-footer-content {
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-size: 10px;
      }
      
      .calendar-footer-left { opacity: 0.9; }
      .calendar-footer-right { font-weight: 600; }
      
      @page {
        size: A4;
        margin: 15mm;
      }
      
      @media print {
        body { print-color-adjust: exact; }
        .calendar-cycle-container { page-break-inside: avoid; }
        .calendar-block-item { page-break-inside: avoid; }
      }
    </style>`;
  }

  private static getCalendarVisualCSS(): string {
    return `
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
      
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        text-rendering: optimizeLegibility;
      }
      
      body {
        font-family: 'Inter', sans-serif;
        font-size: 10px;
        line-height: 1.4;
        color: #1e293b;
        background: white;
        padding: 5px;
        margin: 0;
      }
      
      .calendar-page {
        width: 100%;
        background: white;
      }
      
      /* Calendar Header */
      .calendar-header {
        background: linear-gradient(135deg, #2196F3 0%, #1976D2 100%);
        color: white;
        padding: 20px;
        text-align: center;
        margin-bottom: 15px;
      }
      
      .calendar-header h1 {
        font-size: 24px;
        font-weight: 800;
        margin-bottom: 5px;
      }
      
      .calendar-subtitle {
        font-size: 14px;
        font-weight: 400;
        opacity: 0.9;
        margin-bottom: 3px;
      }
      
      .calendar-period {
        font-size: 12px;
        font-weight: 300;
        opacity: 0.8;
      }
      
      /* Calendar Legend */
      .calendar-legend {
        margin: 15px 0;
        padding: 10px;
        background: #f8f9fa;
        border-radius: 6px;
      }
      
      .calendar-legend h3 {
        font-size: 14px;
        margin-bottom: 8px;
        color: #1976D2;
      }
      
      .legend-items {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 8px;
      }
      
      .legend-item {
        display: flex;
        align-items: center;
        gap: 6px;
      }
      
      .legend-color {
        width: 16px;
        height: 12px;
        border-radius: 2px;
      }
      
      .legend-label {
        font-size: 9px;
        font-weight: 500;
      }
      
      /* Monthly Calendar Grids */
      .monthly-calendars {
        margin-bottom: 20px;
      }
      
      .monthly-calendar {
        margin-bottom: 25px;
        page-break-inside: avoid;
      }
      
      .calendar-month-title {
        text-align: center;
        margin-bottom: 10px;
      }
      
      .calendar-month-title h2 {
        font-size: 18px;
        font-weight: 700;
        color: #1976D2;
      }
      
      .calendar-grid {
        border: 2px solid #1976D2;
        border-radius: 8px;
        overflow: hidden;
      }
      
      .calendar-header-row {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        background: #1976D2;
      }
      
      .calendar-day-header {
        padding: 8px 4px;
        text-align: center;
        font-weight: 600;
        color: white;
        font-size: 10px;
        border-right: 1px solid #0D47A1;
      }
      
      .calendar-day-header:last-child {
        border-right: none;
      }
      
      .calendar-days-grid {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
      }
      
      .calendar-day {
        min-height: 80px;
        border-right: 1px solid #e0e0e0;
        border-bottom: 1px solid #e0e0e0;
        padding: 3px;
        position: relative;
        background: white;
      }
      
      .calendar-day:nth-child(7n) {
        border-right: none;
      }
      
      .calendar-day.other-month {
        background: #f5f5f5;
        color: #9e9e9e;
      }
      
      .calendar-day.today {
        background: #fff3e0;
        border: 2px solid #ff9800;
      }
      
      .calendar-day.has-events {
        background: #f8f9ff;
      }
      
      .calendar-date-number {
        font-size: 11px;
        font-weight: 600;
        text-align: right;
        margin-bottom: 2px;
        color: #333;
      }
      
      .other-month .calendar-date-number {
        color: #bbb;
      }
      
      .calendar-events {
        font-size: 7px;
        line-height: 1.2;
      }
      
      .calendar-event {
        margin-bottom: 1px;
        padding: 1px 2px;
        border-radius: 2px;
        overflow: hidden;
      }
      
      .event-title {
        font-weight: 600;
        display: block;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }
      
      .event-subjects {
        font-size: 6px;
        opacity: 0.8;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }
      
      .more-events {
        font-size: 6px;
        color: #666;
        font-style: italic;
        margin-top: 1px;
      }
      
      /* Weekly Calendar View */
      .weekly-detail-section {
        margin: 20px 0;
      }
      
      .weekly-detail-section h2 {
        font-size: 16px;
        color: #1976D2;
        margin-bottom: 10px;
        text-align: center;
      }
      
      .weekly-calendars {
        display: grid;
        gap: 15px;
      }
      
      .weekly-calendar {
        border: 1px solid #e0e0e0;
        border-radius: 6px;
        overflow: hidden;
        page-break-inside: avoid;
      }
      
      .week-header {
        background: #e3f2fd;
        padding: 8px 12px;
        border-bottom: 1px solid #e0e0e0;
      }
      
      .week-header h3 {
        font-size: 12px;
        color: #1976D2;
        font-weight: 600;
      }
      
      .week-grid {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
      }
      
      .week-day {
        border-right: 1px solid #e0e0e0;
        min-height: 60px;
      }
      
      .week-day:last-child {
        border-right: none;
      }
      
      .week-day-header {
        background: #f5f5f5;
        padding: 4px;
        text-align: center;
        border-bottom: 1px solid #e0e0e0;
      }
      
      .week-day-name {
        font-size: 8px;
        font-weight: 600;
        color: #333;
      }
      
      .week-day-date {
        font-size: 7px;
        color: #666;
      }
      
      .week-day-events {
        padding: 3px;
        font-size: 7px;
      }
      
      .week-event {
        margin-bottom: 2px;
        padding: 2px 3px;
        border-radius: 2px;
        line-height: 1.2;
      }
      
      .week-event-title {
        font-weight: 600;
        margin-bottom: 1px;
      }
      
      .week-event-subjects {
        font-size: 6px;
        opacity: 0.8;
      }
      
      .no-events {
        font-size: 7px;
        color: #999;
        font-style: italic;
        text-align: center;
        padding: 10px 2px;
      }
      
      /* Study Summary */
      .study-summary {
        margin: 20px 0;
      }
      
      .study-summary h2 {
        font-size: 16px;
        color: #1976D2;
        margin-bottom: 10px;
        text-align: center;
      }
      
      .summary-table {
        width: 100%;
        border-collapse: collapse;
        font-size: 9px;
        margin-top: 10px;
      }
      
      .summary-table th {
        background: #1976D2;
        color: white;
        padding: 6px 4px;
        text-align: left;
        font-weight: 600;
        border: 1px solid #0D47A1;
      }
      
      .summary-table td {
        padding: 5px 4px;
        border: 1px solid #e0e0e0;
        vertical-align: top;
        line-height: 1.3;
      }
      
      .summary-table tr:nth-child(even) {
        background: #f9f9f9;
      }
      
      /* Print Optimization */
      @page {
        size: A4;
        margin: 12mm;
      }
      
      @media print {
        body { 
          print-color-adjust: exact; 
          -webkit-print-color-adjust: exact;
        }
        
        .monthly-calendar {
          page-break-inside: avoid;
          break-inside: avoid;
        }
        
        .weekly-calendar {
          page-break-inside: avoid;
          break-inside: avoid;
        }
      }
    </style>`;
  }

  // ===== HELPER METHODS (matching original services) =====

  /**
   * Generate timeline data for calendar visualization
   */
  private static generateTimelineData(studyPlan: StudyPlan): any {
    const cycles = studyPlan.cycles || [];
    return cycles.map(cycle => ({
      name: cycle.cycleName || cycle.cycleType,
      startDate: cycle.cycleStartDate,
      endDate: cycle.cycleEndDate,
      duration: cycle.cycleDuration || 0,
      type: cycle.cycleType,
      blocks: cycle.cycleBlocks?.length || 0
    }));
  }


  /**
   * Generate student profile data for table - enhanced to match DOCX version
   */
  private static generateStudentProfileData(studentIntake: StudentIntake): string[][] {
    const rows: string[][] = [];
    
    // Personal Details
    if (studentIntake.personal_details) {
      const pd = studentIntake.personal_details;
      rows.push([
        'Full Name', pd.full_name || 'Not provided',
        'Email', pd.email || 'Not provided'
      ]);
      rows.push([
        'Phone', pd.phone_number || 'Not provided',
        'Location', pd.present_location || 'Not provided'
      ]);
      rows.push([
        'Student Type', pd.student_archetype || 'Not provided',
        'Graduation Stream', pd.graduation_stream || 'Not provided'
      ]);
    }
    
    // Preparation Background
    if (studentIntake.preparation_background) {
      const pb = studentIntake.preparation_background;
      rows.push([
        'Preparing Since', pb.preparing_since || 'Not provided',
        'Number of Attempts', pb.number_of_attempts || 'Not provided'
      ]);
      rows.push([
        'Highest Stage Reached', pb.highest_stage_per_attempt || 'Not provided',
        'Previous Prelims Score', (pb.last_attempt_gs_prelims_score && pb.last_attempt_gs_prelims_score > 0) ? pb.last_attempt_gs_prelims_score.toString() : 'N/A'
      ]);
    }
    
    // Study Strategy
    if (studentIntake.study_strategy) {
      const ss = studentIntake.study_strategy;
      rows.push([
        'Weekly Study Hours', ss.weekly_study_hours || 'Not provided',
        'Study Approach', ss.study_approach || 'Not provided'
      ]);
      rows.push([
        'Focus Combination', ss.study_focus_combo || 'Not provided',
        'Time Distribution', ss.time_distribution || 'Balanced'
      ]);
    }
    
    // Target Year and Exam Details
    rows.push([
      'Target Year', studentIntake.target_year || 'Not provided',
      'Plan Start Date', studentIntake.start_date || 'Not provided'
    ]);
    
    return rows;
  }

  /**
   * Get cycle description based on cycle type
   */
  private static getCycleDescription(cycle: StudyCycle): string {
    const duration = cycle.cycleDuration || 0;
    const startDate = cycle.cycleStartDate || 'TBD';
    const endDate = cycle.cycleEndDate || 'TBD';
    
    switch (cycle.cycleType) {
      case CycleType.C1:
        return `📚 NCERT Foundation Phase: Building fundamental concepts through systematic NCERT study.`;
      case CycleType.C2:
        return `🏗️ Foundation Building Phase: Establishing solid conceptual foundation across all subjects.`;
      case CycleType.C3:
        return `📝 Mains Preparation Phase: Developing analytical thinking and answer writing skills.`;
      case CycleType.C4:
        return `📖 Prelims Reading Phase: Intensive reading and practice test preparation.`;
      case CycleType.C5:
        return `🔄 Prelims Revision Phase: Consolidating knowledge for Prelims examination.`;
      case CycleType.C5B:
        return `⚡ Prelims Final Sprint: Last-minute revision and high-yield topic focus.`;
      case CycleType.C6:
        return `✍️ Mains Revision Phase: Comprehensive Mains preparation with answer writing practice.`;
      case CycleType.C7:
        return `🎯 Mains Rapid Revision: Intensive post-Prelims Mains preparation.`;
      case CycleType.C8:
        return `📋 Mains Foundation Phase: Specialized Mains preparation with analytical focus.`;
      default:
        return `📅 Study Phase: Focused preparation designed to optimize learning outcomes.`;
    }
  }

  /**
   * Calculate block dates from cycle dates and block position
   */
  private static calculateBlockDates(_cycle: StudyCycle, block: Block, _blockIndex: number): { start: string; end: string } {
    return {
      start: block.block_start_date ? dayjs(block.block_start_date).format('MMM DD') : 'TBD',
      end: block.block_end_date ? dayjs(block.block_end_date).format('MMM DD') : 'TBD'
    };
  }

  /**
   * Summarize block resources for calendar display
   */
  private static summarizeBlockResources(blockResources?: BlockResources): string[] {
    if (!blockResources) {
      return ['No resources available'];
    }

    const resourceNames: string[] = [];
    
    // Collect all resource names
    if (blockResources.primary_books && blockResources.primary_books.length > 0) {
      blockResources.primary_books.forEach(book => {
        resourceNames.push(book.resource_title);
      });
    }
    
    if (blockResources.supplementary_materials && blockResources.supplementary_materials.length > 0) {
      blockResources.supplementary_materials.forEach(mat => {
        resourceNames.push(mat.resource_title);
      });
    }
    
    if (blockResources.current_affairs_sources && blockResources.current_affairs_sources.length > 0) {
      blockResources.current_affairs_sources.forEach(ca => {
        resourceNames.push(ca.resource_title);
      });
    }
    
    if (blockResources.practice_resources && blockResources.practice_resources.length > 0) {
      blockResources.practice_resources.forEach(practice => {
        resourceNames.push(practice.resource_title);
      });
    }
    
    if (blockResources.video_content && blockResources.video_content.length > 0) {
      blockResources.video_content.forEach(video => {
        resourceNames.push(video.resource_title);
      });
    }
    
    return resourceNames.length > 0 ? resourceNames : ['Resources available'];
  }

  /**
   * Get unique subjects from study plan
   */
  private static getUniqueSubjects(studyPlan: StudyPlan): string[] {
    const subjects = new Set<string>();
    studyPlan.cycles?.forEach(cycle => {
      cycle.cycleBlocks?.forEach(block => {
        block.subjects?.forEach(subject => subjects.add(subject));
      });
    });
    return Array.from(subjects);
  }

  /**
   * Get subject name from subject code
   */
  private static getSubjectName(subjectCode: string): string {
    const subject = SubjectLoader.getSubjectByCode(subjectCode);
    return subject?.subjectName || subjectCode;
  }

  /**
   * Calculate total weeks across all cycles
   */
  private static calculateTotalWeeks(studyPlan: StudyPlan): number {
    return studyPlan.cycles?.reduce((total, cycle) => total + (cycle.cycleDuration || 0), 0) || 0;
  }

  /**
   * Count total blocks across all cycles
   */
  private static countTotalBlocks(studyPlan: StudyPlan): number {
    return studyPlan.cycles?.reduce((total, cycle) => total + (cycle.cycleBlocks?.length || 0), 0) || 0;
  }

  /**
   * Calculate subject hours distribution
   */
  private static calculateSubjectHours(studyPlan: StudyPlan): Record<string, number> {
    const subjectHours: Record<string, number> = {};
    const uniqueSubjects = this.getUniqueSubjects(studyPlan);
    
    uniqueSubjects.forEach(subject => {
      let totalHours = 0;
      studyPlan.cycles?.forEach(cycle => {
        cycle.cycleBlocks?.forEach(block => {
          if (block.subjects?.includes(subject)) {
            const blockHours = (block.duration_weeks || 0) * 35;
            const subjectHours = blockHours / (block.subjects?.length || 1);
            totalHours += subjectHours;
          }
        });
      });
      subjectHours[subject] = Math.round(totalHours);
    });
    
    return subjectHours;
  }

  /**
   * Calculate duration string
   */
  private static calculateDuration(startDate: dayjs.Dayjs, targetYear: number): string {
    const targetDate = dayjs(`${targetYear}-05-19`);
    
    const years = targetDate.diff(startDate, 'year');
    const months = targetDate.diff(startDate, 'month') % 12;
    const weeks = Math.floor(targetDate.diff(startDate, 'day') % 30 / 7);
    
    const parts: string[] = [];
    
    if (years > 0) {
      parts.push(`${years} year${years !== 1 ? 's' : ''}`);
    }
    if (months > 0) {
      parts.push(`${months} month${months !== 1 ? 's' : ''}`);
    }
    if (weeks > 0) {
      parts.push(`${weeks} week${weeks !== 1 ? 's' : ''}`);
    }
    
    return parts.length > 0 ? parts.join(' ') : '0 days';
  }
}

export default CalendarPDFService;