import type { StudyPlan, StudyCycle, Block, BlockResources, StudentIntake } from '../types/models';
import { CycleType } from '../types/Types';
import { ResourceService } from './ResourceService';
import { SubjectLoader } from './SubjectLoader';
import dayjs from 'dayjs';
import puppeteer, { type PDFOptions, type Browser } from 'puppeteer';

// Color mapping for different cycle types (matching calendar-example.html)
const CYCLE_PHASE_COLORS = {
  'C1': { bg: '#f8f9fa', border: '#e9ecef', phase: 'cycle-phase-1' }, // NCERT Foundation
  'C2': { bg: '#f1f3f4', border: '#dadce0', phase: 'cycle-phase-2' }, // Comprehensive Foundation
  'C3': { bg: '#e8f0fe', border: '#c6dafc', phase: 'cycle-phase-3' }, // Mains Revision Pre-Prelims
  'C4': { bg: '#f1f3f4', border: '#dadce0', phase: 'cycle-phase-2' }, // Prelims Reading
  'C5': { bg: '#e8f0fe', border: '#c6dafc', phase: 'cycle-phase-3' }, // Prelims Revision
  'C5.b': { bg: '#e8f0fe', border: '#c6dafc', phase: 'cycle-phase-3' }, // Prelims Rapid Revision
  'C6': { bg: '#f3e5f5', border: '#e1bee7', phase: 'cycle-phase-4' }, // Mains Revision
  'C7': { bg: '#f3e5f5', border: '#e1bee7', phase: 'cycle-phase-4' }, // Mains Rapid Revision
  'C8': { bg: '#f3e5f5', border: '#e1bee7', phase: 'cycle-phase-4' }, // Mains Foundation
} as const;

/**
 * Calendar-style PDF generation service using Puppeteer
 * Matches the layout and aesthetics of calendar-example.html
 */
export class CalendarStylePDFService {
  
  /**
   * Generate structured PDF that matches calendar-example.html format with high-fidelity rendering
   * This is the RECOMMENDED method for professional study plan PDFs
   */
  public static async generateStructuredPDF(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    filename?: string
  ): Promise<void> {
    try {
      // Create high-quality HTML template matching calendar design
      const htmlContent = await this.createCalendarStyleHTML(studyPlan, studentIntake);
      
      // Generate PDF using Puppeteer
      const pdfBuffer = await this.generatePDFFromHTML(htmlContent, {
        format: 'A4',
        printBackground: true,
        margin: { top: '20px', right: '30px', bottom: '20px', left: '30px' },
        preferCSSPageSize: false,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `
          <div style="font-size: 10px; text-align: center; width: 100%; color: #666; margin: 0 15px;">
            <span class="title"></span> - Generated by Helios Study Planner on ${new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })} - Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </div>
        `
      });
      
      // Save the PDF
      await this.savePDF(pdfBuffer, filename || `calendar-study-plan-${studyPlan.study_plan_id || 'plan'}.pdf`);
      
    } catch (error) {
      console.error('Failed to generate calendar-style PDF:', error);
      throw new Error('Calendar-style PDF generation failed');
    }
  }

  /**
   * Generate visual PDF with charts and modern design using high-fidelity rendering
   * Use this for presentation-style PDFs with visualizations
   */
  static async generateVisualPDF(
    studyPlan: StudyPlan,
    studentIntake: StudentIntake,
    filename?: string
  ): Promise<void> {
    try {
      // Create enhanced visual HTML template
      const htmlContent = await this.createCalendarStyleHTML(studyPlan, studentIntake);
      
      // Generate PDF using Puppeteer with enhanced visual settings
      const pdfBuffer = await this.generatePDFFromHTML(htmlContent, {
        format: 'A4',
        printBackground: true,
        margin: { top: '20px', right: '30px', bottom: '20px', left: '30px' },
        preferCSSPageSize: false,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `
          <div style="font-size: 10px; text-align: center; width: 100%; color: #666; margin: 0 15px;">
            Generated by Helios Study Planner on ${new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })} - Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </div>
        `
      });
      
      // Save the PDF
      await this.savePDF(pdfBuffer, filename || `visual-calendar-study-plan-${studyPlan.study_plan_id || 'plan'}.pdf`);
      
    } catch (error) {
      console.error('Failed to generate visual calendar PDF:', error);
      throw new Error('Visual calendar PDF generation failed');
    }
  }

  /**
   * Main entry point - defaults to structured PDF (recommended)
   * Matches the exact interface of the original PDFService
   */
  static async generateStudyPlanPDF(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    options?: {
      filename?: string;
      type?: 'structured' | 'visual';
    }
  ): Promise<void> {
    const type = options?.type || 'structured';
    
    if (type === 'visual') {
      return this.generateVisualPDF(studyPlan, studentIntake, options?.filename);
    } else {
      return this.generateStructuredPDF(studyPlan, studentIntake, options?.filename);
    }
  }

  // ===== CORE PDF GENERATION METHODS =====

  /**
   * Generate PDF from HTML using Puppeteer with high-quality settings
   */
  private static async generatePDFFromHTML(htmlContent: string, options: PDFOptions): Promise<Buffer> {
    let browser: Browser | null = null;
    
    try {
      // Launch browser with optimized settings for PDF generation
      browser = await puppeteer.launch({
        headless: true,
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--disable-gpu',
          '--disable-web-security',
          '--disable-features=VizDisplayCompositor',
          '--run-all-compositor-stages-before-draw',
          '--disable-extensions-http-throttling'
        ],
        // Use system Chrome if available for better font rendering
        executablePath: process.env.CHROME_PATH || undefined
      });

      const page = await browser.newPage();
      
      // Set viewport for consistent rendering
      await page.setViewport({ width: 1200, height: 1600, deviceScaleFactor: 2 });
      
      // Enable better font rendering
      await page.evaluateOnNewDocument(() => {
        // Improve text rendering
        const style = document.createElement('style');
        style.innerHTML = `
          * {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            text-rendering: optimizeLegibility;
          }
        `;
        document.head.appendChild(style);
      });

      // Set content with proper encoding
      await page.setContent(htmlContent, {
        waitUntil: ['networkidle0', 'domcontentloaded'],
        timeout: 30000
      });

      // Wait for any charts or dynamic content to load
      await new Promise(resolve => setTimeout(resolve, 2000));

      // Generate PDF with high-quality settings
      const pdfBuffer = await page.pdf({
        ...options,
        preferCSSPageSize: false,
        printBackground: true
      });

      return Buffer.from(pdfBuffer);
    } finally {
      if (browser) {
        await browser.close();
      }
    }
  }

  /**
   * Save PDF to appropriate location (filesystem or browser download)
   */
  private static async savePDF(pdfBuffer: Buffer, filename: string): Promise<void> {
    if (typeof window !== 'undefined') {
      // Browser environment - trigger download
      const blob = new Blob([new Uint8Array(pdfBuffer)], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
      console.log(`📁 PDF download triggered: ${filename}`);
    } else {
      // Node.js environment - save to filesystem
      const fs = await import('fs');
      const path = await import('path');
      
      const outputDir = path.join(process.cwd(), 'generated-docs');
      
      // Ensure output directory exists
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }
      
      const outputPath = path.join(outputDir, filename);
      fs.writeFileSync(outputPath, pdfBuffer);
      
      console.log(`✅ PDF saved: ${filename}`);
      console.log(`   📁 Location: ${outputPath}`);
    }
  }

  // ===== HTML TEMPLATE GENERATION METHODS =====

  /**
   * Create calendar-style HTML template that matches calendar-example.html
   */
  private static async createCalendarStyleHTML(studyPlan: StudyPlan, studentIntake: StudentIntake): Promise<string> {
    const uniqueSubjects = this.getUniqueSubjects(studyPlan);
    
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${studyPlan.plan_title || 'Study Planner Calendar'}</title>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        ${this.getCalendarStyleCSS()}
    </head>
    <body>
        <div class="container">
            ${this.generateStudentProfileSection(studentIntake, studyPlan)}
            ${this.generateCalendarSection(studyPlan)}
            ${this.generateCycleDetailsSection(studyPlan)}
            ${await this.generateResourcesSection(studyPlan, uniqueSubjects)}
        </div>
    </body>
    </html>`;
  }

  /**
   * Generate student profile section matching calendar-example.html
   */
  private static generateStudentProfileSection(studentIntake: StudentIntake, studyPlan: StudyPlan): string {
    
    return `
    <div class="student-profile">
        <div class="profile-header">
            <h1 class="profile-title">${studyPlan.plan_title || 'UPSC Study Plan'}</h1>
            <p class="profile-subtitle">Comprehensive Study Planner for ${studyPlan.targeted_year || '2025'}</p>
        </div>
        
        <div class="profile-grid">
            <div class="profile-card">
                <h3 class="profile-card-title"><i class="fas fa-user"></i> Personal Details</h3>
                <div class="profile-item">
                    <span class="profile-label">Full Name</span>
                    <span class="profile-value">${studentIntake.personal_details?.full_name || 'Student'}</span>
                </div>
                <div class="profile-item">
                    <span class="profile-label">Email</span>
                    <span class="profile-value">${studentIntake.personal_details?.email || 'Not provided'}</span>
                </div>
                <div class="profile-item">
                    <span class="profile-label">Location</span>
                    <span class="profile-value">${studentIntake.personal_details?.present_location || 'Not provided'}</span>
                </div>
                <div class="profile-item">
                    <span class="profile-label">Graduation Stream</span>
                    <span class="profile-value">${studentIntake.personal_details?.graduation_stream || 'Not provided'}</span>
                </div>
            </div>
            
            <div class="profile-card">
                <h3 class="profile-card-title"><i class="fas fa-graduation-cap"></i> Preparation Background</h3>
                <div class="profile-item">
                    <span class="profile-label">Preparing Since</span>
                    <span class="profile-value">${studentIntake.preparation_background?.preparing_since || 'Not provided'}</span>
                </div>
                <div class="profile-item">
                    <span class="profile-label">Number of Attempts</span>
                    <span class="profile-value">${studentIntake.preparation_background?.number_of_attempts || '0'}</span>
                </div>
                <div class="profile-item">
                    <span class="profile-label">Highest Stage</span>
                    <span class="profile-value">${studentIntake.preparation_background?.highest_stage_per_attempt || 'N/A'}</span>
                </div>
                <div class="profile-item">
                    <span class="profile-label">Target Year</span>
                    <span class="profile-value">${studentIntake.target_year || studyPlan.targeted_year || '2025'}</span>
                </div>
            </div>
            
            <div class="profile-card">
                <h3 class="profile-card-title"><i class="fas fa-book-open"></i> Study Strategy</h3>
                <div class="profile-item">
                    <span class="profile-label">Weekly Hours</span>
                    <span class="profile-value">${studentIntake.study_strategy?.weekly_study_hours || 'Not specified'}</span>
                </div>
                <div class="profile-item">
                    <span class="profile-label">Study Approach</span>
                    <span class="profile-value">${studentIntake.study_strategy?.study_approach || 'Balanced'}</span>
                </div>
                <div class="profile-item">
                    <span class="profile-label">Focus Combination</span>
                    <span class="profile-value">${studentIntake.study_strategy?.study_focus_combo || 'Comprehensive'}</span>
                </div>
                <div class="profile-item">
                    <span class="profile-label">Revision Strategy</span>
                    <span class="profile-value">${studentIntake.study_strategy?.revision_strategy || 'Weekly'}</span>
                </div>
            </div>
            
            <div class="profile-card">
                <h3 class="profile-card-title"><i class="fas fa-chart-line"></i> Plan Overview</h3>
                <div class="profile-item">
                    <span class="profile-label">Total Duration</span>
                    <span class="profile-value">${this.calculateTotalWeeks(studyPlan)} weeks</span>
                </div>
                <div class="profile-item">
                    <span class="profile-label">Study Cycles</span>
                    <span class="profile-value">${studyPlan.cycles?.length || 0}</span>
                </div>
                <div class="profile-item">
                    <span class="profile-label">Study Blocks</span>
                    <span class="profile-value">${this.countTotalBlocks(studyPlan)}</span>
                </div>
                <div class="profile-item">
                    <span class="profile-label">Subjects</span>
                    <span class="profile-value">${this.getUniqueSubjects(studyPlan).length}</span>
                </div>
            </div>
        </div>
    </div>`;
  }

  /**
   * Generate calendar section with cycle visualization
   */
  private static generateCalendarSection(studyPlan: StudyPlan): string {
    if (!studyPlan.cycles || studyPlan.cycles.length === 0) {
      return '<div class="calendar-section"><p>No cycles available</p></div>';
    }

    const cycleCards = studyPlan.cycles.map((cycle) => {
      const cycleColor = CYCLE_PHASE_COLORS[cycle.cycleType as keyof typeof CYCLE_PHASE_COLORS] || 
                        { bg: '#f8f9fa', border: '#e9ecef', phase: 'cycle-phase-1' };
      
      const startDate = cycle.cycleStartDate ? dayjs(cycle.cycleStartDate) : dayjs();
      const endDate = cycle.cycleEndDate ? dayjs(cycle.cycleEndDate) : startDate.add(cycle.cycleDuration || 4, 'week');
      
      return `
        <div class="cycle-timeline-card" style="background: ${cycleColor.bg}; border-left: 4px solid ${cycleColor.border};">
          <div class="cycle-header">
            <h3 class="cycle-title">${cycle.cycleName || cycle.cycleType}</h3>
            <div class="cycle-duration">${cycle.cycleDuration || 0} weeks</div>
          </div>
          <div class="cycle-dates">
            <div class="date-item">
              <span class="date-label">Start:</span>
              <span class="date-value">${startDate.format('MMM DD, YYYY')}</span>
            </div>
            <div class="date-item">
              <span class="date-label">End:</span>
              <span class="date-value">${endDate.format('MMM DD, YYYY')}</span>
            </div>
          </div>
          <div class="cycle-blocks">
            <div class="blocks-header">
              <i class="fas fa-cubes"></i>
              <span>${cycle.cycleBlocks?.length || 0} Study Blocks</span>
            </div>
            <div class="blocks-grid">
              ${(cycle.cycleBlocks || []).map(block => `
                <div class="block-item">
                  <div class="block-title">${block.block_title || 'Untitled'}</div>
                  <div class="block-duration">${block.duration_weeks || 0}w</div>
                </div>
              `).join('')}
            </div>
          </div>
        </div>
      `;
    }).join('');

    return `
    <div class="calendar-section">
        <h2 class="section-title">
            <i class="fas fa-calendar-alt"></i>
            Study Plan Timeline
        </h2>
        
        <div class="cycle-timeline">
            ${cycleCards}
        </div>
        
        <div class="legend">
            <h3 class="legend-title">Cycle Types Legend</h3>
            <div class="legend-items">
                <div class="legend-item">
                    <div class="legend-color" style="background: #f8f9fa; border: 1px solid #e9ecef;"></div>
                    <span>Foundation Phase</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color" style="background: #f1f3f4; border: 1px solid #dadce0;"></div>
                    <span>Reading Phase</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color" style="background: #e8f0fe; border: 1px solid #c6dafc;"></div>
                    <span>Revision Phase</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color" style="background: #f3e5f5; border: 1px solid #e1bee7;"></div>
                    <span>Mains Phase</span>
                </div>
            </div>
        </div>
    </div>`;
  }

  /**
   * Generate detailed cycle information section
   */
  private static generateCycleDetailsSection(studyPlan: StudyPlan): string {
    if (!studyPlan.cycles || studyPlan.cycles.length === 0) {
      return '';
    }

    const cycleDetails = studyPlan.cycles.map((cycle) => {
      const cycleColor = CYCLE_PHASE_COLORS[cycle.cycleType as keyof typeof CYCLE_PHASE_COLORS] || 
                        { bg: '#f8f9fa', border: '#e9ecef', phase: 'cycle-phase-1' };
      
      const blocksTable = (cycle.cycleBlocks || []).map(block => {
        const blockDates = this.calculateBlockDates(cycle, block, 0);
        const resourceSummary = this.summarizeBlockResources(block.block_resources);
        
        return `
          <tr>
            <td class="block-name">${block.block_title || 'Untitled'}</td>
            <td class="block-duration">${block.duration_weeks || 0} weeks</td>
            <td class="block-dates">${blockDates.start} - ${blockDates.end}</td>
            <td class="block-subjects">${block.subjects?.join(', ') || 'No subjects'}</td>
            <td class="block-resources">${resourceSummary.slice(0, 3).join(', ')}${resourceSummary.length > 3 ? '...' : ''}</td>
          </tr>
        `;
      }).join('');

      return `
        <div class="cycle-detail-card" style="border-left: 4px solid ${cycleColor.border};">
          <div class="cycle-detail-header" style="background: ${cycleColor.bg};">
            <h3>${cycle.cycleName || cycle.cycleType}</h3>
            <div class="cycle-meta">
              <span class="cycle-duration-badge">${cycle.cycleDuration || 0} weeks</span>
              <span class="cycle-blocks-badge">${cycle.cycleBlocks?.length || 0} blocks</span>
            </div>
          </div>
          
          <div class="cycle-description">
            ${this.getCycleDescription(cycle)}
          </div>
          
          <div class="blocks-table-container">
            <table class="blocks-table">
              <thead>
                <tr>
                  <th>Block Name</th>
                  <th>Duration</th>
                  <th>Dates</th>
                  <th>Subjects</th>
                  <th>Key Resources</th>
                </tr>
              </thead>
              <tbody>
                ${blocksTable}
              </tbody>
            </table>
          </div>
        </div>
      `;
    }).join('');

    return `
    <div class="cycle-details-section">
        <h2 class="section-title">
            <i class="fas fa-list-alt"></i>
            Detailed Cycle Information
        </h2>
        
        <div class="cycle-details">
            ${cycleDetails}
        </div>
    </div>`;
  }

  /**
   * Generate resources section
   */
  private static async generateResourcesSection(_studyPlan: StudyPlan, uniqueSubjects: string[]): Promise<string> {
    let resourcesHTML = '';
    
    for (const subjectCode of uniqueSubjects.slice(0, 8)) { // Limit for PDF space
      try {
        const subjectName = this.getSubjectName(subjectCode);
        const resources = await ResourceService.getResourcesForSubject(subjectCode);
        
        const resourceItems: string[] = [];
        
        if (resources.primary_books && resources.primary_books.length > 0) {
          resources.primary_books.slice(0, 3).forEach(book => {
            resourceItems.push(`<li><i class="fas fa-book"></i> ${book.resource_title}</li>`);
          });
        }
        
        if (resources.current_affairs_sources && resources.current_affairs_sources.length > 0) {
          resources.current_affairs_sources.slice(0, 2).forEach(ca => {
            resourceItems.push(`<li><i class="fas fa-newspaper"></i> ${ca.resource_title}</li>`);
          });
        }
        
        if (resources.practice_resources && resources.practice_resources.length > 0) {
          resources.practice_resources.slice(0, 2).forEach(practice => {
            resourceItems.push(`<li><i class="fas fa-pen"></i> ${practice.resource_title}</li>`);
          });
        }
        
        resourcesHTML += `
        <div class="resource-card">
            <h4 class="resource-subject">${subjectName}</h4>
            <ul class="resource-list">
              ${resourceItems.join('')}
            </ul>
        </div>`;
        
      } catch (error) {
        console.warn(`Failed to load resources for ${subjectCode}`, error);
        const subjectName = this.getSubjectName(subjectCode);
        resourcesHTML += `
        <div class="resource-card">
            <h4 class="resource-subject">${subjectName}</h4>
            <div class="resource-placeholder">Comprehensive resources available</div>
        </div>`;
      }
    }
    
    return `
    <div class="resources-section">
        <h2 class="section-title">
            <i class="fas fa-book-open"></i>
            Essential Resources
        </h2>
        
        <div class="resources-grid">
            ${resourcesHTML}
        </div>
    </div>`;
  }

  /**
   * Get CSS styles matching calendar-example.html
   */
  private static getCalendarStyleCSS(): string {
    return `
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Inter', sans-serif;
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            min-height: 100vh;
            padding: 20px;
        }

        .container {
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            border-radius: 20px;
            box-shadow: 0 20px 40px rgba(0,0,0,0.1);
            overflow: hidden;
        }

        /* Student Profile Section */
        .student-profile {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
        }

        .profile-header {
            text-align: center;
            margin-bottom: 30px;
        }

        .profile-title {
            font-size: 2.2rem;
            font-weight: 700;
            margin-bottom: 8px;
        }

        .profile-subtitle {
            font-size: 1.1rem;
            opacity: 0.9;
            margin-bottom: 20px;
        }

        .profile-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-top: 25px;
        }

        .profile-card {
            background: rgba(255, 255, 255, 0.1);
            border-radius: 12px;
            padding: 20px;
            backdrop-filter: blur(10px);
            border: 1px solid rgba(255, 255, 255, 0.2);
        }

        .profile-card-title {
            font-size: 1rem;
            font-weight: 600;
            margin-bottom: 12px;
            opacity: 0.9;
        }

        .profile-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 8px 0;
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
        }

        .profile-item:last-child {
            border-bottom: none;
        }

        .profile-label {
            font-size: 0.9rem;
            opacity: 0.8;
        }

        .profile-value {
            font-size: 0.9rem;
            font-weight: 500;
        }

        /* Calendar Section */
        .calendar-section {
            padding: 30px;
        }

        .section-title {
            font-size: 1.8rem;
            font-weight: 600;
            color: #2d3748;
            margin-bottom: 20px;
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .cycle-timeline {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }

        .cycle-timeline-card {
            border-radius: 12px;
            padding: 20px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            transition: transform 0.2s ease;
        }

        .cycle-timeline-card:hover {
            transform: translateY(-2px);
        }

        .cycle-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 15px;
        }

        .cycle-title {
            font-size: 1.1rem;
            font-weight: 600;
            color: #2d3748;
        }

        .cycle-duration {
            background: #667eea;
            color: white;
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 0.8rem;
            font-weight: 500;
        }

        .cycle-dates {
            margin-bottom: 15px;
        }

        .date-item {
            display: flex;
            justify-content: space-between;
            margin-bottom: 5px;
        }

        .date-label {
            font-size: 0.9rem;
            color: #4a5568;
        }

        .date-value {
            font-size: 0.9rem;
            font-weight: 500;
            color: #2d3748;
        }

        .cycle-blocks {
            border-top: 1px solid rgba(0, 0, 0, 0.1);
            padding-top: 15px;
        }

        .blocks-header {
            display: flex;
            align-items: center;
            gap: 8px;
            margin-bottom: 10px;
            font-size: 0.9rem;
            font-weight: 500;
            color: #4a5568;
        }

        .blocks-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
            gap: 8px;
        }

        .block-item {
            background: rgba(255, 255, 255, 0.7);
            border-radius: 6px;
            padding: 8px;
            text-align: center;
            border: 1px solid rgba(0, 0, 0, 0.1);
        }

        .block-title {
            font-size: 0.8rem;
            font-weight: 500;
            color: #2d3748;
            margin-bottom: 2px;
        }

        .block-duration {
            font-size: 0.7rem;
            color: #667eea;
            font-weight: 600;
        }

        /* Legend */
        .legend {
            background: #f7fafc;
            border-radius: 12px;
            padding: 20px;
            border: 1px solid #e2e8f0;
        }

        .legend-title {
            font-size: 1rem;
            font-weight: 600;
            color: #2d3748;
            margin-bottom: 15px;
        }

        .legend-items {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 10px;
        }

        .legend-item {
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .legend-color {
            width: 20px;
            height: 20px;
            border-radius: 4px;
        }

        /* Cycle Details Section */
        .cycle-details-section {
            padding: 30px;
            background: #f8fafc;
        }

        .cycle-details {
            display: flex;
            flex-direction: column;
            gap: 25px;
        }

        .cycle-detail-card {
            background: white;
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .cycle-detail-header {
            padding: 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .cycle-detail-header h3 {
            font-size: 1.2rem;
            font-weight: 600;
            color: #2d3748;
        }

        .cycle-meta {
            display: flex;
            gap: 10px;
        }

        .cycle-duration-badge,
        .cycle-blocks-badge {
            background: rgba(255, 255, 255, 0.8);
            color: #2d3748;
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 0.8rem;
            font-weight: 500;
        }

        .cycle-description {
            padding: 0 20px 20px;
            color: #4a5568;
            font-size: 0.9rem;
            line-height: 1.5;
        }

        .blocks-table-container {
            overflow-x: auto;
        }

        .blocks-table {
            width: 100%;
            border-collapse: collapse;
        }

        .blocks-table th {
            background: #f7fafc;
            color: #2d3748;
            font-weight: 600;
            padding: 12px;
            text-align: left;
            border-bottom: 2px solid #e2e8f0;
            font-size: 0.9rem;
        }

        .blocks-table td {
            padding: 12px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 0.8rem;
            color: #4a5568;
        }

        .block-name {
            font-weight: 500;
            color: #2d3748;
        }

        /* Resources Section */
        .resources-section {
            padding: 30px;
        }

        .resources-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 20px;
        }

        .resource-card {
            background: #f7fafc;
            border-radius: 12px;
            padding: 20px;
            border: 1px solid #e2e8f0;
        }

        .resource-subject {
            font-size: 1.1rem;
            font-weight: 600;
            color: #667eea;
            margin-bottom: 15px;
        }

        .resource-list {
            list-style: none;
        }

        .resource-list li {
            display: flex;
            align-items: center;
            gap: 8px;
            margin-bottom: 8px;
            font-size: 0.9rem;
            color: #4a5568;
        }

        .resource-list i {
            color: #667eea;
            width: 16px;
        }

        .resource-placeholder {
            color: #718096;
            font-style: italic;
            font-size: 0.9rem;
        }

        @page {
            size: A4;
            margin: 20mm;
        }

        @media print {
            body { 
                print-color-adjust: exact;
                -webkit-print-color-adjust: exact;
            }
            .container {
                box-shadow: none;
                border-radius: 0;
            }
        }
    </style>`;
  }

  // ===== HELPER METHODS =====


  /**
   * Get cycle description based on cycle type
   */
  private static getCycleDescription(cycle: StudyCycle): string {
    const duration = cycle.cycleDuration || 0;
    const startDate = cycle.cycleStartDate || 'TBD';
    const endDate = cycle.cycleEndDate || 'TBD';
    
    switch (cycle.cycleType) {
      case CycleType.C1:
        return `NCERT Foundation Cycle: This initial cycle focuses exclusively on NCERT textbooks to build fundamental concepts across all subjects. Duration: ${duration} weeks (${startDate} to ${endDate}).`;
      case CycleType.C2:
        return `Foundation Cycle: This cycle establishes a solid conceptual foundation across all subjects through systematic study of core topics. Duration: ${duration} weeks (${startDate} to ${endDate}).`;
      case CycleType.C3:
        return `Mains Revision Pre-Prelims Cycle: This cycle prepares you for Mains-specific requirements while maintaining focus on analytical thinking skills. Duration: ${duration} weeks (${startDate} to ${endDate}).`;
      case CycleType.C4:
        return `Prelims Reading Cycle: This cycle transitions from foundation building to exam-focused preparation with intensive reading and practice tests. Duration: ${duration} weeks (${startDate} to ${endDate}).`;
      case CycleType.C5:
        return `Prelims Revision Cycle: Intensive revision phase focusing on consolidating knowledge and practice for Prelims examination. Duration: ${duration} weeks (${startDate} to ${endDate}).`;
      case CycleType.C5B:
        return `Prelims Rapid Revision Cycle: The final sprint before Prelims examination focuses on high-yield topics and intensive practice sessions. Duration: ${duration} weeks (${startDate} to ${endDate}).`;
      case CycleType.C6:
        return `Mains Revision Cycle: This cycle focuses on comprehensive Mains examination preparation with answer writing practice and essay development. Duration: ${duration} weeks (${startDate} to ${endDate}).`;
      case CycleType.C7:
        return `Mains Rapid Revision Phase: Post-Prelims preparation shifts focus to Mains examination with intensive answer writing practice. Duration: ${duration} weeks (${startDate} to ${endDate}).`;
      case CycleType.C8:
        return `Mains Foundation Cycle: This specialized cycle provides comprehensive Mains preparation with focus on analytical thinking and answer writing skills. Duration: ${duration} weeks (${startDate} to ${endDate}).`;
      default:
        return `Study Cycle: Focused preparation phase designed to optimize learning outcomes. Duration: ${duration} weeks (${startDate} to ${endDate}).`;
    }
  }

  /**
   * Calculate block dates from cycle dates and block position
   */
  private static calculateBlockDates(_cycle: StudyCycle, block: Block, _blockIndex: number): { start: string; end: string } {
    return {
      start: block.block_start_date || 'TBD',
      end: block.block_end_date || 'TBD'
    };
  }

  /**
   * Summarize block resources for display
   */
  private static summarizeBlockResources(blockResources?: BlockResources): string[] {
    if (!blockResources) return ['No resources available'];
    
    const resourceNames: string[] = [];
    
    if (blockResources.primary_books && blockResources.primary_books.length > 0) {
      blockResources.primary_books.forEach(book => {
        resourceNames.push(book.resource_title);
      });
    }
    
    if (blockResources.supplementary_materials && blockResources.supplementary_materials.length > 0) {
      blockResources.supplementary_materials.forEach(mat => {
        resourceNames.push(mat.resource_title);
      });
    }
    
    if (blockResources.current_affairs_sources && blockResources.current_affairs_sources.length > 0) {
      blockResources.current_affairs_sources.forEach(ca => {
        resourceNames.push(ca.resource_title);
      });
    }
    
    return resourceNames.length > 0 ? resourceNames : ['Resources available'];
  }

  /**
   * Get unique subjects from study plan
   */
  private static getUniqueSubjects(studyPlan: StudyPlan): string[] {
    const subjects = new Set<string>();
    studyPlan.cycles?.forEach(cycle => {
      cycle.cycleBlocks?.forEach(block => {
        block.subjects?.forEach(subject => subjects.add(subject));
      });
    });
    return Array.from(subjects);
  }

  /**
   * Get subject name from subject code
   */
  private static getSubjectName(subjectCode: string): string {
    const subject = SubjectLoader.getSubjectByCode(subjectCode);
    return subject?.subjectName || subjectCode;
  }

  /**
   * Calculate total weeks across all cycles
   */
  private static calculateTotalWeeks(studyPlan: StudyPlan): number {
    return studyPlan.cycles?.reduce((total, cycle) => total + (cycle.cycleDuration || 0), 0) || 0;
  }

  /**
   * Count total blocks across all cycles
   */
  private static countTotalBlocks(studyPlan: StudyPlan): number {
    return studyPlan.cycles?.reduce((total, cycle) => total + (cycle.cycleBlocks?.length || 0), 0) || 0;
  }
}

export default CalendarStylePDFService;