import type { StudyPlan, StudyCycle, Block, BlockResources, StudentIntake } from '../types/models';
import { ResourceService } from './ResourceService';
import { SubjectLoader } from './SubjectLoader';
import dayjs from 'dayjs';
import puppeteer, { type PDFOptions, type Browser } from 'puppeteer';

// Color mapping for different cycle types (matching the original PDFService)
const CYCLE_TYPE_COLORS = {
  'C1': { bg: 'rgb(227, 242, 253)', border: 'rgb(59, 130, 246)' }, // Very light blue
  'C2': { bg: 'rgb(232, 245, 232)', border: 'rgb(34, 197, 94)' }, // Very light green  
  'C3': { bg: 'rgb(252, 228, 236)', border: 'rgb(236, 72, 153)' }, // Very light pink
  'C4': { bg: 'rgb(255, 235, 238)', border: 'rgb(239, 68, 68)' }, // Very light red
  'C5': { bg: 'rgb(243, 229, 245)', border: 'rgb(168, 85, 247)' }, // Very light purple
  'C6': { bg: 'rgb(225, 245, 254)', border: 'rgb(6, 182, 212)' }, // Very light cyan
  'C7': { bg: 'rgb(255, 243, 224)', border: 'rgb(245, 158, 11)' }, // Very light orange
  'C8': { bg: 'rgb(241, 248, 233)', border: 'rgb(132, 204, 22)' }, // Very light lime
} as const;

/**
 * High-fidelity PDF generation service using Puppeteer
 * Provides both structured (Word-like) and visual (chart-based) PDF generation with superior quality
 */
export class HighFidelityPDFService {
  
  /**
   * Generate structured PDF that matches Word document format with high-fidelity rendering
   * This is the RECOMMENDED method for professional study plan PDFs
   */
  public static async generateStructuredPDF(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    filename?: string
  ): Promise<void> {
    try {
      // Create high-quality HTML template
      const htmlContent = await this.createStructuredHTML(studyPlan, studentIntake);
      
      // Generate PDF using Puppeteer
      const pdfBuffer = await this.generatePDFFromHTML(htmlContent, {
        format: 'A4',
        printBackground: true,
        margin: { top: '20px', right: '30px', bottom: '20px', left: '30px' },
        preferCSSPageSize: false,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `
          <div style="font-size: 10px; text-align: center; width: 100%; color: #666; margin: 0 15px;">
            <span class="title"></span> - Generated by Helios Study Planner on ${new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })} - Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </div>
        `
      });
      
      // Save the PDF
      await this.savePDF(pdfBuffer, filename || `study-plan-${studyPlan.study_plan_id || 'plan'}.pdf`);
      
    } catch (error) {
      console.error('Failed to generate structured PDF:', error);
      throw new Error('Structured PDF generation failed');
    }
  }

  /**
   * Generate visual PDF with charts and modern design using high-fidelity rendering
   * Use this for presentation-style PDFs with visualizations
   */
  static async generateVisualPDF(
    studyPlan: StudyPlan,
    studentIntake: StudentIntake,
    filename?: string
  ): Promise<void> {
    try {
      // Create enhanced visual HTML template
      const htmlContent = await this.createVisualHTML(studyPlan, studentIntake);
      
      // Generate PDF using Puppeteer with enhanced visual settings
      const pdfBuffer = await this.generatePDFFromHTML(htmlContent, {
        format: 'A4',
        printBackground: true,
        margin: { top: '20px', right: '30px', bottom: '20px', left: '30px' },
        preferCSSPageSize: false,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `
          <div style="font-size: 10px; text-align: center; width: 100%; color: #666; margin: 0 15px;">
            Generated by Helios Study Planner on ${new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })} - Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </div>
        `
      });
      
      // Save the PDF
      await this.savePDF(pdfBuffer, filename || `visual-study-plan-${studyPlan.study_plan_id || 'plan'}.pdf`);
      
    } catch (error) {
      console.error('Failed to generate visual PDF:', error);
      throw new Error('Visual PDF generation failed');
    }
  }

  /**
   * Main entry point - defaults to structured PDF (recommended)
   * Matches the exact interface of the original PDFService
   */
  static async generateStudyPlanPDF(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    options?: {
      filename?: string;
      type?: 'structured' | 'visual';
    }
  ): Promise<void> {
    const type = options?.type || 'structured';
    
    if (type === 'visual') {
      return this.generateVisualPDF(studyPlan, studentIntake, options?.filename);
    } else {
      return this.generateStructuredPDF(studyPlan, studentIntake, options?.filename);
    }
  }

  // ===== CORE PDF GENERATION METHODS =====

  /**
   * Generate PDF from HTML using Puppeteer with high-quality settings
   */
  private static async generatePDFFromHTML(htmlContent: string, options: PDFOptions): Promise<Buffer> {
    let browser: Browser | null = null;
    
    try {
      // Launch browser with optimized settings for PDF generation
      browser = await puppeteer.launch({
        headless: true,
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--disable-gpu',
          '--disable-web-security',
          '--disable-features=VizDisplayCompositor',
          '--run-all-compositor-stages-before-draw',
          '--disable-extensions-http-throttling'
        ],
        // Use system Chrome if available for better font rendering
        executablePath: process.env.CHROME_PATH || undefined
      });

      const page = await browser.newPage();
      
      // Set viewport for consistent rendering
      await page.setViewport({ width: 1200, height: 1600, deviceScaleFactor: 2 });
      
      // Enable better font rendering
      await page.evaluateOnNewDocument(() => {
        // Improve text rendering
        const style = document.createElement('style');
        style.innerHTML = `
          * {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            text-rendering: optimizeLegibility;
          }
        `;
        document.head.appendChild(style);
      });

      // Set content with proper encoding
      await page.setContent(htmlContent, {
        waitUntil: ['networkidle0', 'domcontentloaded'],
        timeout: 30000
      });

      // Wait for any charts or dynamic content to load
      await new Promise(resolve => setTimeout(resolve, 2000));

      // Generate PDF with high-quality settings
      const pdfBuffer = await page.pdf({
        ...options,
        preferCSSPageSize: false,
        printBackground: true
      });

      return Buffer.from(pdfBuffer);
    } finally {
      if (browser) {
        await browser.close();
      }
    }
  }

  /**
   * Save PDF to appropriate location (filesystem or browser download)
   */
  private static async savePDF(pdfBuffer: Buffer, filename: string): Promise<void> {
    if (typeof window !== 'undefined') {
      // Browser environment - trigger download
      const blob = new Blob([new Uint8Array(pdfBuffer)], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
      console.log(`📁 PDF download triggered: ${filename}`);
    } else {
      // Node.js environment - save to filesystem
      const fs = await import('fs');
      const path = await import('path');
      
      const outputDir = path.join(process.cwd(), 'generated-docs');
      
      // Ensure output directory exists
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }
      
      const outputPath = path.join(outputDir, filename);
      fs.writeFileSync(outputPath, pdfBuffer);
      
      console.log(`✅ PDF saved: ${filename}`);
      console.log(`   📁 Location: ${outputPath}`);
    }
  }

  // ===== HTML TEMPLATE GENERATION METHODS =====

  /**
   * Create structured HTML template that matches Word document format
   */
  private static async createStructuredHTML(studyPlan: StudyPlan, studentIntake: StudentIntake): Promise<string> {
    const totalWeeks = this.calculateTotalWeeks(studyPlan);
    const totalBlocks = this.countTotalBlocks(studyPlan);
    const uniqueSubjects = this.getUniqueSubjects(studyPlan);
    
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${studyPlan.plan_title || 'Study Plan'}</title>
        ${this.getStructuredCSS()}
    </head>
    <body>
        ${this.generateHeaderSection(studyPlan, studentIntake)}
        ${this.generateStudyPlanOverview(studyPlan, studentIntake, totalWeeks, totalBlocks)}
        ${this.generateStudentProfileSection(studentIntake)}
        ${this.generateStudyBlocksSection(studyPlan)}
        ${await this.generateResourcesSection(studyPlan, uniqueSubjects)}
    </body>
    </html>`;
  }

  /**
   * Create visual HTML template with charts and modern design
   */
  private static async createVisualHTML(studyPlan: StudyPlan, studentIntake: StudentIntake): Promise<string> {
    const totalWeeks = this.calculateTotalWeeks(studyPlan);
    const totalBlocks = this.countTotalBlocks(studyPlan);
    const uniqueSubjects = this.getUniqueSubjects(studyPlan);
    const subjectHours = this.calculateSubjectHours(studyPlan);
    
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${studyPlan.plan_title || 'Study Plan'}</title>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns"></script>
        ${this.getVisualCSS()}
    </head>
    <body>
        <div class="page">
            <!-- Header Section -->
            <div class="header">
                <h1>${studyPlan.plan_title || 'Comprehensive Study Plan'}</h1>
                <div class="subtitle">Strategic UPSC ${studyPlan.targeted_year || '2025'} Preparation Plan</div>
            </div>
            
            <!-- Plan Information Grid -->
            <div class="info-grid">
                <div class="info-card">
                    <h3>📋 Plan Details</h3>
                    <div class="info-item">
                        <span class="info-label">Student:</span>
                        <span class="info-value">${studentIntake.personal_details?.full_name || 'Student'}</span>
                    </div>
                    <div class="info-item">
                        <span class="info-label">Target Year:</span>
                        <span class="info-value">${studyPlan.targeted_year || '2025'}</span>
                    </div>
                    <div class="info-item">
                        <span class="info-label">Start Date:</span>
                        <span class="info-value">${studentIntake.start_date || 'TBD'}</span>
                    </div>
                    <div class="info-item">
                        <span class="info-label">Generated:</span>
                        <span class="info-value">${dayjs().format('MMMM DD, YYYY')}</span>
                    </div>
                </div>
                
                <div class="info-card">
                    <h3>📊 Plan Statistics</h3>
                    <div class="info-item">
                        <span class="info-label">Total Duration:</span>
                        <span class="info-value">${totalWeeks} weeks</span>
                    </div>
                    <div class="info-item">
                        <span class="info-label">Study Cycles:</span>
                        <span class="info-value">${studyPlan.cycles?.length || 0}</span>
                    </div>
                    <div class="info-item">
                        <span class="info-label">Study Blocks:</span>
                        <span class="info-value">${totalBlocks}</span>
                    </div>
                    <div class="info-item">
                        <span class="info-label">Subjects:</span>
                        <span class="info-value">${uniqueSubjects.length}</span>
                    </div>
                </div>
            </div>
            
            <!-- Statistics Cards -->
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-number">${totalWeeks}</div>
                    <div class="stat-label">Total Weeks</div>
                </div>
                <div class="stat-card accent">
                    <div class="stat-number">${studyPlan.cycles?.length || 0}</div>
                    <div class="stat-label">Study Cycles</div>
                </div>
                <div class="stat-card success">
                    <div class="stat-number">${totalBlocks}</div>
                    <div class="stat-label">Study Blocks</div>
                </div>
                <div class="stat-card warning">
                    <div class="stat-number">${uniqueSubjects.length}</div>
                    <div class="stat-label">Subjects</div>
                </div>
            </div>
            
            <!-- Charts Container -->
            <div class="section">
                <div class="section-header">
                    <h2 class="section-title">📊 Visual Analytics</h2>
                </div>
                
                <div class="charts-row">
                    <div class="chart-container">
                        <h3>Subjects Time Distribution</h3>
                        <canvas id="subjectsChart" width="400" height="200"></canvas>
                    </div>
                    
                    <div class="chart-container">
                        <h3>Cycles Timeline</h3>
                        <canvas id="cyclesChart" width="400" height="200"></canvas>
                    </div>
                </div>
            </div>
            
            <!-- Study Plan Cycles -->
            <div class="section">
                <div class="section-header">
                    <h2 class="section-title">🗓️ Study Plan by Cycles</h2>
                </div>
                
                ${this.generateCyclesHTML(studyPlan)}
            </div>
            
            <!-- Footer -->
            <div class="footer">
                <div class="footer-content">
                    <div class="footer-left">
                        Generated on ${dayjs().format('MMMM DD, YYYY')} | Helios Study Planner
                    </div>
                    <div class="footer-right">
                        Your Path to Excellence
                    </div>
                </div>
            </div>
        </div>
        
        <script>
          // Initialize charts after page load
          document.addEventListener('DOMContentLoaded', function() {
            setTimeout(() => {
              ${this.generateChartScript(uniqueSubjects, subjectHours, studyPlan)}
            }, 100);
          });
        </script>
    </body>
    </html>`;
  }

  // ===== HTML SECTION GENERATION METHODS =====

  private static generateHeaderSection(studyPlan: StudyPlan, studentIntake: StudentIntake): string {
    const startDate = dayjs(studentIntake.start_date);
    const targetYear = studyPlan.targeted_year || new Date().getFullYear() + 1;
    const planDuration = this.calculateDuration(startDate, targetYear);
    
    return `
    <div class="header">
        <h1 class="title">${studyPlan.plan_title || 'Study Plan'}</h1>
        <div class="subtitle">
            Start Date: ${startDate.format('DD/MM/YYYY')} | 
            Target Year: ${targetYear} (${planDuration})
        </div>
    </div>`;
  }

  private static generateStudyPlanOverview(
    studyPlan: StudyPlan, 
    studentIntake: StudentIntake, 
    totalWeeks: number, 
    totalBlocks: number
  ): string {
    const cycles = studyPlan.cycles || [];
    const targetYear = studyPlan.targeted_year || new Date().getFullYear() + 1;
    const studentName = studentIntake.personal_details?.full_name || 'you';
    
    const cycleDescriptions = cycles.map(cycle => {
      const cycleName = cycle.cycleName || cycle.cycleType || 'Unnamed Cycle';
      const cycleDescription = this.getCycleDescription(cycle);
      return `
        <div class="cycle-description">
            <h4>${cycleName}</h4>
            <p>${cycleDescription}</p>
        </div>
      `;
    }).join('');
    
    return `
    <div class="section">
        <h2 class="section-title">Study Plan Overview</h2>
        
        <p class="overview-text">
            This comprehensive study plan is strategically designed for ${studentName} 
            for UPSC ${targetYear} preparation, structured across multiple specialized 
            cycles to maximize learning efficiency and exam readiness.
        </p>
        
        ${cycleDescriptions}
        
        <p class="summary-text">
            The entire study journey spans ${totalWeeks} weeks across ${cycles.length} 
            specialized cycles, broken down into ${totalBlocks} focused study blocks. 
            Each cycle is carefully timed to align with UPSC examination dates and 
            optimal learning patterns.
        </p>
    </div>`;
  }

  private static generateStudentProfileSection(studentIntake: StudentIntake): string {
    const profileData = this.generateStudentProfileData(studentIntake);
    
    const profileRows = profileData.map(row => `
      <tr>
        <td class="profile-label">${row[0]}</td>
        <td class="profile-value">${row[1]}</td>
        <td class="profile-label">${row[2] || ''}</td>
        <td class="profile-value">${row[3] || ''}</td>
      </tr>
    `).join('');
    
    return `
    <div class="section">
        <h2 class="section-title">Student Profile</h2>
        
        <table class="profile-table">
            ${profileRows}
        </table>
    </div>`;
  }

  private static generateStudyBlocksSection(studyPlan: StudyPlan): string {
    if (!studyPlan.cycles) return '';
    
    const cyclesHTML = studyPlan.cycles.map(cycle => this.generateCycleTableHTML(cycle)).join('');
    
    return `
    <div class="section">
        <h2 class="section-title">Study Blocks</h2>
        ${cyclesHTML}
    </div>`;
  }

  private static generateCycleTableHTML(cycle: StudyCycle): string {
    const cycleName = cycle.cycleName || 'Untitled Cycle';
    const cycleDescription = this.getCycleDescription(cycle);
    const durationText = `Duration: ${cycle.cycleStartDate || 'TBD'} to ${cycle.cycleEndDate || 'TBD'} (${cycle.cycleDuration || 0} weeks)`;
    
    const cycleColor = CYCLE_TYPE_COLORS[cycle.cycleType as keyof typeof CYCLE_TYPE_COLORS] || 
                     { bg: 'rgb(248, 250, 252)', border: 'rgb(100, 116, 139)' };
    
    const blocksHTML = (cycle.cycleBlocks || []).map(block => {
      const blockDates = this.calculateBlockDates(cycle, block, 0);
      const durationText = `${blockDates.start} - ${blockDates.end}\n${block.duration_weeks || 0} week(s)`;
      const resourceSummary = this.summarizeBlockResources(block.block_resources);
      
      return `
        <tr style="background-color: ${cycleColor.bg};">
          <td>${block.block_title || 'Untitled'}</td>
          <td class="duration-cell">${durationText}</td>
          <td class="resources-cell">${resourceSummary}</td>
        </tr>
      `;
    }).join('');
    
    return `
    <div class="cycle-section" style="border-left: 4px solid ${cycleColor.border};">
        <h3 class="cycle-title">${cycleName}</h3>
        <p class="cycle-description">${cycleDescription}</p>
        <p class="cycle-duration">${durationText}</p>
        
        <table class="cycle-table">
            <thead>
                <tr>
                    <th>Block</th>
                    <th>Time Frame</th>
                    <th>Resources</th>
                </tr>
            </thead>
            <tbody>
                ${blocksHTML}
            </tbody>
        </table>
    </div>`;
  }

  private static async generateResourcesSection(studyPlan: StudyPlan, uniqueSubjects: string[]): Promise<string> {
    let resourcesHTML = '';
    
    // Add study plan context to the resources section
    const planTitle = studyPlan.plan_title || 'Study Plan';
    
    for (const subjectCode of uniqueSubjects.slice(0, 10)) { // Limit to prevent overwhelming
      try {
        const subjectName = this.getSubjectName(subjectCode);
        const resources = await ResourceService.getResourcesForSubject(subjectCode);
        
        const resourceNames: string[] = [];
        
        if (resources.primary_books && resources.primary_books.length > 0) {
          resources.primary_books.forEach(book => {
            resourceNames.push(`• ${book.resource_title}`);
          });
        }
        
        if (resources.current_affairs_sources && resources.current_affairs_sources.length > 0) {
          resources.current_affairs_sources.forEach(ca => {
            resourceNames.push(`• ${ca.resource_title}`);
          });
        }
        
        if (resources.practice_resources && resources.practice_resources.length > 0) {
          resources.practice_resources.forEach(practice => {
            resourceNames.push(`• ${practice.resource_title}`);
          });
        }
        
        if (resources.video_content && resources.video_content.length > 0) {
          resources.video_content.forEach(video => {
            resourceNames.push(`• ${video.resource_title}`);
          });
        }
        
        resourcesHTML += `
        <div class="subject-resources">
            <h4>${subjectName}</h4>
            <div class="resource-list">
                ${resourceNames.slice(0, 5).join('<br>')}
                ${resourceNames.length > 5 ? '<br>... and more resources available' : ''}
            </div>
        </div>`;
        
      } catch (error) {
        console.warn(`Failed to load resources for ${subjectCode}`, error);
        const subjectName = this.getSubjectName(subjectCode);
        resourcesHTML += `
        <div class="subject-resources">
            <h4>${subjectName}</h4>
            <div class="resource-list">Comprehensive resources available</div>
        </div>`;
      }
    }
    
    return `
    <div class="section">
        <h2 class="section-title">Resources</h2>
        
        <p class="resources-intro">
            This ${planTitle} covers ${uniqueSubjects.length} subjects with comprehensive 
            resource allocation. Below are the key resources for each subject:
        </p>
        
        <div class="resources-grid">
            ${resourcesHTML}
        </div>
        
        <p class="resources-summary">
            Complete resource listing for all ${uniqueSubjects.length} subjects in your ${planTitle.toLowerCase()}.
        </p>
    </div>`;
  }

  private static generateCyclesHTML(studyPlan: StudyPlan): string {
    if (!studyPlan.cycles) return '<p>No cycles available</p>';
    
    return studyPlan.cycles.map(cycle => {
      const cycleColor = CYCLE_TYPE_COLORS[cycle.cycleType as keyof typeof CYCLE_TYPE_COLORS] || 
                        { bg: 'rgb(248, 250, 252)', border: 'rgb(100, 116, 139)' };
      
      return `
        <div class="cycle-container" style="border-left: 4px solid ${cycleColor.border};">
          <div class="cycle-header" style="background: linear-gradient(135deg, ${cycleColor.border}, ${cycleColor.bg});">
            ${cycle.cycleName || cycle.cycleType} (${cycle.cycleDuration || 0} weeks)
          </div>
          <div class="cycle-content">
            ${cycle.cycleBlocks?.map(block => `
              <div class="block-item" style="background-color: ${cycleColor.bg};">
                <div class="block-title">${block.block_title || 'Untitled Block'}</div>
                <div class="block-duration">${block.duration_weeks || 0} weeks</div>
                <div class="block-subjects">${block.subjects?.join(', ') || 'No subjects'}</div>
                <div class="progress-bar">
                  <div class="progress-fill" style="width: ${Math.random() * 100}%; background: ${cycleColor.border};"></div>
                </div>
              </div>
            `).join('') || '<p>No blocks in this cycle</p>'}
          </div>
        </div>
      `;
    }).join('');
  }

  private static generateChartScript(uniqueSubjects: string[], subjectHours: Record<string, number>, studyPlan: StudyPlan): string {
    const chartColors = [
      '#2563eb', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', 
      '#06b6d4', '#ec4899', '#6366f1', '#14b8a6', '#f97316'
    ];
    
    const subjectData = uniqueSubjects.map(subject => subjectHours[subject] || 0);
    const subjectColors = uniqueSubjects.map((_, index) => chartColors[index % chartColors.length]);
    
    const cycleNames = studyPlan.cycles?.map(cycle => cycle.cycleName || cycle.cycleType || 'Cycle') || [];
    const cycleDurations = studyPlan.cycles?.map(cycle => cycle.cycleDuration || 0) || [];
    
    return `
      // Subjects pie chart
      const subjectsCtx = document.getElementById('subjectsChart');
      if (subjectsCtx) {
        new Chart(subjectsCtx, {
          type: 'pie',
          data: {
            labels: ${JSON.stringify(uniqueSubjects)},
            datasets: [{
              data: ${JSON.stringify(subjectData)},
              backgroundColor: ${JSON.stringify(subjectColors)},
              borderWidth: 2,
              borderColor: '#ffffff'
            }]
          },
          options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
              legend: {
                position: 'right',
                labels: {
                  font: { family: 'Inter, sans-serif', size: 10 }
                }
              }
            }
          }
        });
      }
      
      // Cycles timeline chart
      const cyclesCtx = document.getElementById('cyclesChart');
      if (cyclesCtx) {
        new Chart(cyclesCtx, {
          type: 'bar',
          data: {
            labels: ${JSON.stringify(cycleNames)},
            datasets: [{
              label: 'Duration (Weeks)',
              data: ${JSON.stringify(cycleDurations)},
              backgroundColor: '#2563eb',
              borderColor: '#1d4ed8',
              borderWidth: 1
            }]
          },
          options: {
            indexAxis: 'y',
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
              legend: { display: false }
            },
            scales: {
              x: {
                beginAtZero: true,
                title: { display: true, text: 'Weeks' }
              }
            }
          }
        });
      }
    `;
  }

  // ===== CSS GENERATION METHODS =====

  private static getStructuredCSS(): string {
    return `
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
      
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        text-rendering: optimizeLegibility;
      }
      
      body {
        font-family: 'Inter', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        font-size: 11px;
        line-height: 1.6;
        color: #1e293b;
        background: white;
        padding: 10px;
        margin: 0;
      }
      
      .header {
        text-align: center;
        margin-bottom: 30px;
        padding: 20px 0;
        border-bottom: 3px solid #2563eb;
      }
      
      .title {
        font-size: 24px;
        font-weight: 800;
        color: #1e40af;
        margin-bottom: 10px;
        letter-spacing: -0.025em;
      }
      
      .subtitle {
        font-size: 14px;
        font-weight: 400;
        color: #64748b;
        font-style: italic;
      }
      
      .section {
        margin-bottom: 30px;
        page-break-inside: avoid;
      }
      
      .section-title {
        font-size: 16px;
        font-weight: 700;
        color: #1e40af;
        margin-bottom: 15px;
        padding-bottom: 5px;
        border-bottom: 2px solid #e2e8f0;
      }
      
      .overview-text, .summary-text {
        font-size: 11px;
        line-height: 1.6;
        color: #374151;
        margin-bottom: 15px;
        text-align: justify;
      }
      
      .cycle-description {
        margin-bottom: 15px;
        padding: 10px;
        background-color: #f8fafc;
        border-left: 3px solid #3b82f6;
      }
      
      .cycle-description h4 {
        font-size: 12px;
        font-weight: 600;
        color: #1e40af;
        margin-bottom: 5px;
      }
      
      .cycle-description p {
        font-size: 10px;
        color: #4b5563;
        line-height: 1.5;
      }
      
      .profile-table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
        font-size: 10px;
      }
      
      .profile-table td {
        padding: 8px;
        border: 1px solid #e5e7eb;
        vertical-align: top;
      }
      
      .profile-label {
        font-weight: 600;
        color: #374151;
        background-color: #f9fafb;
        width: 25%;
      }
      
      .profile-value {
        color: #1f2937;
        width: 25%;
      }
      
      .cycle-section {
        margin-bottom: 25px;
        padding-left: 15px;
        page-break-inside: avoid;
      }
      
      .cycle-title {
        font-size: 14px;
        font-weight: 700;
        color: #1e40af;
        margin-bottom: 8px;
      }
      
      .cycle-description {
        font-size: 10px;
        color: #4b5563;
        margin-bottom: 5px;
        line-height: 1.5;
      }
      
      .cycle-duration {
        font-size: 10px;
        color: #6b7280;
        margin-bottom: 10px;
        font-style: italic;
      }
      
      .cycle-table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
        font-size: 10px;
      }
      
      .cycle-table th {
        background-color: #1e40af;
        color: white;
        padding: 8px;
        font-weight: 600;
        text-align: left;
        border: 1px solid #1e40af;
      }
      
      .cycle-table td {
        padding: 8px;
        border: 1px solid #e5e7eb;
        vertical-align: top;
        line-height: 1.4;
      }
      
      .duration-cell {
        white-space: pre-line;
        font-size: 9px;
        width: 20%;
      }
      
      .resources-cell {
        font-size: 9px;
        line-height: 1.3;
        width: 50%;
      }
      
      .resources-intro {
        font-size: 11px;
        color: #374151;
        margin-bottom: 15px;
      }
      
      .resources-grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 15px;
        margin-bottom: 15px;
      }
      
      .subject-resources {
        background-color: #f8fafc;
        padding: 10px;
        border-radius: 6px;
        border-left: 3px solid #3b82f6;
      }
      
      .subject-resources h4 {
        font-size: 11px;
        font-weight: 600;
        color: #1e40af;
        margin-bottom: 5px;
      }
      
      .resource-list {
        font-size: 9px;
        color: #4b5563;
        line-height: 1.4;
      }
      
      .resources-summary {
        font-size: 10px;
        color: #6b7280;
        font-style: italic;
        text-align: center;
      }
      
      @page {
        size: A4;
      }
      
      @media print {
        body { print-color-adjust: exact; }
        .section { page-break-inside: avoid; }
        .cycle-section { page-break-inside: avoid; }
      }
    </style>`;
  }

  private static getVisualCSS(): string {
    return `
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
      
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        text-rendering: optimizeLegibility;
      }
      
      body {
        font-family: 'Inter', sans-serif;
        font-size: 12px;
        line-height: 1.6;
        color: #1e293b;
        background: #f8fafc;
        padding: 10px;
        margin: 0;
      }
      
      .page {
        width: 210mm;
        min-height: 297mm;
        background: white;
        padding: 0;
      }
      
      .header {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        padding: 30px 25px;
        text-align: center;
      }
      
      .header h1 {
        font-size: 2.5em;
        font-weight: 800;
        margin-bottom: 8px;
        letter-spacing: -0.02em;
      }
      
      .header .subtitle {
        font-size: 1.1em;
        font-weight: 300;
        opacity: 0.9;
      }
      
      .info-grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 20px;
        padding: 25px;
        margin-bottom: 15px;
      }
      
      .info-card {
        background: white;
        border: 1px solid #e2e8f0;
        border-radius: 8px;
        padding: 18px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      }
      
      .info-card h3 {
        color: #2563eb;
        font-weight: 600;
        margin-bottom: 12px;
        font-size: 1.0em;
      }
      
      .info-item {
        display: flex;
        justify-content: space-between;
        margin-bottom: 6px;
        padding: 6px 0;
        border-bottom: 1px solid #f1f5f9;
      }
      
      .info-label {
        font-weight: 500;
        color: #64748b;
        font-size: 0.9em;
      }
      
      .info-value {
        font-weight: 600;
        color: #1e293b;
        font-size: 0.9em;
      }
      
      .stats-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 12px;
        padding: 0 25px;
        margin-bottom: 25px;
      }
      
      .stat-card {
        background: white;
        border-radius: 8px;
        padding: 16px;
        text-align: center;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        border-left: 3px solid #2563eb;
      }
      
      .stat-card.accent { border-left-color: #06b6d4; }
      .stat-card.success { border-left-color: #10b981; }
      .stat-card.warning { border-left-color: #f59e0b; }
      
      .stat-number {
        font-size: 2.0em;
        font-weight: 800;
        color: #2563eb;
        margin-bottom: 4px;
      }
      
      .stat-label {
        font-size: 0.8em;
        color: #64748b;
        font-weight: 500;
      }
      
      .section {
        margin: 30px 25px;
      }
      
      .section-header {
        margin-bottom: 15px;
        padding-bottom: 8px;
        border-bottom: 2px solid #e2e8f0;
      }
      
      .section-title {
        font-size: 1.4em;
        font-weight: 700;
        color: #0f172a;
      }
      
      .charts-row {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 15px;
        margin-bottom: 15px;
      }
      
      .chart-container {
        background: white;
        border: 1px solid #e2e8f0;
        border-radius: 8px;
        padding: 15px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      }
      
      .chart-container h3 {
        color: #2563eb;
        font-weight: 600;
        margin-bottom: 12px;
        text-align: center;
        font-size: 1.0em;
      }
      
      .chart-container canvas {
        max-width: 100% !important;
        height: 200px !important;
      }
      
      .cycle-container {
        margin-bottom: 20px;
      }
      
      .cycle-header {
        background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
        color: white;
        padding: 12px 15px;
        border-radius: 6px 6px 0 0;
        font-weight: 600;
        font-size: 1.0em;
      }
      
      .cycle-content {
        background: white;
        border: 1px solid #e2e8f0;
        border-top: none;
        border-radius: 0 0 6px 6px;
      }
      
      .block-item {
        padding: 12px 15px;
        border-bottom: 1px solid #f1f5f9;
        display: grid;
        grid-template-columns: 2fr 0.8fr 1fr 1.5fr;
        gap: 12px;
        align-items: center;
        font-size: 0.9em;
      }
      
      .block-title {
        font-weight: 600;
        color: #1e293b;
      }
      
      .block-duration {
        background: #06b6d4;
        color: white;
        padding: 3px 10px;
        border-radius: 15px;
        font-size: 0.8em;
        font-weight: 600;
        text-align: center;
      }
      
      .block-subjects {
        color: #64748b;
        font-size: 0.85em;
      }
      
      .progress-bar {
        width: 100%;
        height: 5px;
        background: #f1f5f9;
        border-radius: 3px;
        overflow: hidden;
      }
      
      .progress-fill {
        height: 100%;
        background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
        border-radius: 3px;
      }
      
      .footer {
        background: #0f172a;
        color: white;
        padding: 15px 25px;
        margin-top: 30px;
      }
      
      .footer-content {
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-size: 0.85em;
      }
      
      .footer-left { opacity: 0.8; }
      .footer-right { font-weight: 600; }
      
      @page {
        size: A4;
      }
      
      @media print {
        body { print-color-adjust: exact; }
      }
    </style>`;
  }

  // ===== HELPER METHODS (matching original PDFService) =====

  /**
   * Generate student profile data for table - enhanced to match DOCX version
   */
  private static generateStudentProfileData(studentIntake: StudentIntake): string[][] {
    const rows: string[][] = [];
    
    // Personal Details
    if (studentIntake.personal_details) {
      const pd = studentIntake.personal_details;
      rows.push([
        'Full Name', pd.full_name || 'Not provided',
        'Email', pd.email || 'Not provided'
      ]);
      rows.push([
        'Phone', pd.phone_number || 'Not provided',
        'Location', pd.present_location || 'Not provided'
      ]);
      rows.push([
        'Student Type', pd.student_archetype || 'Not provided',
        'Graduation Stream', pd.graduation_stream || 'Not provided'
      ]);
      if (pd.college_university) {
        rows.push([
          'College/University', pd.college_university,
          'Year of Passing', pd.year_of_passing?.toString() || 'Not provided'
        ]);
      }
    }
    
    // Preparation Background
    if (studentIntake.preparation_background) {
      const pb = studentIntake.preparation_background;
      rows.push([
        'Preparing Since', pb.preparing_since || 'Not provided',
        'Number of Attempts', pb.number_of_attempts || 'Not provided'
      ]);
      rows.push([
        'Highest Stage Reached', pb.highest_stage_per_attempt || 'Not provided',
        'Previous Prelims Score', pb.last_attempt_gs_prelims_score > 0 ? pb.last_attempt_gs_prelims_score.toString() : 'N/A'
      ]);
      rows.push([
        'CSAT Score', pb.last_attempt_csat_score > 0 ? pb.last_attempt_csat_score.toString() : 'N/A',
        'Wrote Mains', pb.wrote_mains_in_last_attempt || 'Not provided'
      ]);
    }
    
    // Study Strategy
    if (studentIntake.study_strategy) {
      const ss = studentIntake.study_strategy;
      rows.push([
        'Weekly Study Hours', ss.weekly_study_hours || 'Not provided',
        'Study Approach', ss.study_approach || 'Not provided'
      ]);
      rows.push([
        'Focus Combination', ss.study_focus_combo || 'Not provided',
        'Time Distribution', ss.time_distribution || 'Balanced'
      ]);
      rows.push([
        'Revision Strategy', ss.revision_strategy || 'Weekly',
        'Test Frequency', ss.test_frequency || 'Monthly'
      ]);
      if (ss.catch_up_day_preference) {
        rows.push([
          'Preferred Catch-up Day', ss.catch_up_day_preference,
          'Seasonal Windows', ss.seasonal_windows ? ss.seasonal_windows.join(', ') : 'Not specified'
        ]);
      }
    }
    
    // Current Status and Confidence
    if (studentIntake.subject_confidence && Object.keys(studentIntake.subject_confidence).length > 0) {
      const subjects = Object.entries(studentIntake.subject_confidence);
      const subjectStrings = subjects.map(([code, level]) => `${code}:${level}`);
      const midPoint = Math.ceil(subjectStrings.length / 2);
      
      rows.push([
        'Subject Confidence (Part 1)', subjectStrings.slice(0, midPoint).join(', '),
        'Subject Confidence (Part 2)', subjectStrings.slice(midPoint).join(', ')
      ]);
    }
    
    // Target Year and Exam Details
    rows.push([
      'Target Year', studentIntake.target_year || 'Not provided',
      'Plan Start Date', studentIntake.start_date || 'Not provided'
    ]);
    
    // Optional Subject
    if (studentIntake.optional_subject) {
      const os = studentIntake.optional_subject;
      rows.push([
        'Optional Subject', os.optional_subject_name || 'Not selected',
        'Optional Status', os.optional_status || 'Not assessed'
      ]);
    }
    
    return rows;
  }

  /**
   * Get cycle description based on cycle type
   */
  private static getCycleDescription(cycle: StudyCycle): string {
    const duration = cycle.cycleDuration || 0;
    const startDate = cycle.cycleStartDate || 'TBD';
    const endDate = cycle.cycleEndDate || 'TBD';
    
    switch (cycle.cycleType) {
      case 'C1':
        return `NCERT Foundation Cycle (${startDate} to ${endDate}, ${duration} weeks): This initial cycle focuses exclusively on NCERT textbooks to build fundamental concepts across all subjects.`;
      case 'C2':
        return `Foundation Cycle (${startDate} to ${endDate}, ${duration} weeks): This cycle establishes a solid conceptual foundation across all subjects through systematic study of core topics.`;
      case 'C3':
        return `Mains Revision Pre-Prelims Cycle (${startDate} to ${endDate}, ${duration} weeks): This cycle prepares you for Mains-specific requirements while maintaining focus on study and analytical thinking skills.`;
      case 'C4':
        return `Prelims Revision Cycle (${startDate} to ${endDate}, ${duration} weeks): This cycle transitions from foundation building to exam-focused preparation with intensive revision and practice tests.`;
      case 'C5':
        return `Prelims Rapid Revision Cycle (${startDate} to ${endDate}, ${duration} weeks): The final sprint before Prelims examination focuses on high-yield topics and intensive practice sessions.`;
      case 'C6':
        return `Mains Revision Cycle (${startDate} to ${endDate}, ${duration} weeks): This cycle focuses on comprehensive Mains examination preparation with answer writing practice and essay development.`;
      case 'C7':
        return `Mains Rapid Revision Phase (${startDate} to ${endDate}, ${duration} weeks): Post-Prelims preparation shifts focus to Mains examination with intensive answer writing practice.`;
      case 'C8':
        return `Mains Foundation Cycle (${startDate} to ${endDate}, ${duration} weeks): This specialized cycle provides comprehensive Mains preparation with focus on analytical thinking and answer writing skills.`;
      default:
        return `Study Cycle (${startDate} to ${endDate}, ${duration} weeks): Focused preparation phase designed to optimize learning outcomes.`;
    }
  }

  /**
   * Calculate block dates from cycle dates and block position
   */
  private static calculateBlockDates(_cycle: StudyCycle, block: Block, _blockIndex: number): { start: string; end: string } {
    return {
      start: block.block_start_date || 'TBD',
      end: block.block_end_date || 'TBD'
    };
  }

  /**
   * Summarize block resources for table display
   */
  private static summarizeBlockResources(blockResources?: BlockResources): string {
    if (!blockResources) {
      return 'No resources specified';
    }

    const resourceNames: string[] = [];
    
    if (blockResources.primary_books && blockResources.primary_books.length > 0) {
      blockResources.primary_books.forEach(book => {
        resourceNames.push(`• ${book.resource_title}`);
      });
    }
    
    if (blockResources.supplementary_materials && blockResources.supplementary_materials.length > 0) {
      blockResources.supplementary_materials.forEach(mat => {
        resourceNames.push(`• ${mat.resource_title}`);
      });
    }
    
    if (blockResources.current_affairs_sources && blockResources.current_affairs_sources.length > 0) {
      blockResources.current_affairs_sources.forEach(ca => {
        resourceNames.push(`• ${ca.resource_title}`);
      });
    }
    
    if (resourceNames.length === 0) {
      return 'Comprehensive resources available';
    }
    
    const fullText = resourceNames.join('\n');
    const maxLength = 150;
    
    if (fullText.length > maxLength) {
      return fullText.substring(0, maxLength) + '\n... and more';
    }
    
    return fullText;
  }

  /**
   * Get unique subjects from study plan
   */
  private static getUniqueSubjects(studyPlan: StudyPlan): string[] {
    const subjects = new Set<string>();
    studyPlan.cycles?.forEach(cycle => {
      cycle.cycleBlocks?.forEach(block => {
        block.subjects?.forEach(subject => subjects.add(subject));
      });
    });
    return Array.from(subjects);
  }

  /**
   * Get subject name from subject code
   */
  private static getSubjectName(subjectCode: string): string {
    const subject = SubjectLoader.getSubjectByCode(subjectCode);
    return subject?.subjectName || subjectCode;
  }

  /**
   * Calculate total weeks across all cycles
   */
  private static calculateTotalWeeks(studyPlan: StudyPlan): number {
    return studyPlan.cycles?.reduce((total, cycle) => total + (cycle.cycleDuration || 0), 0) || 0;
  }

  /**
   * Count total blocks across all cycles
   */
  private static countTotalBlocks(studyPlan: StudyPlan): number {
    return studyPlan.cycles?.reduce((total, cycle) => total + (cycle.cycleBlocks?.length || 0), 0) || 0;
  }

  /**
   * Calculate subject hours distribution
   */
  private static calculateSubjectHours(studyPlan: StudyPlan): Record<string, number> {
    const subjectHours: Record<string, number> = {};
    const uniqueSubjects = this.getUniqueSubjects(studyPlan);
    
    uniqueSubjects.forEach(subject => {
      let totalHours = 0;
      studyPlan.cycles?.forEach(cycle => {
        cycle.cycleBlocks?.forEach(block => {
          if (block.subjects?.includes(subject)) {
            const blockHours = (block.duration_weeks || 0) * 35;
            const subjectHours = blockHours / (block.subjects?.length || 1);
            totalHours += subjectHours;
          }
        });
      });
      subjectHours[subject] = Math.round(totalHours);
    });
    
    return subjectHours;
  }

  /**
   * Calculate duration string
   */
  private static calculateDuration(startDate: dayjs.Dayjs, targetYear: number): string {
    const targetDate = dayjs(`${targetYear}-05-19`);
    
    const years = targetDate.diff(startDate, 'year');
    const months = targetDate.diff(startDate, 'month') % 12;
    const weeks = Math.floor(targetDate.diff(startDate, 'day') % 30 / 7);
    
    const parts: string[] = [];
    
    if (years > 0) {
      parts.push(`${years} year${years !== 1 ? 's' : ''}`);
    }
    if (months > 0) {
      parts.push(`${months} month${months !== 1 ? 's' : ''}`);
    }
    if (weeks > 0) {
      parts.push(`${weeks} week${weeks !== 1 ? 's' : ''}`);
    }
    
    return parts.length > 0 ? parts.join(' ') : '0 days';
  }
}

export default HighFidelityPDFService;