"""user model upgrade

Revision ID: 5baef3be3152
Revises: 5cb1af1c8d85
Create Date: 2023-07-27 11:27:42.759290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5baef3be3152'
down_revision = '5cb1af1c8d85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile_number', sa.String(), nullable=False))
    op.create_index(op.f('users_mobile_number_idx'), 'users', ['mobile_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('users_mobile_number_idx'), table_name='users')
    op.drop_column('users', 'mobile_number')
    # ### end Alembic commands ###
