"""change test model and delete attempts models

Revision ID: 7111f4fbed7b
Revises: 1ddb5eff6a01
Create Date: 2023-09-15 11:56:03.190479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7111f4fbed7b'
down_revision = '1ddb5eff6a01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testquestionattempts')
    op.add_column('testquestions', sa.Column('tq_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testquestions', 'tq_order')
    op.create_table('testquestionattempts',
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attempted_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_elapsed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('selected_options', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True),
    sa.Column('is_correct_attempt', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('marks_obtained', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_starred', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attempted_by_id'], ['users.id'], name='testquestionattempts_attempted_by_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='testquestionattempts_question_id_fkey'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name='testquestionattempts_test_id_fkey'),
    sa.PrimaryKeyConstraint('test_id', 'question_id', 'attempted_by_id', name='testquestionattempts_pkey')
    )
    # ### end Alembic commands ###
