"""revision in users

Revision ID: 8880b34fb3a9
Revises: ee05b8c6bcf1
Create Date: 2023-08-02 10:32:26.008171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8880b34fb3a9'
down_revision = 'ee05b8c6bcf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
