"""

Revision ID: 99741c170bb6
Revises: f2ae5fa0f071
Create Date: 2023-08-21 17:54:18.111999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99741c170bb6"
down_revision = "f2ae5fa0f071"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("stages", sa.ARRAY(sa.JSON()), nullable=True))
    op.drop_column("tests", "subjects")
    op.drop_column("tests", "topics")
    op.drop_column("tests", "exam")
    op.drop_column("tests", "stage")
    op.drop_column("tests", "paper")
    op.add_column("tests", sa.Column("subjects", sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column("tests", sa.Column("topics", sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column("tests", sa.Column("exam", sa.JSON(), nullable=True))
    op.add_column("tests", sa.Column("stage", sa.JSON(), nullable=True))
    op.add_column("tests", sa.Column("paper", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "stages")
    # ### end Alembic commands ###
