"""

Revision ID: 1a8265d132c1
Revises: 8a7a64546c2f
Create Date: 2023-10-13 18:16:03.679182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8265d132c1'
down_revision = '8a7a64546c2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('adjustment_amount', sa.Float(), nullable=True))
    op.add_column('subscriptions', sa.Column('auth_req_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('pg_data', sa.JSON(), nullable=True))
    op.add_column('transactions', sa.Column('pg_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'pg_data')
    op.drop_column('subscriptions', 'pg_data')
    op.drop_column('subscriptions', 'auth_req_id')
    op.drop_column('subscriptions', 'adjustment_amount')
    # ### end Alembic commands ###
