"""discount model change

Revision ID: 4f6f73c03795
Revises: 6650a231b32c
Create Date: 2023-08-12 12:44:12.987318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f6f73c03795'
down_revision = '6650a231b32c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discountcodes', 'valid_to')
    op.drop_column('discountcodes', 'valid_from')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discountcodes', sa.Column('valid_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('discountcodes', sa.Column('valid_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
