"""recurr task add sus

Revision ID: 0cda253e2d44
Revises: 3fc510a36cd7
Create Date: 2023-12-16 21:51:46.155549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cda253e2d44'
down_revision = '3fc510a36cd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('recurring_task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'recurring_task_id')
    # ### end Alembic commands ###
