"""user model upgrade

Revision ID: 5cb1af1c8d85
Revises: 522bbf8edb14
Create Date: 2023-07-27 11:27:12.953746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb1af1c8d85'
down_revision = '522bbf8edb14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('users_mobile_number_idx', table_name='users')
    op.drop_column('users', 'mobile_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('users_mobile_number_idx', 'users', ['mobile_number'], unique=False)
    # ### end Alembic commands ###
