"""user model update

Revision ID: 7e0815bd3f38
Revises: 36b319832aed
Create Date: 2023-07-28 20:55:18.184866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7e0815bd3f38"
down_revision = "36b319832aed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_email_verified", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("is_phone_verified", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_phone_verified")
    op.drop_column("users", "is_email_verified")
    # ### end Alembic commands ###
