"""record elimination tech

Revision ID: 2d37c58c3c47
Revises: 0cda253e2d44
Create Date: 2023-12-22 13:36:49.078334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d37c58c3c47'
down_revision = '0cda253e2d44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testattempts', sa.Column('record_elimination', sa.Boolean(), nullable=True))
    op.add_column('testquestionattempts', sa.Column('elimination_technique', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testquestionattempts', 'elimination_technique')
    op.drop_column('testattempts', 'record_elimination')
    # ### end Alembic commands ###
