"""free trial and test attempts count fields added

Revision ID: a05254b48ad6
Revises: c1c1bf40cd78
Create Date: 2023-09-21 13:51:18.283934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a05254b48ad6"
down_revision = "c1c1bf40cd78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("free_trial_used", sa.Boolean(), nullable=True))
    op.add_column(
        "users", sa.Column("test_attempts_count", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "test_attempts_count")
    op.drop_column("users", "free_trial_used")
    # ### end Alembic commands ###
