"""QuestionFavorite table added

Revision ID: 9e9b8d2fe0fd
Revises: b82cf875628a
Create Date: 2023-11-06 12:17:43.693468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e9b8d2fe0fd"
down_revision = "b82cf875628a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questionfavorites",
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("marked_by_id", sa.Integer(), nullable=True),
        sa.Column("is_favorite", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["marked_by_id"],
            ["users.id"],
            name=op.f("questionfavorites_marked_by_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("questionfavorites_question_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("questionfavorites_pkey")),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("questionfavorites")
    # ### end Alembic commands ###
