"""added testquestionattempt

Revision ID: 93c347fa64d6
Revises: cbfaa58d66ea
Create Date: 2023-08-26 09:11:49.989522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "93c347fa64d6"
down_revision = "cbfaa58d66ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("testquestionattempts")
    op.create_table(
        "testquestionattempts",
        sa.Column("test_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("attempted_by_id", sa.Integer(), nullable=False),
        sa.Column("time_elapsed", sa.Float(), nullable=True),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("selected_options", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("is_correct_attempt", sa.Boolean(), nullable=True),
        sa.Column("marks_obtained", sa.Float(), nullable=True),
        sa.Column("is_starred", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempted_by_id"],
            ["users.id"],
            name=op.f("testquestionattempts_attempted_by_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("testquestionattempts_question_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["test_id"], ["tests.id"], name=op.f("testquestionattempts_test_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "test_id",
            "question_id",
            "attempted_by_id",
            name=op.f("testquestionattempts_pkey"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("testquestionattempts")
    # ### end Alembic commands ###
