"""free_trial added for subs

Revision ID: 3faf692aa783
Revises: 736b4578a6ff
Create Date: 2023-10-28 07:57:23.923862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3faf692aa783'
down_revision = '736b4578a6ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('free_trial', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'free_trial')
    # ### end Alembic commands ###
