"""

Revision ID: ee05b8c6bcf1
Revises: c43460b505f6
Create Date: 2023-08-02 01:45:00.922224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee05b8c6bcf1'
down_revision = 'c43460b505f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'profile_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profiles', 'profile_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
