"""create_test_and_question_models

Revision ID: b1f811474263
Revises: a58894b28e8b
Create Date: 2023-08-21 19:13:16.227567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1f811474263"
down_revision = "a58894b28e8b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("testquestionattempts")
    op.drop_table("testshares")
    op.drop_table("testquestions")
    op.drop_table("testattempts")
    op.drop_index(op.f("tests_title_idx"), table_name="tests")
    op.drop_table("tests")
    op.drop_table("questions")
    op.create_table(
        "questions",
        sa.Column("tenant", sa.String(), nullable=True),
        sa.Column("question_type", sa.String(), nullable=True),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("options", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("is_multi", sa.Boolean(), nullable=True),
        sa.Column("question_form", sa.String(), nullable=True),
        sa.Column("model_solution", sa.Text(), nullable=True),
        sa.Column("cms_id", sa.Integer(), nullable=True),
        sa.Column("exams", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("stages", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("papers", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("subjects", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("topics", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("source", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("difficulty_level", sa.String(), nullable=True),
        sa.Column("reference_material", sa.Text(), nullable=True),
        sa.Column("publishing_status", sa.String(), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("questions_pkey")),
    )
    op.create_table(
        "tests",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("exam", sa.JSON(), nullable=False),
        sa.Column("stage", sa.JSON(), nullable=True),
        sa.Column("paper", sa.JSON(), nullable=True),
        sa.Column("test_size", sa.Integer(), nullable=True),
        sa.Column("max_duration", sa.Float(), nullable=True),
        sa.Column("max_marks", sa.Integer(), nullable=True),
        sa.Column("test_questions_count", sa.Integer(), nullable=True),
        sa.Column("attempts_count", sa.Integer(), nullable=True),
        sa.Column("subjects", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("topics", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("include_prev_year", sa.Boolean(), nullable=True),
        sa.Column("include_attempted", sa.Boolean(), nullable=True),
        sa.Column("difficulty_level", sa.String(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("is_recommended", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("test_status", sa.String(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("avg_score", sa.Float(), nullable=True),
        sa.Column("max_score", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("tests_created_by_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("tests_tenant_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tests_pkey")),
    )
    op.create_index(op.f("tests_title_idx"), "tests", ["title"], unique=False)
    op.create_table(
        "testattempts",
        sa.Column("test_id", sa.Integer(), nullable=True),
        sa.Column("attempted_by", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("time_elapsed", sa.Float(), nullable=True),
        sa.Column("correct", sa.Integer(), nullable=True),
        sa.Column("incorrect", sa.Integer(), nullable=True),
        sa.Column("unattempted", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempted_by"], ["users.id"], name=op.f("testattempts_attempted_by_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["test_id"], ["tests.id"], name=op.f("testattempts_test_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("testattempts_pkey")),
    )
    op.create_table(
        "testquestions",
        sa.Column("test_id", sa.Integer(), nullable=True),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("correct_attempts_percent", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("testquestions_question_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["test_id"], ["tests.id"], name=op.f("testquestions_test_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("testquestions_pkey")),
    )
    op.create_table(
        "testshares",
        sa.Column("test_id", sa.Integer(), nullable=True),
        sa.Column("shared_with_id", sa.Integer(), nullable=True),
        sa.Column("shared_by_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["shared_by_id"], ["users.id"], name=op.f("testshares_shared_by_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["shared_with_id"],
            ["users.id"],
            name=op.f("testshares_shared_with_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["test_id"], ["tests.id"], name=op.f("testshares_test_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("testshares_pkey")),
    )
    op.create_table(
        "testquestionattempts",
        sa.Column("test_id", sa.Integer(), nullable=True),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("attempted_by", sa.Integer(), nullable=True),
        sa.Column("time_elapsed", sa.Float(), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("marks_obtained", sa.Float(), nullable=True),
        sa.Column("report", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("is_starred", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempted_by"],
            ["users.id"],
            name=op.f("testquestionattempts_attempted_by_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["testquestions.id"],
            name=op.f("testquestionattempts_question_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["test_id"], ["tests.id"], name=op.f("testquestionattempts_test_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("testquestionattempts_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("testquestionattempts")
    op.drop_table("testshares")
    op.drop_table("testquestions")
    op.drop_table("testattempts")
    op.drop_index(op.f("tests_title_idx"), table_name="tests")
    op.drop_table("tests")
    op.drop_table("questions")
    # ### end Alembic commands ###
