"""tenant id addition in plan and discount

Revision ID: 736b4578a6ff
Revises: 2cca6320d0a3
Create Date: 2023-10-27 16:03:23.890788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736b4578a6ff'
down_revision = '2cca6320d0a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discountcodes', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('discountcodes_tenant_id_fkey'), 'discountcodes', 'tenants', ['tenant_id'], ['id'])
    op.add_column('plans', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('plans_tenant_id_fkey'), 'plans', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('plans_tenant_id_fkey'), 'plans', type_='foreignkey')
    op.drop_column('plans', 'tenant_id')
    op.drop_constraint(op.f('discountcodes_tenant_id_fkey'), 'discountcodes', type_='foreignkey')
    op.drop_column('discountcodes', 'tenant_id')
    # ### end Alembic commands ###
