"""

Revision ID: 2d0bdfdf5e63
Revises: f4f6da8c58a6
Create Date: 2023-08-11 11:02:31.162278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2d0bdfdf5e63"
down_revision = "f4f6da8c58a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("discountcodes", sa.Column("currency", sa.String(), nullable=True))
    op.add_column(
        "discountcodes", sa.Column("applicable_plan_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "discountcodes_applied_plan_id_fkey", "discountcodes", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("discountcodes_applicable_plan_id_fkey"),
        "discountcodes",
        "plans",
        ["applicable_plan_id"],
        ["id"],
    )
    op.drop_column("discountcodes", "applied_plan_id")
    op.add_column("plans", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("plans", sa.Column("base_price", sa.Float(), nullable=True))
    op.add_column("plans", sa.Column("total_price", sa.Float(), nullable=True))
    op.add_column("plans", sa.Column("currency", sa.String(), nullable=True))
    op.drop_column("plans", "price")
    op.add_column("subscriptions", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column(
        "subscriptions", sa.Column("discount_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "subscriptions", sa.Column("subscription_amount", sa.Float(), nullable=True)
    )
    op.add_column("subscriptions", sa.Column("currency", sa.String(), nullable=True))
    op.add_column("subscriptions", sa.Column("auto_renew", sa.Boolean(), nullable=True))
    op.add_column(
        "subscriptions", sa.Column("recurring_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "subscriptions", sa.Column("payment_status", sa.String(), nullable=True)
    )
    op.add_column("subscriptions", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column(
        "subscriptions", sa.Column("subscription_status", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        op.f("subscriptions_discount_id_fkey"),
        "subscriptions",
        "discountcodes",
        ["discount_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("subscriptions_user_id_fkey"),
        "subscriptions",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_column("subscriptions", "status")
    op.add_column(
        "transactions", sa.Column("subscription_id", sa.Integer(), nullable=True)
    )
    op.add_column("transactions", sa.Column("currency", sa.String(), nullable=True))
    op.drop_constraint("transactions_item_fkey", "transactions", type_="foreignkey")
    op.drop_column("transactions", "paid_to")
    op.add_column("transactions", sa.Column("paid_to", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("transactions_paid_to_fkey"), "transactions", "users", ["paid_to"], ["id"]
    )
    op.create_foreign_key(
        op.f("transactions_subscription_id_fkey"),
        "transactions",
        "subscriptions",
        ["subscription_id"],
        ["id"],
    )
    op.drop_column("transactions", "item")
    op.drop_column("users", "subscription")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "subscription",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column("item", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        op.f("transactions_subscription_id_fkey"), "transactions", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("transactions_paid_to_fkey"), "transactions", type_="foreignkey"
    )
    op.create_foreign_key(
        "transactions_item_fkey", "transactions", "plans", ["item"], ["id"]
    )
    op.drop_column("transactions", "currency")
    op.drop_column("transactions", "subscription_id")
    op.add_column(
        "subscriptions",
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        op.f("subscriptions_user_id_fkey"), "subscriptions", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("subscriptions_discount_id_fkey"), "subscriptions", type_="foreignkey"
    )
    op.drop_column("subscriptions", "subscription_status")
    op.drop_column("subscriptions", "is_active")
    op.drop_column("subscriptions", "payment_status")
    op.drop_column("subscriptions", "recurring_count")
    op.drop_column("subscriptions", "auto_renew")
    op.drop_column("subscriptions", "currency")
    op.drop_column("subscriptions", "subscription_amount")
    op.drop_column("subscriptions", "discount_id")
    op.drop_column("subscriptions", "user_id")
    op.add_column(
        "plans",
        sa.Column(
            "price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("plans", "currency")
    op.drop_column("plans", "total_price")
    op.drop_column("plans", "base_price")
    op.drop_column("plans", "description")
    op.add_column(
        "discountcodes",
        sa.Column("applied_plan_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        op.f("discountcodes_applicable_plan_id_fkey"),
        "discountcodes",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "discountcodes_applied_plan_id_fkey",
        "discountcodes",
        "plans",
        ["applied_plan_id"],
        ["id"],
    )
    op.drop_column("discountcodes", "applicable_plan_id")
    op.drop_column("discountcodes", "currency")
    # ### end Alembic commands ###
