"""tenant id relation

Revision ID: fb0c4e561b6b
Revises: 180fee2c75eb
Create Date: 2023-07-27 11:09:26.265362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0c4e561b6b'
down_revision = '180fee2c75eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_tenant_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('users', 'tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tenant', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key('users_tenant_fkey', 'users', 'tenants', ['tenant'], ['id'])
    op.drop_column('users', 'tenant_id')
    # ### end Alembic commands ###
