"""remove_purchasetxs

Revision ID: 7640d4e6fff2
Revises: 137c3432eafd
Create Date: 2024-10-24 17:24:49.270567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7640d4e6fff2'
down_revision = '137c3432eafd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchasetransactions')
    op.add_column('purchases', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('purchases', sa.Column('additional_discount_id', sa.Integer(), nullable=True))
    op.add_column('purchases', sa.Column('additional_disc_amt', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('purchases_additional_discount_id_fkey'), 'purchases', 'discountcodes', ['additional_discount_id'], ['id'])
    op.drop_column('purchases', 'purchase_amount')
    op.add_column('transactions', sa.Column('tx_data', sa.JSON(), nullable=True))
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('walkins', sa.Column('admission_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('walkins_admission_id_fkey'), 'walkins', 'admissions', ['admission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('walkins_admission_id_fkey'), 'walkins', type_='foreignkey')
    op.drop_column('walkins', 'admission_id')
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('transactions', 'tx_data')
    op.add_column('purchases', sa.Column('purchase_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('purchases_additional_discount_id_fkey'), 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'additional_disc_amt')
    op.drop_column('purchases', 'additional_discount_id')
    op.drop_column('purchases', 'amount')
    op.create_table('purchasetransactions',
    sa.Column('tx_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paid_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tx_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tx_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], name='purchasetransactions_paid_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='purchasetransactions_pkey')
    )
    # ### end Alembic commands ###
