"""discount_code_product_addition

Revision ID: 137c3432eafd
Revises: 6bd453263148
Create Date: 2024-10-17 12:09:54.050649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137c3432eafd'
down_revision = '6bd453263148'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discountcodes', sa.Column('applicable_product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('discountcodes_applicable_product_id_fkey'), 'discountcodes', 'products', ['applicable_product_id'], ['id'])
    op.add_column('purchases', sa.Column('discount_id', sa.Integer(), nullable=True))
    op.add_column('purchases', sa.Column('discount_amount', sa.Integer(), nullable=True))
    op.add_column('purchases', sa.Column('purchase_amount', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('purchases_discount_id_fkey'), 'purchases', 'discountcodes', ['discount_id'], ['id'])
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('purchases_discount_id_fkey'), 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'purchase_amount')
    op.drop_column('purchases', 'discount_amount')
    op.drop_column('purchases', 'discount_id')
    op.drop_constraint(op.f('discountcodes_applicable_product_id_fkey'), 'discountcodes', type_='foreignkey')
    op.drop_column('discountcodes', 'applicable_product_id')
    # ### end Alembic commands ###
