"""changing_of_offering_link_to_papers_exams_stage 

Revision ID: d40bfec5e8ab
Revises: 0228ec6acb36
Create Date: 2024-12-04 11:52:13.908941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd40bfec5e8ab'
down_revision = '0228ec6acb36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offerings', sa.Column('exams', postgresql.ARRAY(sa.JSON()), nullable=True))
    op.add_column('offerings', sa.Column('stages', postgresql.ARRAY(sa.JSON()), nullable=True))
    op.add_column('offerings', sa.Column('papers', postgresql.ARRAY(sa.JSON()), nullable=True))
    op.drop_column('offerings', 'paper')
    op.drop_column('offerings', 'stage')
    op.drop_column('offerings', 'exam')
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('offerings', sa.Column('exam', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('offerings', sa.Column('stage', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('offerings', sa.Column('paper', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('offerings', 'papers')
    op.drop_column('offerings', 'stages')
    op.drop_column('offerings', 'exams')
    # ### end Alembic commands ###
