"""freeplan in subs

Revision ID: af413c384ea3
Revises: a1e0554300f7
Create Date: 2024-02-01 11:28:10.696450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "af413c384ea3"
down_revision = "a1e0554300f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("free_plan", sa.Boolean(), nullable=True))
    op.alter_column(
        "tests",
        "daily_test_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "users", "free_trial_used", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "free_trial_used", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "tests",
        "daily_test_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_column("subscriptions", "free_plan")
    # ### end Alembic commands ###
