"""is_current_affairs added to test model

Revision ID: b15e1be346e6
Revises: 0e97c3115355
Create Date: 2024-07-18 12:57:21.587846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15e1be346e6'
down_revision = '0e97c3115355'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('is_current_affairs', sa.Boolean(), nullable=True))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('tests', 'is_current_affairs')
    # ### end Alembic commands ###
