"""testattempts record addition

Revision ID: f248b345f9e7
Revises: b2251a0a76ab
Create Date: 2024-01-18 17:11:34.567653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f248b345f9e7"
down_revision = "b2251a0a76ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "testattempts", sa.Column("with_omr_sheet", sa.Boolean(), nullable=True)
    )
    op.alter_column(
        "tests",
        "daily_test_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.add_column("users", sa.Column("user_preferences", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "user_preferences")
    op.alter_column(
        "tests",
        "daily_test_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_column("testattempts", "with_omr_sheet")
    # ### end Alembic commands ###
