"""subs id and uuid added for phonepe in sub model

Revision ID: f380e98f3d38
Revises: 56f129299894
Create Date: 2024-03-20 13:31:17.060272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f380e98f3d38'
down_revision = '56f129299894'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('subs_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True))
    op.add_column('subscriptions', sa.Column('subs_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'subs_id')
    op.drop_column('subscriptions', 'subs_uuid')
    # ### end Alembic commands ###
