"""adding purchases to studyplans

Revision ID: 099023a2fba9
Revises: 443cc331f059
Create Date: 2025-02-24 11:19:40.784340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099023a2fba9'
down_revision = '443cc331f059'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plantasks', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('plantaskusers', sa.Column('purchase_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('plantaskusers_plantask_id_key'), 'plantaskusers', ['plantask_id', 'studyplan_id', 'purchase_id', 'student_id'])
    op.create_foreign_key(op.f('plantaskusers_purchase_id_fkey'), 'plantaskusers', 'purchases', ['purchase_id'], ['id'])
    op.alter_column('studyplans', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('studyplanusers', sa.Column('purchase_id', sa.Integer(), nullable=False))
    op.add_column('studyplanusers', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('studyplanusers_studyplan_id_key'), 'studyplanusers', ['studyplan_id', 'purchase_id', 'product_id', 'student_id'])
    op.create_foreign_key(op.f('studyplanusers_purchase_id_fkey'), 'studyplanusers', 'purchases', ['purchase_id'], ['id'])
    op.create_foreign_key(op.f('studyplanusers_product_id_fkey'), 'studyplanusers', 'products', ['product_id'], ['id'])
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('studyplanusers_product_id_fkey'), 'studyplanusers', type_='foreignkey')
    op.drop_constraint(op.f('studyplanusers_purchase_id_fkey'), 'studyplanusers', type_='foreignkey')
    op.drop_constraint(op.f('studyplanusers_studyplan_id_key'), 'studyplanusers', type_='unique')
    op.drop_column('studyplanusers', 'product_id')
    op.drop_column('studyplanusers', 'purchase_id')
    op.alter_column('studyplans', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('plantaskusers_purchase_id_fkey'), 'plantaskusers', type_='foreignkey')
    op.drop_constraint(op.f('plantaskusers_plantask_id_key'), 'plantaskusers', type_='unique')
    op.drop_column('plantaskusers', 'purchase_id')
    op.alter_column('plantasks', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
