"""admission dropoutaddition

Revision ID: f6501b004869
Revises: 1530b1dead70
Create Date: 2025-10-03 09:22:14.129214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6501b004869'
down_revision = '1530b1dead70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions', sa.Column('is_dropout', sa.Boolean(), nullable=True))
    op.alter_column('plantasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantaskusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplans', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplanusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplanusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplans', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantaskusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('admissions', 'is_dropout')
    # ### end Alembic commands ###
