"""removingsubcategory

Revision ID: f0e51453412f
Revises: a0aa8339aa75
Create Date: 2025-03-25 22:44:47.942351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e51453412f'
down_revision = 'a0aa8339aa75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masterdata', 'sub_category')
    op.alter_column('plantasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantaskusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplans', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplanusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplanusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplans', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantaskusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('masterdata', sa.Column('sub_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
