"""seq id in offerings verified and sub cate in masterdata

Revision ID: 075eb85cc582
Revises: 844594dc9427
Create Date: 2025-03-25 10:55:43.545597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075eb85cc582'
down_revision = '844594dc9427'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masterdata', sa.Column('sub_category', sa.String(), nullable=True))
    op.add_column('masterdata', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('offerings', sa.Column('display_seq_id', sa.Integer(), nullable=True))
    op.alter_column('plantasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantaskusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplans', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplanusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplanusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplans', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantaskusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('offerings', 'display_seq_id')
    op.drop_column('masterdata', 'is_verified')
    op.drop_column('masterdata', 'sub_category')
    # ### end Alembic commands ###
