"""testattemmpts assess changes

Revision ID: f634e16ee18c
Revises: 099023a2fba9
Create Date: 2025-02-24 17:32:56.430121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f634e16ee18c'
down_revision = '099023a2fba9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plantasks', sa.Column('last_updated_by', sa.JSON(), nullable=True))
    op.add_column('plantasks', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('plantasks', 'planned_completion_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('plantasks', 'actual_completion_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('plantaskusers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('studyplans', sa.Column('last_updated_by', sa.JSON(), nullable=True))
    op.add_column('studyplans', sa.Column('remarks', sa.String(), nullable=True))
    op.add_column('studyplans', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('studyplanusers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('testattempts', sa.Column('test_evaluator', sa.Integer(), nullable=True))
    op.add_column('testattempts', sa.Column('test_reviewer', sa.Integer(), nullable=True))
    op.add_column('testattempts', sa.Column('test_re_evaluator', sa.Integer(), nullable=True))
    op.add_column('testattempts', sa.Column('test_re_reviewer', sa.Integer(), nullable=True))
    op.add_column('testattempts', sa.Column('submitted_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('testattempts', sa.Column('assigned_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('testattempts', sa.Column('evaluated_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('testattempts', sa.Column('accepted_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('testattempts', sa.Column('rejected_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('testattempts', sa.Column('re_evaluated_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('testattempts', sa.Column('withdrawn_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('testattempts', sa.Column('test_assessment_status', sa.String(), nullable=True))
    op.create_foreign_key(op.f('testattempts_test_re_evaluator_fkey'), 'testattempts', 'users', ['test_re_evaluator'], ['id'])
    op.create_foreign_key(op.f('testattempts_test_reviewer_fkey'), 'testattempts', 'users', ['test_reviewer'], ['id'])
    op.create_foreign_key(op.f('testattempts_test_evaluator_fkey'), 'testattempts', 'users', ['test_evaluator'], ['id'])
    op.create_foreign_key(op.f('testattempts_test_re_reviewer_fkey'), 'testattempts', 'users', ['test_re_reviewer'], ['id'])
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('testattempts_test_re_reviewer_fkey'), 'testattempts', type_='foreignkey')
    op.drop_constraint(op.f('testattempts_test_evaluator_fkey'), 'testattempts', type_='foreignkey')
    op.drop_constraint(op.f('testattempts_test_reviewer_fkey'), 'testattempts', type_='foreignkey')
    op.drop_constraint(op.f('testattempts_test_re_evaluator_fkey'), 'testattempts', type_='foreignkey')
    op.drop_column('testattempts', 'test_assessment_status')
    op.drop_column('testattempts', 'withdrawn_date')
    op.drop_column('testattempts', 're_evaluated_date')
    op.drop_column('testattempts', 'rejected_date')
    op.drop_column('testattempts', 'accepted_date')
    op.drop_column('testattempts', 'evaluated_date')
    op.drop_column('testattempts', 'assigned_date')
    op.drop_column('testattempts', 'submitted_date')
    op.drop_column('testattempts', 'test_re_reviewer')
    op.drop_column('testattempts', 'test_re_evaluator')
    op.drop_column('testattempts', 'test_reviewer')
    op.drop_column('testattempts', 'test_evaluator')
    op.drop_column('studyplanusers', 'is_deleted')
    op.drop_column('studyplans', 'is_deleted')
    op.drop_column('studyplans', 'remarks')
    op.drop_column('studyplans', 'last_updated_by')
    op.drop_column('plantaskusers', 'is_deleted')
    op.alter_column('plantasks', 'actual_completion_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('plantasks', 'planned_completion_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('plantasks', 'is_deleted')
    op.drop_column('plantasks', 'last_updated_by')
    # ### end Alembic commands ###
