"""plan and product map to test attempt

Revision ID: 7a12ba6a9715
Revises: 76dbf4c1b1c5
Create Date: 2025-07-10 13:59:37.027954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a12ba6a9715'
down_revision = '76dbf4c1b1c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plantasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantaskusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplans', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplanusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('testattempts', sa.Column('plantask_id', sa.Integer(), nullable=True))
    op.add_column('testattempts', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('testattempts_plantask_id_fkey'), 'testattempts', 'plantasks', ['plantask_id'], ['id'])
    op.create_foreign_key(op.f('testattempts_product_id_fkey'), 'testattempts', 'products', ['product_id'], ['id'])
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('testattempts_product_id_fkey'), 'testattempts', type_='foreignkey')
    op.drop_constraint(op.f('testattempts_plantask_id_fkey'), 'testattempts', type_='foreignkey')
    op.drop_column('testattempts', 'product_id')
    op.drop_column('testattempts', 'plantask_id')
    op.alter_column('studyplanusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studyplans', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantaskusers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plantasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
