"""refund added for purchases

Revision ID: 359430969a7d
Revises: d40bfec5e8ab
Create Date: 2025-01-06 16:58:57.498935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359430969a7d'
down_revision = 'd40bfec5e8ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('refund_tx_id', sa.Integer(), nullable=True))
    op.add_column('purchases', sa.Column('refund_amount', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('purchases_refund_tx_id_fkey'), 'purchases', 'transactions', ['refund_tx_id'], ['id'])
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('purchases_refund_tx_id_fkey'), 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'refund_amount')
    op.drop_column('purchases', 'refund_tx_id')
    # ### end Alembic commands ###
