"""purchase and installments in txs

Revision ID: 9d2851c0275f
Revises: 359430969a7d
Create Date: 2025-01-09 13:16:12.622195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2851c0275f'
down_revision = '359430969a7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('purchase_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('purchaseinstallment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('transactions_purchaseinstallment_id_fkey'), 'transactions', 'purchaseinstallments', ['purchaseinstallment_id'], ['id'])
    op.create_foreign_key(op.f('transactions_purchase_id_fkey'), 'transactions', 'purchases', ['purchase_id'], ['id'])
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('transactions_purchase_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_purchaseinstallment_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'purchaseinstallment_id')
    op.drop_column('transactions', 'purchase_id')
    # ### end Alembic commands ###
