"""teaching app models

Revision ID: 713ed7522cb5
Revises: ec2dd08f4b9a
Create Date: 2025-02-19 10:14:50.466644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '713ed7522cb5'
down_revision = 'ec2dd08f4b9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studyplans',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('studyplans_batch_id_fkey')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('studyplans_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], name=op.f('studyplans_offering_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('studyplans_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('studyplans_pkey'))
    )
    op.create_table('plantasks',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('task_seq_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('studyplan_id', sa.Integer(), nullable=False),
    sa.Column('papers', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('subjects', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('subject_area', sa.String(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('study_materials', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('planned_time', sa.Integer(), nullable=True),
    sa.Column('planned_completion_date', sa.DateTime(), nullable=True),
    sa.Column('actual_completion_date', sa.DateTime(), nullable=True),
    sa.Column('target_marks', sa.Integer(), nullable=True),
    sa.Column('links', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('reference_materials', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.JSON(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('plantasks_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['studyplan_id'], ['studyplans.id'], name=op.f('plantasks_studyplan_id_fkey')),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('plantasks_test_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plantasks_pkey'))
    )
    op.create_table('studyplanusers',
    sa.Column('studyplan_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('studyplanusers_enrollment_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('studyplanusers_student_id_fkey')),
    sa.ForeignKeyConstraint(['studyplan_id'], ['studyplans.id'], name=op.f('studyplanusers_studyplan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('studyplanusers_pkey'))
    )
    op.create_table('plantaskusers',
    sa.Column('plantask_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('studyplan_id', sa.Integer(), nullable=False),
    sa.Column('student_remarks', sa.String(), nullable=True),
    sa.Column('teacher_remarks', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plantask_id'], ['plantasks.id'], name=op.f('plantaskusers_plantask_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('plantaskusers_student_id_fkey')),
    sa.ForeignKeyConstraint(['studyplan_id'], ['studyplans.id'], name=op.f('plantaskusers_studyplan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plantaskusers_pkey'))
    )
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('plantaskusers')
    op.drop_table('studyplanusers')
    op.drop_table('plantasks')
    op.drop_table('studyplans')
    # ### end Alembic commands ###
