"""uniqueness contraint on masterdata

Revision ID: ec6cbbc84f31
Revises: 693e930ebd74
Create Date: 2025-02-17 12:41:14.284526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6cbbc84f31'
down_revision = '693e930ebd74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('masterdata_category_key'), 'masterdata', ['category', 'value'])
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('masterdata_category_key'), 'masterdata', type_='unique')
    # ### end Alembic commands ###
